(function(T,D,R,G){'use strict';
// Domain integration uses the existing deterministic engines; no separate safety rules.
const guard=G.guard,reset=G.reset;G.guard=target=>guard(target==='trauma'?'screen':target);G.reset=()=>{T.clear();reset();};
const safetyPaths=['suicide.currentIdeation','suicide.desireToDie','suicide.intent','suicide.plan','suicide.preparation','suicide.unableToStaySafe','selfHarm.recentBehavior','harmToOthers.actualDesire','harmToOthers.intent','harmToOthers.plan','harmToOthers.preparation','medical.lossOfConsciousness','medical.seizure','medical.severeConfusion','medical.severeHeadInjury','substances.overdoseConcern','substances.severeWithdrawalConcern','selfCare.unableToRemainSafelyAlone','psychosis.dangerousBehaviorFromBeliefs'];
const safetyLabels={"selfHarm.recentBehavior":"traumaSafety.selfHarm_recentBehavior","medical.lossOfConsciousness":"traumaSafety.medical_lossOfConsciousness","medical.seizure":"traumaSafety.medical_seizure","medical.severeConfusion":"traumaSafety.medical_severeConfusion","medical.severeHeadInjury":"traumaSafety.medical_severeHeadInjury","substances.overdoseConcern":"traumaSafety.substances_overdoseConcern","substances.severeWithdrawalConcern":"traumaSafety.substances_severeWithdrawalConcern","selfCare.unableToRemainSafelyAlone":"traumaSafety.selfCare_unableToRemainSafelyAlone","psychosis.dangerousBehaviorFromBeliefs":"traumaSafety.psychosis_dangerousBehaviorFromBeliefs"};
const safety={id:'safety',label:'traumaUI.safety',questions:safetyPaths.map(path=>({id:'safety.'+path,label:(safetyLabels[path]?I18n.pair(safetyLabels[path]):G.questionLabels[path])||G.domainNames[({harmToOthers:'harm_to_others',selfHarm:'self_harm',selfCare:'self_care',substances:'substance'})[path.split('.')[0]]||path.split('.')[0]],options:['yes','no','unknown'].map(v=>[v,...I18n.pair(({yes:'traumaUI.option_yes',no:'traumaUI.option_no',unknown:'traumaUI.option_unknown'})[v])])}))};
T.sections.splice(1,0,...[0,1,2,3].map(i=>({...safety,id:'safety'+i,questions:safety.questions.slice(i*5,(i+1)*5)})));T.questions=T.sections.flatMap(s=>s.questions);
const update=T.update;T.update=(p,v)=>{update(p,v);if(p.startsWith('safety.'))G.answer(p.slice(7),T.tri(v));};
const collect=G.collect;G.collect=()=>{const base=collect();if(!T.store.state.revision)return base;const signals=G.empty();let failed=false;for(const p of safetyPaths){const value=Assessment.get(T.store.state,'safety.'+p);if(value!==undefined&&!['yes','no','unknown'].includes(value))failed=true;G.put(signals,p,T.tri(value));}const merged=G.merge([base.signals,signals]);return {...G.evaluate(merged.signals,{failed:failed||base.assessmentStatus==='unable_to_assess'}),signals:merged.signals,sources:[...base.sources,{module:'trauma',revision:T.store.state.revision}]};};
// Safety answers are owned by the shared engine; clearing this questionnaire cannot erase them.
const oldValid=D.validEvidence;D.validEvidence=e=>e?.sourceModule==='trauma'||e?.domain==='trauma'?!!e&&['trauma','mood','anxiety','ocd','router','clarification'].includes(e.sourceModule)&&e.domain===e.concept.split('.')[0]&&Object.hasOwn(D.concepts,e.concept)&&oldValid({...e,sourceModule:'mood',domain:'mood',concept:'mood.low'}):oldValid(e);
for(const [id,label]of Object.entries(T.factLabels))D.concepts['trauma.'+id]=label;
D.concepts['trauma.medical']='traumaUI.q_medical_contribution';D.concepts['trauma.substance']='traumaUI.q_substance_contribution';
const modules=D.modules;D.modules=()=>({...modules(),trauma:T});D.store.selected.trauma=true;
const adapt=D.adapt;D.adapt=(name,store,module)=>{if(name!=='trauma')return adapt(name,store,module);const s=store?.state,r=store?.result;if(!r||r.revision!==s.revision||s.intro.agree!=='yes'||s.intro.adult!=='yes')return {evidence:[],ready:false,invalid:false};return {ready:true,invalid:T.questions.filter(q=>T.visible(q,s)).some(q=>!Assessment.validAnswer(q,Assessment.get(s,q.id))),evidence:[...Object.entries(r.facts).map(([k,v])=>D.fact('trauma.'+k,v,'trauma',T.questions.filter(q=>q.id.startsWith(({duration:'course',impairment:'function',current:'course'})[k]||k)).map(q=>q.id),s.revision,'structured_assessment','current',T.version)),D.fact('unsupported.psychotic',r.psychoticFlag,'trauma',['dissociation.fixed','dissociation.reality'],s.revision,'structured_assessment','current',T.version),...['medical','substance'].map(k=>D.fact('trauma.'+k,k==='medical'&&r.ruleouts.includes('medical.memory')?T.tri(s.medical.memory):T.tri(s[k]?.contribution),'trauma',k==='medical'?['medical.contribution','medical.memory']:[k+'.contribution'],s.revision,'exclusion','current',T.version))]};};
D.directions.trauma={label:'traumaUI.compatible',domain:'trauma',required:Object.keys(T.factLabels).map(k=>'trauma.'+k)};
D.rules.push({id:'DIFF_TRAUMA_CLUSTERS_001',comparison:'trauma_existing_domains',all:Object.fromEntries(['exposure','intrusion','avoidance','negative','arousal','duration','current','impairment'].map(k=>['trauma.'+k,true])),effects:[{direction:'trauma',support:3}],explanationKey:'traumaUI.comparison',evidenceSource:'normalized_structured_evidence',reviewStatus:'unreviewed',version:D.version});
const routerEvidence=D.adaptRouter;D.adaptRouter=p=>[...routerEvidence(p),...(R.validate(p)?[['exposure','exposure'],['reliving','intrusion'],['avoidance','avoidance'],['alertness','arousal']].map(([a,b])=>D.fact('trauma.'+b,p.trauma[a],'router',['trauma.'+a],0,'free_text_extraction','current',R.version)):[])];
const evaluate=D.evaluate;D.evaluate=(e,s,o)=>{const r=evaluate(e,s,o);if(r.blocked)return r;const supported=r.primaryDirections.includes('trauma')||r.secondaryDirections.includes('trauma');if(supported){for(const [other,key]of [['mood','traumaUI.moodCompare'],['gad','traumaUI.anxietyCompare'],['ocd','traumaUI.ocdCompare'],['panic','traumaUI.anxietyCompare']])if(r.candidates.some(c=>c.id===other&&c.level>=2))r.possibleCooccurringPatterns.push({directions:['trauma',other],key});}return r;};
})(globalThis.Trauma,globalThis.Differential,globalThis.SymptomRouter,globalThis.GlobalSafety);
