(function(A,V,D,G){'use strict';
const text=(k,l=lang,values={})=>I18n.t(k,l,values),E=s=>esc(String(s));
const statuses={stop_sufficient:'adaptive.stop_sufficient',stop_multiple_supported:'adaptive.stop_multiple_supported',stop_insufficient:'adaptive.stop_insufficient',stop_user:'adaptive.stop_user',stop_budget:'adaptive.stop_budget',stop_safety:'adaptive.stop_safety',stop_unsupported:'adaptive.stop_unsupported'};
A.questionText=(q,l=lang)=>text(q.questionKey,l,{concept:V.concepts[q.conceptTarget]?text(V.concepts[q.conceptTarget],l):q.conceptTarget});
A.entry=()=>'<button class="secondary" data-adaptive-start>'+E(text('adaptive.entry'))+'</button>';
A.render=function(){
 const gate=A.gate();if(gate.show)return G.panel(gate.result);const r=A.current(),s=A.store.session;if(!r)return '<section class="page"><h1>'+E(text('adaptive.title'))+'</h1>'+A.entry()+'</section>';
 const q=r.nextQuestion,msg=k=>E(text(k));
 let body='';
 if(q){body=`<p role="status" id="adaptive-progress">${E(text('adaptive.progress',lang,{number:r.questionsAsked+1,budget:s.budget}))}</p><p>${E(text('adaptive.scope',lang,{domains:q.domainsCompared.map(d=>text(SymptomRouter.domains.get(d).label)).join(' / ')}))}</p><form id="adaptive-form"><fieldset aria-describedby="adaptive-progress"><legend>${E(A.questionText(q))}</legend>${q.answerOptions.map(o=>`<label class="adaptive-option"><input id="adaptive-answer-${q.id}-${o.value}" type="radio" name="adaptive-answer" value="${o.value}" ${A.store.draft?.questionId===q.id&&A.store.draft?.value===o.value?'checked':''}>${E(text(o.labelKey))}</label>`).join('')}</fieldset>${A.store.error?'<p role="alert">'+msg('adaptive.error')+'</p>':''}<details id="adaptive-why"><summary>${msg('adaptive.why')}</summary><p>${E(text(q.whyKey))}</p></details><div class="actions"><button type="submit">${msg('adaptive.next')}</button><button type="button" class="secondary" data-adaptive-stop>${msg('adaptive.stop')}</button></div></form><details id="adaptive-safety"><summary>${msg('adaptive.safetySubmit')}</summary><form id="adaptive-safety-form"><label for="adaptive-safety-text">${msg('adaptive.safetyText')}</label><textarea id="adaptive-safety-text" maxlength="3000" rows="3" aria-describedby="adaptive-safety-help"></textarea><p id="adaptive-safety-help">${msg('adaptive.safetyHelp')}</p><button type="submit">${msg('adaptive.safetySubmit')}</button></form></details>`;}
 else{const d=s.differential;body=`<h2>${msg('adaptive.finish')}</h2><p role="status">${msg(statuses[r.adaptiveStatus])}</p><h3>${msg('differential.primary')}</h3><ul>${d.primaryDirections.map(id=>'<li>'+E(text(D.directions[id].label))+'</li>').join('')}</ul><h3>${msg('adaptive.uncertainty')}</h3><ul>${[...new Set([...d.missingEvidence,...d.unresolvedRuleOuts,...d.unresolvedDiscriminators.map(x=>x.conceptNeeded)])].map(k=>'<li>'+E(V.concepts[k]?text(V.concepts[k]):D.describe(k,lang))+'</li>').join('')}</ul><h3>${msg('adaptive.answered')}</h3><ol>${s.answers.map(a=>{const q=A.registry.find(q=>q.id===a.questionId);return '<li>'+E(q?A.questionText(q):text('adaptive.q_conflict',lang,{concept:text(V.concepts[a.targets[0]])}))+': '+E(q?text(q.answerOptions.find(o=>o.value===a.value).labelKey):text(({yes:'adaptive.yes',no:'adaptive.no',unknown:'adaptive.unknown',prefer:'adaptive.prefer'})[a.value]))+'</li>';}).join('')}</ol><p>${msg('adaptive.nextStep')}</p><details><summary>${msg('differential.summary')}</summary><textarea readonly rows="12" aria-label="${msg('differential.summary')}">${E(V.summary(d,lang))}</textarea></details><div class="actions"><button data-diff-open>${msg('adaptive.compare')}</button><button class="secondary" data-adaptive-start>${msg('adaptive.restart')}</button></div>`;}
 return `<section class="page adaptive-page" aria-labelledby="adaptive-heading"><h1 id="adaptive-heading" tabindex="-1">${msg('adaptive.title')}</h1><p>${E(text('adaptive.intro',lang,{budget:s.budget}))}</p><p>${msg('adaptive.limit')}</p>${body}<p>${msg('adaptive.review')}</p></section>`;
};
A.bind=function(){document.querySelectorAll('[data-adaptive-start]').forEach(b=>b.onclick=()=>{navigate(A.start());document.getElementById('adaptive-heading')?.focus();});document.querySelectorAll('[name=adaptive-answer]').forEach(input=>input.onchange=()=>{A.store.draft={questionId:A.store.session.result.nextQuestion.id,value:input.value};});const form=document.getElementById('adaptive-form');if(form)form.onsubmit=e=>{e.preventDefault();const value=form.querySelector('input:checked')?.value;if(!value){A.store.error=true;render();return;}A.submit(A.store.session.result.nextQuestion.id,value);render();document.getElementById('adaptive-heading')?.focus();};document.querySelector('[data-adaptive-stop]')?.addEventListener('click',()=>{A.stop(A.store.session);render();document.getElementById('adaptive-heading')?.focus();});const safety=document.getElementById('adaptive-safety-form');if(safety)safety.onsubmit=e=>{e.preventDefault();A.safetyText(document.getElementById('adaptive-safety-text').value);render();};const raw=document.getElementById('adaptive-safety-text');if(raw)raw.oninput=()=>{const parsed=G.validateExtraction(G.extract(raw.value));if(G.evaluate(parsed.signals,{failed:!parsed.valid}).requiresInterruption){A.safetyText(raw.value);render();}};};
})(globalThis.Adaptive,globalThis.DifferentialV2,globalThis.Differential,globalThis.GlobalSafety);
