(function(V){'use strict';
V.evaluate=function(profile,session=V.session(),safety=null){const r={version:V.version,routerVersion:V.version,primaryRoute:null,secondaryRoutes:[],candidateRoutes:[],unsupportedDomainFlags:[],unsupportedSignals:[],unresolvedQuestions:[],routingStatus:'insufficient',confidenceStatus:'insufficient',clarificationRecommended:false,clarification:null,explanationKeys:['router.notDiagnosis'],matchedRules:[],contradictions:[],stopReason:null};if(safety?.requiresInterruption||safety?.assessmentStatus==='unable_to_assess'){r.routingStatus='safety_interrupted';r.stopReason='safety';return r;}if(!V.validate(profile)){r.unresolvedQuestions=['invalid_profile'];return r;}const f=profile.facts;
for(const d of V.domains.values()){const hits=d.rules.filter(rule=>V.matches(f,rule));if(!hits.length)continue;const support=[...new Set(hits.flatMap(rule=>[...(rule.all||[]),...(rule.any||[]).filter(k=>f[k]===true)]))],opposing=(d.opposingFeatures||[]).filter(k=>f[k]===true);let rank=Math.max(...hits.map(x=>x.rank));if(opposing.length)rank=Math.min(rank,1);const evidence=paths=>paths.map(path=>({concept:path,evidenceIds:profile.evidence.filter(e=>e.path===path).map(e=>e.id)}));r.candidateRoutes.push({domain:d.id,rank,relevance:rank>=3?'high':rank===2?'moderate':'tentative',supportingEvidence:evidence(support),opposingEvidence:evidence(opposing),discriminatingEvidence:evidence(support.filter(p=>d.discriminatingFeatures.includes(p))),supportingSignals:support,explanationKeys:[...new Set(hits.map(h=>h.explanationKey))]});r.matchedRules.push(...hits.map(h=>h.id));}
for(const candidate of r.candidateRoutes){const d=V.clarificationDiscriminators[candidate.domain];if(!d||f[d.path]!==true)continue;const evidenceIds=profile.evidence.filter(e=>e.path===d.path&&e.source==='clarification'&&e.value===true).map(e=>e.id);if(!evidenceIds.length)continue;const evidence={concept:d.path,evidenceIds};candidate.supportingEvidence.push(evidence);candidate.discriminatingEvidence.push(evidence);candidate.explanationKeys.push(d.explanationKey);}
r.candidateRoutes.sort((a,b)=>b.rank-a.rank||[...V.domains.keys()].indexOf(a.domain)-[...V.domains.keys()].indexOf(b.domain));r.unsupportedDomainFlags=Object.keys(V.unsupported).filter(k=>f['unsupported.'+k]===true);r.unsupportedSignals=[...r.unsupportedDomainFlags];if(f['general.suddenCognition']===true&&!r.unsupportedDomainFlags.includes('cognitive'))r.unsupportedDomainFlags.push('cognitive');
const [first,second]=r.candidateRoutes;if(f['general.suddenCognition']===true){r.primaryRoute=null;r.routingStatus='unsupported';r.stopReason='medical_review';}else if(first?.rank>=2){const tied=second?.rank===first.rank;r.routingStatus=tied?'ambiguous':'sufficient';r.primaryRoute=tied?null:first.domain;}else if(r.unsupportedDomainFlags.length){r.routingStatus='unsupported';r.stopReason='unsupported';}
for(const path of V.paths){const rows=profile.evidence.filter(e=>e.path===path&&e.value!=='unknown');if(new Set(rows.map(e=>e.value)).size>1)r.contradictions.push({concept:path,evidenceIds:rows.map(e=>e.id),selectedValue:f[path]});}
if(session.preference&&V.domains.has(session.preference)){r.primaryRoute=session.preference;r.explanationKeys.push('router.userChoice');}r.secondaryRoutes=r.candidateRoutes.filter(c=>c.domain!==r.primaryRoute).map(c=>c.domain);r.confidenceStatus=r.routingStatus==='sufficient'?'sufficient':r.routingStatus==='ambiguous'?'uncertain':'insufficient';
if(!session.stopped&&session.order.length<session.maxQuestions&&!['unsupported','safety_interrupted'].includes(r.routingStatus)){r.clarification=V.selectClarification(profile,r,session);r.clarificationRecommended=!!r.clarification;}
if(session.stopped)r.stopReason='user_stopped';else if(session.order.length>=session.maxQuestions)r.stopReason='question_limit';else if(r.routingStatus==='sufficient'&&!r.clarification)r.stopReason='discriminated';else if(r.routingStatus==='ambiguous'&&!r.clarification){r.stopReason='multiple_relevant';}else if(!r.clarification&&!r.stopReason)r.stopReason='insufficient';r.unresolvedQuestions=r.clarification?[r.clarification.id]:[];return r;};
V.answer=function(profile,session,id,value){const q=V.questions.find(q=>q.id===id);if(!V.validate(profile)||!q||!q.options.some(o=>o.value===value)||session.stopped||session.order.includes(id)||session.order.length>=session.maxQuestions)throw Error('Invalid clarification');const p=JSON.parse(JSON.stringify(profile)),s=JSON.parse(JSON.stringify(session));s.answers[id]=value;s.order.push(id);if(['unknown','prefer'].includes(value))s.stopped=true;for(const [path,v]of Object.entries(q.options.find(o=>o.value===value).effects||{}))p.evidence.push({id:'clarification:'+id+':'+path,path,value:v,source:'clarification',context:{subject:'self',temporality:'current',polarity:v?'affirmed':'denied',quotationStatus:'direct_self_report',certainty:'reported'}});V.normalize(p);return {profile:p,session:s};};
V.selectClarification=(p,r,s)=>{const domains=r.candidateRoutes.map(c=>c.domain);return V.questions.filter(q=>!s.order.includes(q.id)&&V.matches(p.facts,q.requiredEvidence)&&(!q.domainsCompared.length||q.domainsCompared.every(d=>domains.includes(d)))&&(!q.stopWhenKnown||q.stopWhenKnown.some(k=>p.facts[k]==='unknown'))&&(r.routingStatus!=='sufficient'||q.refinement||q.domainsCompared.length>1)).sort((a,b)=>b.informationValue-a.informationValue||a.id.localeCompare(b.id))[0]||null;};
})(globalThis.RouterV2);
