(function(V,R){'use strict';
V.version='symptom-router-v2.0.0';V.reviewStatus='unreviewed';V.legacy={extract:R.extract,route:R.route,render:R.render,bind:R.bind,clear:R.clear,resume:R.resume,choose:R.choose};
V.extra=['mood.episodicElevation','mood.reducedNeedForSleep','adhd.crossSetting','adhd.preTrauma','adhd.preMood','adhd.preWorry','psychosis.realityDifficulty','psychosis.disorganization','psychosis.negativeFeatures','eating.lowInterest','eating.moodAppetite','eating.contamination','general.attention','general.traumaLinked','general.moodLinked','general.suddenCognition','general.onsetRecent','general.chronic','general.memory','trauma.nightmares','trauma.dissociation','trauma.negativeMood','unsupported.autism','unsupported.substance','unsupported.sleep','unsupported.somatic','unsupported.personality','unsupported.cognitive','unsupported.grief','unsupported.bdd','unsupported.hoarding'];
V.paths=[...new Set([...R.paths,...V.extra])];V.empty=()=>({schemaVersion:V.version,facts:Object.fromEntries(V.paths.map(p=>[p,'unknown'])),evidence:[],course:{duration:'unknown',frequency:'unknown',severity:'unknown'}});
V.validate=p=>!!p&&p.schemaVersion===V.version&&p.facts&&Object.keys(p.facts).length===V.paths.length&&V.paths.every(k=>[true,false,'unknown'].includes(p.facts[k]))&&Array.isArray(p.evidence)&&p.evidence.length<=500&&new Set(p.evidence.map(e=>e.id)).size===p.evidence.length&&p.evidence.every(e=>V.paths.includes(e.path)&&[true,false,'unknown'].includes(e.value)&&['extraction','clarification'].includes(e.source)&&['self','other','unclear'].includes(e.context?.subject)&&['current','recent','historical','hypothetical','unclear'].includes(e.context.temporality)&&['affirmed','denied','uncertain'].includes(e.context.polarity)&&['direct_self_report','quoted_speech','reported_speech','clinician_question','unclear'].includes(e.context.quotationStatus)&&['reported','uncertain'].includes(e.context.certainty));
V.normalize=p=>{for(const path of V.paths){const rows=p.evidence.filter(e=>e.path===path&&e.value!=='unknown'&&e.context.subject==='self'&&(['current','recent'].includes(e.context.temporality)||(path==='trauma.exposure'&&e.context.temporality==='historical'))&&e.context.quotationStatus==='direct_self_report'&&e.context.certainty==='reported'),strong=rows.filter(e=>e.source==='clarification'),values=[...new Set((strong.length?strong:rows).map(e=>e.value))];p.facts[path]=values.length===1?values[0]:'unknown';}return p;};
const structural=V.validate;
const exact=(o,keys)=>o&&typeof o==='object'&&!Array.isArray(o)&&Object.keys(o).length===keys.length&&keys.every(k=>Object.hasOwn(o,k));
V.validate=p=>!!structural(p)&&exact(p,['schemaVersion','facts','evidence','course'])&&exact(p.course,['duration','frequency','severity'])&&['unknown','brief','persistent'].includes(p.course.duration)&&['unknown','repeated'].includes(p.course.frequency)&&['unknown','marked'].includes(p.course.severity)&&p.evidence.every(e=>exact(e,['id','path','value','source','context'])&&typeof e.id==='string'&&/^(?:e\d+|clarification:[a-zA-Z]+:[a-zA-Z.]+)$/.test(e.id)&&exact(e.context,['subject','temporality','polarity','quotationStatus','certainty']));
const validStructure=V.validate;V.validate=p=>{try{if(!validStructure(p))return false;const normalized=V.normalize(JSON.parse(JSON.stringify(p)));return V.paths.every(k=>normalized.facts[k]===p.facts[k]);}catch{return false;}};
V.toLegacy=p=>{const old=R.empty();if(!V.validate(p))return old;for(const path of R.paths)R.put(old,path,p.facts[path]);old.course={...p.course};
// The v1 projection carries normalized facts, not a truncated evidence log. The complete log remains in v2.
old.observations=R.paths.filter(path=>p.facts[path]!=='unknown').map(path=>({path,value:p.facts[path],context:{subject:'self',temporality:'current',polarity:p.facts[path]?'affirmed':'denied',uncertainty:false}}));return old;};
V.domains=new Map();V.registerDomain=d=>{if(!d||!R.domains.has(d.id)||V.domains.has(d.id)||!Array.isArray(d.rules))throw Error('Invalid routing domain registration');V.domains.set(d.id,Object.freeze({...d,version:V.version,reviewStatus:'unreviewed'}));};
V.session=()=>({answers:{},order:[],stopped:false,maxQuestions:3});
V.matches=(f,r)=>(r.all||[]).every(p=>f[p]===true)&&(!(r.any||[]).length||r.any.some(p=>f[p]===true))&&(r.none||[]).every(p=>f[p]!==true);
})(globalThis.RouterV2={},globalThis.SymptomRouter);
