const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const c={lang:0,esc:v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')};vm.createContext(c);for(const f of ['runtime','catalog'])vm.runInContext(fs.readFileSync('dist/i18n/'+f+'.js','utf8'),c);for(const p of ['schema','rules','engine','adapters','extraction','resources','runtime','ui'])vm.runInContext(fs.readFileSync('dist/safety/'+p+'.js','utf8'),c);
for(const p of ['shared/core','shared/safety','shared/fields','mood/data','mood/scoring','mood/safety','mood/state','mood/engine','mood/ui','mood/summary','anxiety/data','anxiety/state','anxiety/engine','anxiety/summary','anxiety/ui'])vm.runInContext(fs.readFileSync('dist/'+p+'.js','utf8'),c,{filename:p});
const A=c.Anxiety,M=c.Mood,set=A.setAnswer;const report=[];
function fill(s){for(const sec of A.plan(s))for(const q of sec.questions){if(A.get(s,q.id)!==undefined)continue;const val=q.options.find(o=>o[0]==='no')?.[0]??q.options.find(o=>o[0]==='0')?.[0]??q.options.find(o=>o[0]==='none')?.[0]??q.options[0][0];s=set(s,q.id,val);}return s;}
function base(){let s=fill(A.emptyState());for(const [k,v]of Object.entries({'intro.age':'adult','intro.respondent':'self','intro.agree':'yes','function.work':'2'}))s=set(s,k,v);return fill(s);}
function branch(s,id){s=set(s,'clusters.'+id,'yes');s=fill(s);for(const q of A.sections.find(sec=>sec.id===id).questions){const k=q.id,v=k.endsWith('.duration')?'6plus':k.endsWith('.impact')?'2':'yes';s=set(s,k,v);}return s;}
function test(name,fn){fn();report.push(name);console.log('PASS '+name);}
const fixtures=[];
test('1 high GAD-7 and independently chronic generalized worry',()=>{let s=branch(base(),'gad');for(let i=0;i<7;i++)s=set(s,'gad7.'+i,'3');let r=A.assess(s);assert.equal(r.screening.total,21);assert(r.leading.includes('gad'));assert.equal(r.directions[0].level,3);fixtures.push(s);s=set(s,'gad.duration','under4w');assert(!A.assess(s).leading.includes('gad'));assert(A.assess(s).discrepancy);});
test('2 recurrent unexpected panic, not any single attack',()=>{let s=branch(base(),'panic');assert(A.assess(s).leading.includes('panic'));fixtures.push(s);for(const p of ['panic.recurrent','panic.unexpected','panic.month','panic.abrupt'])assert(!A.assess(set(s,p,'no')).leading.includes('panic'));s=set(s,'panic.concern','no');assert(A.assess(s).leading.includes('panic'));s=set(s,'panic.behavior','no');assert(!A.assess(s).leading.includes('panic'));});
test('3 panic and agoraphobia independently and concurrently',()=>{let s=branch(branch(base(),'panic'),'agora');assert(A.assess(s).leading.includes('panic'));assert(A.assess(s).leading.includes('agora'));fixtures.push(s);s=set(s,'clusters.panic','no');assert(A.assess(s).leading.includes('agora'));assert(!A.assess(s).leading.includes('panic'));for(const p of ['open','enclosed','alone','crowds'])s=set(s,'agora.places.'+p,'no');assert(!A.assess(s).leading.includes('agora'));});
test('4 social evaluation only; shyness without impact is not pattern',()=>{let s=branch(base(),'social');assert.deepEqual(Array.from(A.assess(s).leading),['social']);fixtures.push(s);assert(!A.assess(set(s,'social.impact','0')).leading.includes('social'));});
test('5 specific stimulus fear',()=>{let s=branch(base(),'specific');for(const k of ['nature','blood','situation','other'])s=set(s,'specific.triggers.'+k,'no');assert.deepEqual(Array.from(A.assess(s).leading),['specific']);fixtures.push(s);assert(!A.assess(set(s,'specific.disproportion','no')).leading.includes('specific'));});
test('6 stimulant timing raises causal differential without confirming causation',()=>{let s=set(base(),'substance.exposures.stimulant','yes');s=set(s,'substance.temporal','start');const r=A.assess(s);assert(r.leading.includes('substance'));assert.equal(r.directions.find(d=>d.id==='substance').level,2);fixtures.push(s);assert(!A.assess(set(s,'substance.temporal','none')).leading.includes('substance'));});
test('7 depression cross-module signals and explicit current-page Mood inclusion',()=>{let s=set(branch(base(),'gad'),'context.depression','yes');let r=A.assess(s);assert(r.mood.depression);assert.equal(r.directions[0].level,2);fixtures.push(s);let mood=JSON.parse(fs.readFileSync('work/mood-fixture.json','utf8'));s=set(s,'context.depression','no');assert(!A.assess(s,mood).mood.included);s=set(s,'context.useMood','yes');r=A.assess(s,mood);assert(r.mood.included);assert(r.mood.depression);assert.equal(r.mood.revision,mood.revision);const snapshot=JSON.stringify(mood);A.assess(s,mood);assert.equal(JSON.stringify(mood),snapshot);mood=M.setAnswer(mood,'mania.pastMania','yes');assert(A.assess(s,mood).mood.bipolar);});
test('8 physical emergency overrides low score and every diagnostic direction',()=>{const s=set(base(),'intro.chest','yes'),r=A.assess(s);assert.equal(r.screening.total,0);assert.equal(r.safety.action,'immediate');assert.equal(r.safety.medical.length,1);assert.equal(r.leading.length,0);fixtures.push(s);});
test('9 suicidal ideation follows identical shared safety rules',()=>{let s=set(base(),'safety.thoughts','yes');assert.equal(A.assess(s).safety.action,'prompt');fixtures.push(s);for(const key of ['current','plan','intent','attempt','unableSafe','injury']){const next=set(s,'safety.'+key,'yes');assert.equal(A.assess(next).safety.action,M.safety(next).action);assert.equal(A.assess(next).leading.length,0);}assert.equal(A.assess(set(s,'safety.means','yes')).safety.action,'immediate');});
test('Separation: adult six months, younger four weeks, caregiver gate',()=>{let s=branch(base(),'separation');assert(A.assess(s).leading.includes('separation'));s=set(s,'separation.duration','1to5m');assert(!A.assess(s).leading.includes('separation'));s=set(s,'intro.age','youth');assert(A.assess(s).leading.includes('separation'));assert(!A.assess(s).screening.applicable);assert.equal(A.assess(s).directions.find(d=>d.id==='separation').level,2);s=set(s,'intro.age','child');assert(!A.assess(s).eligible);s=set(s,'intro.respondent','caregiver');assert(A.assess(s).eligible);assert(A.assess(s).leading.includes('separation'));});
test('Score bands, unanswered values, caregiver no proxy score',()=>{for(const [total,band]of [[0,0],[4,0],[5,1],[9,1],[10,2],[14,2],[15,3],[21,3]]){let s=base(),left=total;for(let i=0;i<7;i++){s=set(s,'gad7.'+i,String(Math.min(3,left)));left=Math.max(0,left-3);}assert.equal(A.scoreGAD7(s).band,band);}assert.equal(A.scoreGAD7(set(base(),'gad7.0','unknown')).total,null);assert(!A.scoreGAD7(set(base(),'intro.respondent','caregiver')).applicable);});
test('Unknowns, invalid answers, branch clearing and result invalidation',()=>{assert.equal(A.assess(A.emptyState()).leading.length,0);let s=branch(base(),'gad');s=set(s,'gad.duration','unknown');assert(!A.assess(s).leading.includes('gad'));assert(A.assess(s).unresolved.some(q=>q.key==='gad.duration'));s=set(s,'clusters.gad','no');assert.equal(Object.keys(s.gad).length,0);assert(!A.plan(s).some(sec=>sec.id==='gad'));assert.throws(()=>set(s,'gad7.0','9'));A.store.state=branch(base(),'gad');A.store.result=A.assess(A.store.state);A.update('gad.duration','under4w');assert.equal(A.store.result,null);assert(!A.assess(A.store.state).leading.includes('gad'));A.clear();assert.equal(A.store.state.revision,0);});
test('All nine cases render full results and clinician summaries in both global languages',()=>{for(const [i,s]of fixtures.entries())for(const l of [0,1]){c.lang=l;A.store.state=s;A.store.step='results';const r=A.assess(s),out=A.summary(s,r,l),html=A.render();assert(out.startsWith(l?'Assessment Summary':'评估摘要'));assert(html.includes(l?'AI-Assisted Anxiety Assessment':'AI 辅助焦虑评估'));assert(html.includes(l?'Why this result?':'为什么得到这个结果？'));assert(html.includes(l?'Clinician-style record':'给专业人员的结构化记录'));assert(!html.includes('undefined'));assert(!out.includes('undefined'));assert(html.includes(A.disclaimer[l]));for(const d of A.disorders)assert(html.includes(d.name[l]));if(i===7)assert(html.includes(l?'Seek emergency medical help first':'先获得紧急医疗帮助'));if(i===8)assert(html.includes(l?'Contact a professional promptly':'请尽快联系专业人员'));}});
test('No answer persistence, analytics or network calls',()=>{const code=['data','state','engine','summary','ui'].map(f=>fs.readFileSync('dist/anxiety/'+f+'.js','utf8')).join('\n');assert(!/localStorage|sessionStorage|indexedDB|fetch\(|XMLHttpRequest|sendBeacon/.test(code));});
test('Shared page safety includes Mood signals independently of diagnostic opt-in',()=>{let mood=M.emptyState();mood=M.setAnswer(mood,'safety.current','yes');const r=A.assess(base(),mood);assert.equal(r.mood.included,false);assert.equal(r.safety.action,'immediate');assert(r.safety.acute.some(e=>e.key==='mood.current'));assert.equal(r.leading.length,0);assert.equal(A.assess(set(base(),'intro.chest','unknown')).safety.action,'clarify');});
fs.writeFileSync('work/anxiety-test-results.json',JSON.stringify(report,null,2));fs.writeFileSync('work/anxiety-fixtures.json',JSON.stringify(fixtures,null,2));
