const assert=require('node:assert/strict'),fs=require('fs');const boot=require(process.cwd()+'/tests/differential-v2-harness.cjs');let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS UX2 '+name);};
const safe=c=>{c.GlobalSafety.reset();for(const p of c.GlobalSafety.paths)c.GlobalSafety.answer(p,false);};
const setup=()=>{const c=boot();safe(c);c.view='screen';c.Mood.store.step=2;c.render=()=>{};return c;};
for(let i=0;i<9;i++)test('PHQ mapping '+i,()=>{const c=boot(),M=c.Mood;assert.equal(M.phqDomainMap[i],['interest','mood','sleep','energy','appetite','worth','focus','motor','death'][i]);M.update('phq.'+i,'2');const id=M.phqDomainMap[i];assert.equal(M.store.state.symptoms[id].present,'yes');assert.equal(M.store.state.symptoms[id].frequency,'most');assert(M.symptomQuestions(M.store.state,id).some(q=>q.id.endsWith('.duration')));M.update('phq.'+i,'0');assert.equal(M.store.state.symptoms[id].present,'no');assert.equal(M.symptomQuestions(M.store.state,id).length,0);assert.equal(M.store.state.symptoms[id].duration,undefined);});
test('required visible fields permit Step 3 validation with optional onset empty',()=>{const c=boot(),M=c.Mood;for(let i=0;i<9;i++)M.update('phq.'+i,i===8?'0':'1');assert(M.validateSection(M.store.state,2).length>0);for(const [id]of M.symptomDomains)for(const q of M.symptomQuestions(M.store.state,id))if(!q.optional)M.update(q.id,q.options[0][0]);assert.deepEqual([...M.validateSection(M.store.state,2)],[]);for(const [id]of M.symptomDomains)assert.equal(M.store.state.symptoms[id].onset,undefined);const score=M.scorePHQ9(M.store.state.phq);assert.equal(score.total,8);const snapshot=JSON.stringify(M.store.state);for(const lang of [0,1]){c.lang=lang;M.store.step=2;M.render();assert.equal(JSON.stringify(M.store.state),snapshot);assert.equal(M.validateSection(M.store.state,2).length,0);}});
for(const gate of ['substance.screen','medical.screen','mania.period','course.chronic','stress.present'])test('four states and stale cleanup '+gate,()=>{const c=boot(),M=c.Mood;assert.equal(M.get(M.store.state,gate),undefined);for(const value of ['yes','no','unknown','']){M.update(gate,value);assert.equal(M.get(M.store.state,gate),value||undefined);}const row={'substance.screen':['substance.temporal','dose'],'medical.screen':['medical.temporal','yes'],'mania.period':['mania.duration','7plus'],'course.chronic':['course.years','2plus'],'stress.present':['stress.linked','yes']}[gate];M.update(gate,'yes');M.update(...row);M.update(gate,'no');assert.equal(M.get(M.store.state,row[0]),undefined);M.update(gate,'unknown');assert.equal(M.get(M.store.state,gate),'unknown');});
test('medication/exposure categories only display applicable detail',()=>{const c=boot(),M=c.Mood;M.update('substance.screen','yes');M.update('substance.medication','no');M.update('substance.other','yes');const visible=M.sections[7].questions.filter(q=>M.visible(q,M.store.state)).map(q=>q.id);assert(!visible.includes('substance.exposures.dose'));assert(visible.includes('substance.exposures.alcohol'));});
for(const lang of [0,1])test('correction preserves original assessment and Router '+lang,()=>{const c=setup(),G=c.GlobalSafety,M=c.Mood;c.lang=lang;M.update('phq.0','1');const saved=M.store.state.phq[0],router=JSON.stringify(c.SymptomRouter.store);M.update('safety.intent','yes');assert(G.current().requiresInterruption);G.openCorrection();assert(G.current().requiresInterruption);assert(G.panel(G.current()).includes('safety-correction-answer'));assert(G.correct('no'));assert.equal(G.resumeCorrection(),'screen');assert.equal(M.store.step,2);assert.equal(M.store.state.phq[0],saved);assert.equal(JSON.stringify(c.SymptomRouter.store),router);});
test('remaining independent acute evidence prevents correction bypass',()=>{const c=setup(),G=c.GlobalSafety;G.answer('medical.lossOfConsciousness',true);c.Mood.update('safety.intent','yes');G.openCorrection();G.correct('no');assert(G.current().requiresInterruption);assert.equal(G.resumeCorrection(),false);assert(G.panel(G.current()).includes('role="alert"'));});
test('failure and unknown critical evidence prevent resume',()=>{const c=setup(),G=c.GlobalSafety;c.Mood.update('safety.intent','yes');G.correct('no');G.answer('suicide.plan','unknown');assert.equal(G.resumeCorrection(),false);G.store.failed=true;assert.equal(G.resumeCorrection(),false);});
test('stable batch survives ordinary selection and language redraw',()=>{const c=boot(),G=c.GlobalSafety;c.view='safety';let renders=0;c.render=()=>renders++;const r=G.current(),paths=[...G.clarificationPaths(r)];const el={value:'no',dataset:{globalAnswer:paths[0]}};c.document={querySelectorAll:q=>q==='[data-global-answer]'?[el]:[],getElementById:()=>null,querySelector:()=>null};G.bind();el.onchange();assert.equal(renders,0);assert.equal(G.get(G.store.signals,paths[0]),false);for(const lang of [0,1]){c.lang=lang;const html=G.panel(G.current());assert.deepEqual([...G.clarificationPaths(G.current())],paths);assert(html.includes('value="no" selected'));}el.value='yes';el.onchange();assert(G.current().requiresInterruption);assert.equal(renders,1);});

for(const lang of [0,1])test('Step 3 Continue advances to Step 4 '+lang,()=>{const c=setup(),M=c.Mood;c.lang=lang;for(const q of M.questions.filter(q=>q.id.startsWith('safety.')))M.update(q.id,q.options.some(o=>o[0]==='no')?'no':q.options[0][0]);for(let i=0;i<9;i++)M.update('phq.'+i,'0');M.update('phq.0','1');for(const [id]of M.symptomDomains)for(const q of M.symptomQuestions(M.store.state,id))if(!q.optional)M.update(q.id,q.options[0][0]);const next={dataset:{mood:'next'}};c.document={querySelectorAll:q=>q==='[data-mood]'?[next]:[],getElementById:()=>null,querySelector:()=>null};c.window={scrollTo(){}};M.bind();next.onclick();assert.equal(M.store.step,3);assert.equal(M.store.error.length,0);});
test('Safety Continue reevaluates a completed batch',()=>{const c=boot(),G=c.GlobalSafety;c.view='safety';c.render=()=>{};const first=[...G.clarificationPaths(G.current())];for(const p of first)G.answer(p,false);assert.deepEqual([...G.clarificationPaths(G.current())],first);const next={dataset:{global:'continue'}};c.document={querySelectorAll:q=>q==='[data-global]'?[next]:[],getElementById:()=>null,querySelector:()=>null};G.bind();next.onclick();assert.deepEqual([...G.clarificationPaths(G.current())],[...G.current().followup]);assert(!G.clarificationPaths(G.current()).some(p=>first.includes(p)));});
test('new Safety concerns open a fresh batch after an empty completed batch',()=>{const c=setup(),G=c.GlobalSafety;assert.equal(G.clarificationPaths(G.current()).length,0);G.answer('suicide.plan','unknown');assert(G.clarificationPaths(G.current()).includes('suicide.plan'));});
fs.writeFileSync('work/ux2-results.json',JSON.stringify({passed:true,count},null,2));
