const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const c=require(process.cwd()+'/tests/differential-v2-harness.cjs')(),C=c.TopicCapabilities;
const test=(name,fn)=>{fn();console.log('PASS Capability '+name);};
const expected=[['depression','FULL_ASSESSMENT','screen'],['bipolar','ASSESSMENT_PATHWAY','screen'],['gad','FULL_ASSESSMENT','anxiety'],['panic','ASSESSMENT_PATHWAY','anxiety'],['social-anxiety','ASSESSMENT_PATHWAY','anxiety'],['ocd','FULL_ASSESSMENT','ocd'],['body-dysmorphia-hoarding','DIFFERENTIAL_OR_NAVIGATION',null],['ptsd','FULL_ASSESSMENT','trauma'],['adjustment-grief','DIFFERENTIAL_OR_NAVIGATION',null],['psychosis','FULL_ASSESSMENT','psychosis'],['adhd','FULL_ASSESSMENT','adhd'],['autism','KNOWLEDGE_ONLY',null],['eating','FULL_ASSESSMENT','eating'],['somatic','DIFFERENTIAL_OR_NAVIGATION',null],['sleep','DIFFERENTIAL_OR_NAVIGATION',null],['substance','MEDICAL_OR_SAFETY_NAVIGATION',null],['personality','KNOWLEDGE_ONLY',null],['cognitive','MEDICAL_OR_SAFETY_NAVIGATION',null]];
for(const [index,[id,type,route]] of expected.entries())test(id+' classification and route',()=>{const row=C.forTopic(index);assert.equal(row.topicId,id);assert.equal(row.capabilityType,type);assert.equal(C.route(row),route);assert.equal(row.knowledgeAvailable,true);assert.equal(row.fullAssessmentAvailable,type==='FULL_ASSESSMENT');if(route)assert.ok(C.assessments().some(r=>r.assessmentDomain===row.assessmentDomain));else assert.equal(row.adaptiveSupported,false);});
test('exactly 18 unique immutable configurations linked to editorial topics',()=>{assert.equal(C.topics.length,18);assert.equal(new Set(C.topics.map(r=>r.topicId)).size,18);assert.ok(Object.isFrozen(C.topics));for(const r of C.topics){assert.ok(Object.isFrozen(r));assert.equal(c.I18n.t(r.titleKey,1),vm.runInContext('topics['+r.topicIndex+'][2]',c));}});
test('exactly seven unique parent domains',()=>assert.equal(new Set(C.assessments().map(r=>r.assessmentDomain)).size,7));
for(const locale of [0,1])test('all topic UI and routes in locale '+locale,()=>{c.lang=locale;for(const row of C.topics){const html=C.info(row);assert.ok(html.includes(c.esc(c.I18n.t(C.badgeKeys[row.capabilityType],locale))));assert.ok(!html.includes('capability.'));assert.equal(/class="secondary capability-cta"/.test(html),!!C.route(row));assert.equal(/[\u3400-\u9fff]/.test(html),!locale);if(row.capabilityType==='MEDICAL_OR_SAFETY_NAVIGATION')assert.ok(html.includes('data-view="urgent"'));}assert.equal((C.overview().match(/data-view=/g)||[]).length,7);});
test('language presentation preserves metadata and clinical state',()=>{const before=JSON.stringify([C.topics,c.GlobalSafety.store,c.SymptomRouter.store,c.Adaptive.store]);for(const locale of [0,1,0]){c.lang=locale;C.topics.forEach(C.info);C.overview();}assert.equal(JSON.stringify([C.topics,c.GlobalSafety.store,c.SymptomRouter.store,c.Adaptive.store]),before);});
test('Bipolar boundary and Psychosis product name',()=>{c.lang=1;assert.match(C.info(C.forTopic(1)),/standalone comprehensive Bipolar assessment is not available/);assert.match(C.info(C.forTopic(9)),/Psychosis \/ Severe Mental Health Assessment/);assert.doesNotMatch(C.info(C.forTopic(1)),/Take Bipolar Test/);});
test('registry is not imported into clinical engines',()=>{for(const dir of ['safety','router-v2','differential-v2','adaptive'])for(const file of fs.readdirSync('src/'+dir).filter(f=>f.endsWith('.js')))assert.doesNotMatch(fs.readFileSync('src/'+dir+'/'+file,'utf8'),/TopicCapabilities/);});
// Load the actual application with a minimal DOM, without changing existing tests.
let markup='';const nodes={app:{set innerHTML(v){markup=v;}},lang:{},detail:{open:false,innerHTML:'',showModal(){this.open=true;},close(){this.open=false;}}};
c.document={documentElement:{},querySelector:s=>nodes[s.slice(1)]||null,querySelectorAll:()=>[],getElementById:id=>nodes[id]||null};c.window={scrollTo(){}};vm.runInContext(fs.readFileSync('src/app.js','utf8'),c);
test('library has 18 semantic cards, ten supported CTAs and four nav entries',()=>{assert.equal((markup.match(/class="card topic-card"/g)||[]).length,18);assert.equal((markup.match(/class="secondary capability-cta"/g)||[]).length,10);assert.equal((markup.match(/<nav>(.*?)<\/nav>/s)[1].match(/<button/g)||[]).length,4);let depth=0;for(const tag of markup.matchAll(/<\/?button\b[^>]*>/g)){depth+=tag[0].startsWith('</')?-1:1;assert.ok(depth===0||depth===1,'buttons cannot nest');}assert.equal(depth,0);});
test('search filtering retains registry CTA and topic identity',()=>{const html=vm.runInContext("query='Autism';listing()",c);assert.ok(html.includes('data-capability-topic="autism"'));assert.ok(!html.includes('capability-cta'));});
test('assessment navigation renders seven domains and Safety-first text entry',()=>{vm.runInContext("navigate('assessments')",c);assert.equal((markup.match(/class="capability-domains"/g)||[]).length,1);assert.ok(markup.includes('id="global-entry-form"'));assert.ok(markup.includes('data-capability-describe'));});
test('acute medical state interrupts assessment directory',()=>{c.GlobalSafety.store.signals.medical.lossOfConsciousness=true;vm.runInContext("navigate('assessments')",c);assert.ok(!markup.includes('capability-domains'));assert.ok(!markup.includes('capability-cta'));assert.match(markup,/<nav><\/nav>/);});
