const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),c=require(process.cwd()+'/tests/differential-v2-harness.cjs')(),{DifferentialV2:V,Differential:D,GlobalSafety:G}=c;
for(const name of ['differential','trauma','adhd','eating','psychosis'])vm.runInContext(fs.readFileSync('tests/'+name+'-fixtures.js','utf8'),c);
const clone=x=>JSON.parse(JSON.stringify(x)),modules=D.modules(),states={mood:()=>c.DifferentialFixtures.mood(),anxiety:()=>c.DifferentialFixtures.gad(),ocd:()=>c.DifferentialFixtures.ocd(),trauma:()=>c.TraumaFixtures.classic(),adhd:()=>c.ADHDTestFixtures.classic(),eating:()=>c.EatingFixtures.state('restrictive'),psychosis:()=>c.PsychosisFixtures.state()};
let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS Differential v2 integration '+name);};
function load(domains){G.reset();c.SymptomRouter.clear();D.clear();D.store.selected=Object.fromEntries([...V.domainIds,'router'].map(k=>[k,true]));for(const p of G.paths)G.answer(p,false);for(const domain of domains){const m=modules[domain];m.store.state=states[domain]();m.store.result=m.assess(m.store.state,c.Mood.store.state,c.Anxiety.store.state);}D.store.enabled=true;G.acknowledge();return V.current();}
for(const domain of V.domainIds){
 test(domain+' stable adapter and provenance',()=>{const r=load([domain]);assert(r.availability[domain]);assert(r.evidenceGraph.valid);assert(r.evidenceGraph.nodes.some(n=>n.source===domain));assert(r.candidateDirections.some(d=>d.domain===domain&&d.level>=2));});
 test(domain+' English Chinese render and state preservation',()=>{load([domain]);const r=V.current(),before=JSON.stringify([V.store,D.store,G.store,...Object.values(modules).map(m=>m.store)]);c.lang=0;const zh=V.render();c.lang=1;const en=V.render();assert(zh.includes('还有哪些信息尚不明确'));assert(en.includes('What is still uncertain?'));assert(!/[\u3400-\u9fff]/.test(en));assert.equal(V.current(),r);assert.equal(JSON.stringify([V.store,D.store,G.store,...Object.values(modules).map(m=>m.store)]),before);});
 test(domain+' stale assessment excluded',()=>{load([domain]);modules[domain].store.result.revision--;const a=V.adaptAssessment(domain,modules[domain].store,modules[domain]);assert(!a.ready);assert.equal(a.evidence.length,0);});
}
for(const pair of [['mood','anxiety'],['mood','ocd'],['trauma','ocd'],['trauma','anxiety'],['trauma','mood'],['adhd','mood'],['adhd','anxiety'],['adhd','trauma'],['eating','mood'],['eating','ocd'],['psychosis','ocd'],['psychosis','trauma'],['psychosis','mood']])test('real assessment combination '+pair.join(' + '),()=>{const r=load(pair);assert(!r.blocked);for(const domain of pair)assert(r.candidateDirections.some(d=>d.domain===domain&&d.level>0));});
test('three independent domains survive shared adaptation',()=>{const r=load(['mood','trauma','adhd']);for(const domain of ['mood','trauma','adhd'])assert(r.candidateDirections.some(d=>d.domain===domain&&d.level>=2));});
test('typed functional and course observations retained',()=>{const r=load(['adhd']);assert(r.evidenceGraph.nodes.some(n=>n.concept==='adhd.observation.function.work'&&n.value==='moderate'));assert(r.evidenceGraph.nodes.some(n=>n.concept==='adhd.observation.course.pattern'&&n.value==='longstanding'));});
test('historical assessment exposure remains historical',()=>{const r=load(['trauma']);assert.equal(r.evidenceGraph.nodes.find(n=>n.concept==='trauma.exposure').temporality,'history');assert.equal(r.evidenceGraph.facts['trauma.exposure'],true);});
test('Router labels and recommendations never become evidence',()=>{load([]);const p=c.RouterV2.extract('I feel depressed and have lost interest.');c.SymptomRouter.store.v2={profile:p};const before=clone(V.collect().evidence);c.SymptomRouter.store.result={primaryRoute:'psychosis',candidateRoutes:[{domain:'psychosis',rank:99}]};assert.deepEqual(clone(V.collect().evidence),before);});
test('Router v2 clarification preserves original evidence contexts',()=>{const p=c.RouterV2.extract('I feel depressed and have lost interest. I keep having unwanted thoughts and repeatedly check the door.'),a=c.RouterV2.answer(p,c.RouterV2.session(),'moodOcd','both'),r=V.adaptRouter(a.profile);assert(!r.invalid);assert(r.evidence.some(n=>n.concept==='mood.rumination'&&n.sourceType==='user_clarification'));assert(r.evidence.some(n=>n.concept==='ocd.response'&&n.sourceType==='user_clarification'));});
test('malformed Router profile cannot be silently treated as no evidence',()=>{assert(V.adaptRouter({facts:{}}).invalid);});
test('Safety suppresses ordinary comparison UI',()=>{load(['mood']);G.answer('suicide.intent',true);const r=V.current();assert(r.blocked);assert(!V.render().includes('dv2-uncertain'));assert(!V.render().includes('data-diff-clear'));});
test('medical Safety suppresses comparison UI',()=>{load(['psychosis']);G.answer('medical.lossOfConsciousness',true);assert(V.current().blocked);assert(!V.render().includes('differential-v2'));});
test('adaptive handoff cannot mutate the live result',()=>{const r=load(['mood']),before=JSON.stringify(r),contract=V.adaptiveContract(r);contract.candidateDirections.length=0;contract.missingEvidence.push('synthetic');assert.equal(JSON.stringify(r),before);});
test('no adaptive answer controls or raw translation keys',()=>{load(['eating']);const html=V.render();assert(!html.includes('data-diff-answer'));assert(!/>(?:dv2|differential|eatingUI)\./.test(html));assert(html.includes('<summary>'));assert(html.includes('aria-labelledby='));});
console.log('Differential v2 integration: '+count+' tests passed.');
