// Completion audit: synthetic inputs only. No clinical validation claim.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),create=require(process.cwd()+'/tests/differential-v2-harness.cjs');
const test=(name,fn)=>{fn();console.log('PASS Entry audit '+name);};
function start(raw='bad'){const c=create();c.EntryFlow.submit(raw);for(const p of c.GlobalSafety.current().followup)c.GlobalSafety.answer(p,false);c.GlobalSafety.acknowledge();c.SymptomRouter.resume();return c;}
test('explicit insufficient-to-description prohibition survives repeated reevaluation',()=>{const c=start();for(let i=0;i<20;i++){assert.equal(c.SymptomRouter.store.result.routingStatus,'insufficient');assert.equal(c.SymptomRouter.resume(),'router');assert.notEqual(c.EntryFlow.store.state,'ENTRY_DESCRIPTION');}});
test('nonacute Q2 return preserves Q1 original evidence and budget exactly',()=>{const c=start('I have no energy.'),e=c.EntryFlow,g=c.GlobalSafety,r=c.SymptomRouter;assert.equal(r.store.v2.profile.facts['mood.lowEnergy'],true);e.respond('entryBroad','anxiety');const before=JSON.stringify([e.store.answers,e.store.used,r.store.v2,e.store.question]);g.answer('suicide.currentIdeation',true);e.reconcile();assert.equal(e.store.state,'SAFETY_CLARIFICATION');g.answer('suicide.currentIdeation',false);g.acknowledge();r.resume();assert.equal(e.store.state,'ENTRY_BROAD_CLARIFICATION');assert.equal(e.store.question.id,'entryAnxiety');assert.equal(JSON.stringify([e.store.answers,e.store.used,r.store.v2,e.store.question]),before);});
test('known symptom option is not asked again under entry wording',()=>{const c=start('I feel depressed.'),e=c.EntryFlow;assert.equal(e.store.question.id,'entryMood');assert(!e.store.question.options.some(o=>o.value==='low'));e.respond('entryMood','interest');assert.equal(c.SymptomRouter.store.result.primaryRoute,'mood');assert.equal(c.SymptomRouter.store.v2.profile.evidence.filter(x=>x.path==='mood.depressedMood').length,1);});
test('concept-complete alternate wording yields no question',()=>{const c=start('I feel depressed and have lost interest.'),q=c.EntryFlow.questions.mood,p=c.SymptomRouter.store.v2.profile;assert.equal(c.EntryFlow.entryQuestion({...q,id:'differentWording'},p),null);});
test('concept contradictions cannot be silently overwritten by a partial option',()=>{const c=start('I am not depressed.'),q=c.EntryFlow.entryQuestion(c.EntryFlow.questions.mood,c.SymptomRouter.store.v2.profile);assert.equal(c.SymptomRouter.store.v2.profile.facts['mood.depressedMood'],false);assert(!q.options.some(o=>o.value==='both'||o.value==='low'));});
test('Router discriminator precedence and ordering are identical',()=>{const c=start('I feel depressed and have lost interest. I have unwanted thoughts and repeatedly check the door.'),expected=c.RouterV2.evaluate(c.SymptomRouter.store.v2.profile,c.SymptomRouter.store.v2.session,c.GlobalSafety.current());assert.equal(c.EntryFlow.store.question.id,expected.clarification.id);assert.equal(expected.clarification.id,'moodOcd');assert.equal(JSON.stringify(c.SymptomRouter.store.result.candidateRoutes),JSON.stringify(expected.candidateRoutes));});
test('stale answer after user exit cannot mutate evidence or budget',()=>{const c=start(),e=c.EntryFlow;e.action('direct');const before=JSON.stringify([e.store,c.SymptomRouter.store]);assert.equal(e.respond('entryBroad','mood'),false);assert.equal(JSON.stringify([e.store,c.SymptomRouter.store]),before);});
test('repeating a resolved identical Safety answer preserves acknowledgment',()=>{const c=start(),e=c.EntryFlow,g=c.GlobalSafety;const ack=g.store.ack,v=e.store.evidenceVersion;g.answer('suicide.intent',false);assert.equal(g.store.ack,ack);assert.equal(e.store.evidenceVersion,v);assert.equal(e.checkSafety().show,false);g.answer('suicide.intent',true);assert.equal(e.checkSafety().result.urgency,'acute');});
for(const domain of ['mood','anxiety','ocd','trauma','adhd','eating','psychosis'])test('manual '+domain+' choice is navigation only',()=>{const c=start(),before=JSON.stringify(c.SymptomRouter.store);const row=c.TopicCapabilities.assessments().find(r=>r.assessmentDomain===domain);assert.equal(c.EntryFlow.start(domain),row.assessmentRoute);assert.equal(JSON.stringify(c.SymptomRouter.store),before);assert.equal(c.SymptomRouter.store.preference,null);});
test('unavailable manual routes rejected',()=>{const c=start();for(const domain of ['autism','sleep','unknown','screen?answer=yes'])assert.equal(c.EntryFlow.start(domain),'router');});
test('direct module answers still trigger authoritative live Safety',()=>{const c=start();assert.equal(c.EntryFlow.start('mood'),'screen');c.Mood.update('safety.plan','yes');assert.equal(c.EntryFlow.checkSafety().result.urgency,'acute');assert.equal(c.EntryFlow.start('anxiety'),'safety');});
test('Adaptive answers consult live Safety and block after new acute evidence',()=>{const c=start(),g=c.GlobalSafety,a=c.Adaptive;for(const p of g.paths)g.answer(p,false);g.acknowledge();vm.runInContext(fs.readFileSync('tests/differential-fixtures.js','utf8'),c);c.Mood.store.state=c.DifferentialFixtures.mood();c.Mood.store.result=c.Mood.assess(c.Mood.store.state);a.start();assert(a.submit('childhood_onset','no'));a.safetyText('I intend to kill myself tonight.');assert.equal(a.gate().result.urgency,'acute');assert.equal(a.submit('childhood_onset','yes'),false);assert.equal(c.EntryFlow.checkSafety().result.urgency,'acute');});
for(const raw of ['我打算杀死别人。','我现在打算杀他人。'])test('current Chinese violent-intent coverage '+raw.length,()=>{const c=start();assert.equal(c.EntryFlow.addText(raw),'safety');assert.equal(c.GlobalSafety.current().urgency,'acute');assert.equal(c.GlobalSafety.get(c.GlobalSafety.current().signals,'harmToOthers.intent'),true);});
for(const raw of ['我不打算杀死别人。','我以前打算杀死别人，但现在没有这个意图。','他打算杀死别人。','如果我打算杀死别人怎么办？','我害怕出现杀死别人的念头，但不想这样做。','他说：“我打算杀死别人。”'])test('context excludes asserted current self intent '+raw.length,()=>{const c=create(),s=c.GlobalSafety.extract(raw).signals;assert.notEqual(c.GlobalSafety.get(s,'harmToOthers.intent'),true);});
for(const raw of ['I wish I were dead.','I wish I was dead.'])test('passive death wish triggers clarification without invented intent '+raw.length,()=>{const c=start();assert.equal(c.EntryFlow.addText(raw),'safety');const result=c.GlobalSafety.current();assert.equal(result.urgency,'attention');assert.equal(c.GlobalSafety.get(result.signals,'suicide.passiveDeathWish'),true);assert.equal(c.GlobalSafety.get(result.signals,'suicide.intent'),false);});
for(const raw of ['I do not wish I were dead.','I wished I was dead years ago.','My brother says he wishes he were dead.','What if I wish I were dead?','He said: "I wish I were dead."'])test('passive wish coverage respects context '+raw.length,()=>{const c=create();assert.notEqual(c.GlobalSafety.get(c.GlobalSafety.extract(raw).signals,'suicide.passiveDeathWish'),true);});
test('every nonacute presentation has an actionable exit',()=>{for(const state of ['ENTRY_DESCRIPTION','ENTRY_BROAD_CLARIFICATION','ROUTER_CLARIFICATION','ROUTE_RECOMMENDATION','DIRECT_ASSESSMENT_SELECTION','UNSUPPORTED_NAVIGATION','STOPPED']){const c=start();c.EntryFlow.store.state=state;const html=c.SymptomRouter.render();assert(/data-entry-action=/.test(html),state);}});
const result=require(process.cwd()+'/scripts/entry-scenarios.cjs').run();
for(const row of result.results)test('scenario '+row.id,()=>assert.equal(row.passed,true));
test('synthetic metrics have zero restarts dead ends duplicates and repeated Safety UI',()=>{for(const key of ['involuntaryRestartCount','deadEndCount','duplicateQuestionCount','unnecessaryRepeatedSafetyUICount'])assert.equal(result.metrics[key],0);assert.equal(result.metrics.bilingualParity.passed,result.metrics.bilingualParity.total);});
