// Synthetic examples only; no user narratives or clinical validation claims.
const assert=require('node:assert/strict'),create=require(process.cwd()+'/tests/differential-v2-harness.cjs');
const copy=x=>JSON.parse(JSON.stringify(x));
function test(name,fn){fn();console.log('PASS Entry '+name);}
function start(raw='bad'){const c=create();c.EntryFlow.submit(raw);c.GlobalSafety.acknowledge();c.SymptomRouter.resume();return c;}
const choices={mood:'both',anxiety:'worry',ocd:'checking',trauma:'reliving',adhd:'longstanding',eating:'restriction',psychosis:'awake'};
test('short vague entry reaches broad clarification without restart',()=>{const c=start();assert.equal(c.EntryFlow.store.state,'ENTRY_BROAD_CLARIFICATION');assert.equal(c.EntryFlow.store.question.id,'entryBroad');assert.equal(c.SymptomRouter.store.result.routingStatus,'insufficient');});
for(const [domain,value]of Object.entries(choices))test(domain+' explicit second-level evidence creates useful Router route',()=>{const c=start(),e=c.EntryFlow,r=c.SymptomRouter;e.respond('entryBroad',domain);assert.equal(r.store.v2.profile.evidence.length,0);e.respond(e.store.question.id,value);if(domain==='psychosis'){assert.equal(c.GlobalSafety.current().urgency,'elevated');c.GlobalSafety.acknowledge();r.resume();}assert.equal(r.store.result.primaryRoute,domain);assert.equal(e.store.used,2);assert.ok(['ROUTE_RECOMMENDATION','ROUTER_CLARIFICATION'].includes(e.store.state));});
for(const answer of ['unknown','prefer','other'])test(answer+' does not fabricate evidence or force route',()=>{const c=start(),e=c.EntryFlow,p=JSON.stringify(c.SymptomRouter.store.v2.profile);assert(e.respond('entryBroad',answer));assert.equal(JSON.stringify(c.SymptomRouter.store.v2.profile),p);assert.equal(c.SymptomRouter.store.result.primaryRoute,null);assert.equal(e.store.state,answer==='other'?'UNSUPPORTED_NAVIGATION':'DIRECT_ASSESSMENT_SELECTION');});
test('three-question budget spans broad and mature Router questions',()=>{const c=start(),e=c.EntryFlow;e.respond('entryBroad','mood');e.addText('I feel depressed and have lost interest. I have unwanted thoughts and repeatedly check the door. I worry constantly about work and family and feel physically tense.');assert.equal(e.store.question.id,'moodAnxiety');e.respond('moodAnxiety','both');assert.equal(e.store.question.id,'moodOcd');const q=e.store.question;e.respond(q.id,q.options[0].value);assert.equal(e.store.used,3);assert.equal(e.store.question,null);assert.notEqual(e.store.state,'ENTRY_DESCRIPTION');assert.equal(e.respond(q.id,q.options[0].value),false);});
test('back cannot reset monotonic budget into endless loop',()=>{const c=start(),e=c.EntryFlow;for(let i=0;i<3;i++){assert(e.respond('entryBroad','anxiety'));if(i<2)assert(e.back());}assert.equal(e.store.used,3);assert.equal(e.store.state,'DIRECT_ASSESSMENT_SELECTION');assert.equal(e.back(),false);});
test('repeated insufficient continuations remain terminal',()=>{const c=start(),e=c.EntryFlow;e.respond('entryBroad','unknown');for(let i=0;i<20;i++){c.SymptomRouter.resume();assert.equal(e.store.state,'DIRECT_ASSESSMENT_SELECTION');}});
test('back restores prior evidence question and family',()=>{const c=start(),e=c.EntryFlow;const p=JSON.stringify(c.SymptomRouter.store.v2);e.respond('entryBroad','ocd');e.back();assert.equal(e.store.question.id,'entryBroad');assert.equal(e.store.family,null);assert.equal(JSON.stringify(c.SymptomRouter.store.v2),p);assert.equal(e.store.used,1);});
for(const [action,state,destination]of [['direct','DIRECT_ASSESSMENT_SELECTION','router'],['knowledge','STOPPED','library'],['stop','STOPPED','router'],['edit','ENTRY_DESCRIPTION','router']])test(action+' escape preserves evidence',()=>{const c=start(),p=JSON.stringify(c.SymptomRouter.store.v2);assert.equal(c.EntryFlow.action(action),destination);assert.equal(c.EntryFlow.store.state,state);assert.equal(JSON.stringify(c.SymptomRouter.store.v2),p);});
test('direct choices use the single capability registry',()=>{const c=start(),html=c.EntryFlow.choices();assert.equal((html.match(/data-entry-start=/g)||[]).length,7);for(const row of c.TopicCapabilities.assessments())assert(html.includes('data-entry-start="'+row.assessmentDomain+'"'));});
test('intentional edit invalidates old symptoms and reevaluates',()=>{const c=start('I feel depressed and have lost interest.'),e=c.EntryFlow;e.action('edit');e.submit('I repeatedly check the door.');assert.equal(c.SymptomRouter.store.v2.profile.facts['mood.depressedMood'],'unknown');assert.equal(c.SymptomRouter.store.v2.profile.facts['ocd.checking'],true);assert.equal(e.store.editing,false);});
test('non-Safety clarification preserves explicit Safety answers and acknowledgment',()=>{const c=start(),g=c.GlobalSafety,e=c.EntryFlow;g.answer('suicide.intent',false);g.acknowledge();c.SymptomRouter.resume();const before=JSON.stringify(g.store);e.respond('entryBroad','anxiety');e.respond('entryAnxiety','worry');assert.equal(JSON.stringify(g.store),before);assert.equal(e.checkSafety().show,false);assert.equal(g.get(g.current().signals,'suicide.intent'),false);});
test('safe additional text preserves resolved Safety answers',()=>{const c=start(),g=c.GlobalSafety;g.answer('suicide.intent',false);g.acknowledge();c.SymptomRouter.resume();c.EntryFlow.addText('I worry about work.');assert.equal(g.get(g.current().signals,'suicide.intent'),false);assert.equal(c.EntryFlow.checkSafety().show,false);});
for(const [name,raw]of [['suicide','I intend to kill myself tonight and have a plan.'],['violence','I intend to kill someone tonight and have a plan.'],['medical','I have severe chest pain and cannot breathe.']])test(name+' new evidence immediately suspends routing',()=>{const c=start();assert.equal(c.EntryFlow.addText(raw),'safety');assert.equal(c.GlobalSafety.current().urgency,'acute');assert.equal(c.EntryFlow.respond('entryBroad','mood'),false);assert.equal(c.EntryFlow.action('direct'),'safety');assert(!c.SymptomRouter.render().includes('data-entry-start'));});
test('nonacute Safety return restores previous entry question',()=>{const c=start(),e=c.EntryFlow,g=c.GlobalSafety;e.respond('entryBroad','anxiety');const id=e.store.question.id;g.answer('suicide.intent','unknown');e.reconcile();assert.equal(e.store.state,'SAFETY_CLARIFICATION');g.answer('suicide.intent',false);g.acknowledge();c.SymptomRouter.resume();assert.equal(e.store.question.id,id);assert.equal(e.store.used,1);});
test('acute initial entry never runs Router extraction',()=>{const c=create();let called=false;c.RouterV2.extract=()=>{called=true;throw Error('should not run');};assert.equal(c.EntryFlow.submit('I intend to kill myself tonight and have a plan.'),'safety');assert.equal(called,false);assert.equal(c.SymptomRouter.store.profile,null);});
test('existing mood evidence retained when attention evidence added',()=>{const c=start('I feel depressed and cannot focus.'),e=c.EntryFlow;c.EntryFlow.addText('I have been disorganized since childhood.');const f=c.SymptomRouter.store.v2.profile.facts;assert.equal(f['mood.depressedMood'],true);assert.equal(f['adhd.disorganized'],true);assert.notEqual(e.store.state,'ENTRY_DESCRIPTION');});
test('known Mood pattern skips broad duplicate',()=>{const c=start('I feel depressed and have lost interest.');assert.equal(c.EntryFlow.store.state,'ROUTE_RECOMMENDATION');assert.equal(c.EntryFlow.store.used,0);});
test('mixed Mood OCD retains both without forced winner',()=>{const c=start('I feel depressed and have lost interest. I have unwanted thoughts and repeatedly check the door.'),e=c.EntryFlow;assert.equal(e.store.question.id,'moodOcd');e.respond('moodOcd','both');assert.equal(c.SymptomRouter.store.result.primaryRoute,null);assert.deepEqual(copy(c.SymptomRouter.store.result.candidateRoutes.map(r=>r.domain)),['mood','ocd']);});
test('mixed-language evidence preserved',()=>{const c=start('最近状态很差 and I keep checking the door.');assert.equal(c.SymptomRouter.store.v2.profile.facts['ocd.checking'],true);assert.notEqual(c.EntryFlow.store.state,'ENTRY_DESCRIPTION');});
for(const raw of ['I think I may have autism.','I am grieving a loss.','I have sleep apnea.'])test('unsupported navigation remains unsupported '+raw.length,()=>{const c=start(raw);assert.equal(c.SymptomRouter.store.result.primaryRoute,null);assert.equal(c.EntryFlow.store.state,'UNSUPPORTED_NAVIGATION');});
for(const phase of ['broad','domain','recommendation','terminal','safety'])test('presentation-only switching preserves all state '+phase,()=>{const c=start(),e=c.EntryFlow;if(phase==='domain'||phase==='recommendation'){e.respond('entryBroad','anxiety');if(phase==='recommendation')e.respond('entryAnxiety','worry');}if(phase==='terminal')e.respond('entryBroad','unknown');if(phase==='safety')e.addText('I intend to kill myself tonight and have a plan.');const before=JSON.stringify([e.store,c.SymptomRouter.store,c.GlobalSafety.store]);for(const locale of [0,1,0]){c.lang=locale;const html=c.SymptomRouter.render();assert(html.includes(locale===0?'安全':'safety')||html.includes(c.I18n.t('entry.heading',locale)));}assert.equal(JSON.stringify([e.store,c.SymptomRouter.store,c.GlobalSafety.store]),before);});
for(const [domain,value]of Object.entries(choices))test('bilingual structured route parity '+domain,()=>{const a=start('bad'),b=start('不好');for(const [c,locale]of [[a,1],[b,0]]){c.lang=locale;c.EntryFlow.respond('entryBroad',domain);c.EntryFlow.respond(c.EntryFlow.store.question.id,value);}assert.deepEqual(copy(a.SymptomRouter.store.v2),copy(b.SymptomRouter.store.v2));assert.deepEqual(copy(a.SymptomRouter.store.result),copy(b.SymptomRouter.store.result));});
test('clear session removes all entry and routing evidence',()=>{const c=start();c.EntryFlow.respond('entryBroad','anxiety');assert(c.PrivacyGovernance.deleteData({scope:'current_session',purpose:'user_requested_deletion',subject:'current_browser_session',storageTarget:'memory'}).deleted);assert.equal(c.EntryFlow.store.active,false);assert.equal(c.EntryFlow.store.answers.length,0);assert.equal(c.EntryFlow.store.safetyEvaluation,null);assert.equal(c.SymptomRouter.store.profile,null);});
test('new entry rules require review and have bounded budget',()=>{const c=create();for(const q of Object.values(c.EntryFlow.questions)){assert.equal(q.reviewStatus,'unreviewed');assert.equal(q.version,'assessment-entry-flow-v1.0.0');}assert.equal(c.EntryFlow.maxQuestions,3);});
test('explicit waking experience is not asked again as a sleep-only question',()=>{const c=start(),e=c.EntryFlow;e.respond('entryBroad','psychosis');e.respond('entryPsychosis','awake');assert.equal(c.GlobalSafety.current().urgency,'elevated');c.GlobalSafety.acknowledge();c.SymptomRouter.resume();assert.equal(e.store.state,'ROUTE_RECOMMENDATION');assert.equal(e.store.used,2);assert.equal(c.SymptomRouter.store.v2.profile.facts['psychosis.sleep'],false);});
test('adding information after uncertainty can produce a recommendation without restarting',()=>{const c=start();c.EntryFlow.respond('entryBroad','unknown');c.EntryFlow.addText('I repeatedly check the door.');assert.equal(c.EntryFlow.store.state,'ROUTE_RECOMMENDATION');assert.equal(c.EntryFlow.store.used,1);assert.equal(c.SymptomRouter.store.result.primaryRoute,'ocd');});
test('historical and third-party extraction provenance survives broad answers',()=>{const c=start('My brother had panic attacks three years ago.'),p=copy(c.SymptomRouter.store.v2.profile);c.EntryFlow.respond('entryBroad','mood');assert.deepEqual(copy(c.SymptomRouter.store.v2.profile),p);assert.equal(c.SymptomRouter.store.result.primaryRoute,null);});
test('edit preserves explicit safety denial but new intent overrides it',()=>{const c=start(),g=c.GlobalSafety;g.answer('suicide.intent',false);g.acknowledge();c.SymptomRouter.resume();c.EntryFlow.submit('I intend to kill myself tonight.');assert.equal(g.current().urgency,'acute');assert.equal(g.get(g.current().signals,'suicide.intent'),true);});
