const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const ctx={console};vm.createContext(ctx);for(const f of ['runtime','catalog'])vm.runInContext(fs.readFileSync('dist/i18n/'+f+'.js','utf8'),ctx);for(const p of ['schema','rules','engine','adapters','extraction','resources','runtime','ui'])vm.runInContext(fs.readFileSync('dist/safety/'+p+'.js','utf8'),ctx);for(const f of ['core','safety','fields'])vm.runInContext(fs.readFileSync('dist/shared/'+f+'.js','utf8'),ctx);for(const file of ['data','scoring','safety','state','engine'])vm.runInContext(fs.readFileSync('dist/mood/'+file+'.js','utf8'),ctx);const M=ctx.Mood;const clone=s=>JSON.parse(JSON.stringify(s));const set=(s,p,v)=>M.setAnswer(s,p,v);function fill(s){for(const q of M.questions){if(q.optional||!M.visible(q,s)||M.get(s,q.id)!==undefined)continue;const v=q.options.find(o=>o[0]==='no')?.[0]??q.options.find(o=>o[0]==='0')?.[0]??q.options.find(o=>o[0]==='none')?.[0]??q.options[0][0];s=set(s,q.id,v);}return s;}
function base(){let s=M.emptyState();s=fill(s);for(const [p,v] of Object.entries({'intro.age':'yes','intro.agree':'yes','intro.immediate':'no','course.duration':'14to29','course.together':'yes','course.pattern':'continuous','course.trend':'stable','function.work':'2'}))s=set(s,p,v);for(const id of ['mood','interest','sleep','energy','worth','focus']){s=set(s,`symptoms.${id}.present`,'yes');for(const [k,v]of Object.entries({frequency:'daily',duration:'14to29',changed:'yes',severity:'2'}))s=set(s,`symptoms.${id}.${k}`,v);}for(let i=0;i<8;i++)s=set(s,'phq.'+i,'2');return fill(s);}
function mania(s,severe=false){s=set(s,'mania.period','yes');s=fill(s);for(const [k,v]of Object.entries({'features.elevated':'yes','features.energy':'yes','features.activity':'yes','features.sleep':'yes','features.speech':'yes','features.racing':'yes',together:'yes',duration:severe?'7plus':'4to6',noticed:'yes',impact:severe?'3':'1',hospital:'no',psychosis:'no',current:'no',related:'no',pastMania:'no'}))s=set(s,'mania.'+k,v);return s;}
const results=[];function test(name,fn){fn();results.push(name);console.log('PASS '+name)}
test('A: MDD structure can lead after competing explanations assessed',()=>{const r=M.assess(base());assert.equal(r.missing.length,0);assert.equal(r.leading,'mdd');assert.equal(r.directions[0].level,3)});
test('B: hypomania changes priority to bipolar II direction',()=>{const r=M.assess(mania(base()));assert.equal(r.leading,'bipolar2');assert.equal(r.mania.hypoPattern,true);assert.notEqual(r.directions[0].level,3)});
test('C: medication timing makes a causal rule-out prominent, not confirmed',()=>{const r=M.assess(set(base(),'substance.temporal','dose'));assert.equal(r.leading,'substance');assert.equal(r.directions.find(d=>d.id==='substance').level,2)});
test('D: medical condition remains unresolved',()=>{const r=M.assess(set(base(),'medical.conditions.thyroid','yes'));assert.equal(r.leading,'medical');assert(r.ruleouts.some(x=>x.key==='medical'))});
test('E: stressor differential coexists; does not override full episode',()=>{let s=set(base(),'stress.present','yes');s=fill(s);s=set(s,'stress.onset','within3');s=set(s,'stress.linked','yes');s=set(s,'stress.impact','2');let r=M.assess(s);assert.equal(r.leading,'mdd');assert.equal(r.directions.find(d=>d.id==='adjustment').level,2);for(const id of ['sleep','energy','worth','focus'])s=set(s,`symptoms.${id}.present`,'no');r=M.assess(s);assert.equal(r.leading,'adjustment')});
test('F: PDD needs persistence, associated symptoms and impairment',()=>{let s=set(base(),'course.chronic','yes');s=fill(s);s=set(s,'course.years','2plus');s=set(s,'course.remission','under2');s=set(s,'course.associated.sleep','yes');s=set(s,'course.associated.energy','yes');assert.equal(M.assess(s).leading,'pdd');s=set(s,'course.remission','over2');assert.notEqual(M.assess(s).leading,'pdd')});
test('G: acute safety overrides diagnostic priority',()=>{let s=set(base(),'safety.intent','yes');let r=M.assess(s);assert.equal(r.safety.action,'immediate');assert.equal(r.leading,null);s=set(base(),'safety.current','yes');assert.equal(M.assess(s).safety.action,'immediate')});
test('H: low PHQ does not erase independent depressive episode',()=>{let s=base();for(let i=0;i<9;i++)s=set(s,'phq.'+i,'0');const r=M.assess(s);assert.equal(r.phq.total,0);assert.equal(r.leading,'mdd');assert.equal(r.screeningDiscrepancy,true);assert.equal(r.directions[0].level,2)});
test('I: high PHQ with missing history does not produce MDD',()=>{let s=M.emptyState();for(let i=0;i<9;i++)s=set(s,'phq.'+i,'3');const r=M.assess(s);assert.equal(r.phq.total,27);assert.equal(r.leading,null);assert.equal(r.directions[0].level,0)});
test('J: editing mania history invalidates and changes derived result',()=>{let s=base(),r=M.assess(s);assert.equal(r.leading,'mdd');s=mania(s);assert.equal(M.assess(s).leading,'bipolar2');s=set(s,'mania.period','no');assert.equal(s.mania.features,undefined);assert.equal(M.assess(s).leading,'mdd')});
test('PHQ boundaries, item separation and incomplete/invalid values',()=>{for(const n of [0,4,5,9,10,14,15,19,20,27]){let left=n,p={};for(let i=0;i<9;i++){p[i]=String(Math.min(3,left));left-=Number(p[i]);}const r=M.scorePHQ9(p);assert.equal(r.total,n);assert.equal(r.band,n<5?0:n<10?1:n<15?2:n<20?3:4);}assert.equal(M.scorePHQ9({0:'3'}).total,null);assert.equal(M.scorePHQ9({0:7}).total,null);assert.throws(()=>set(base(),'phq.0','9'))});
test('Item 9 is actionable regardless of total; unknown is not safety',()=>{let s=set(base(),'phq.8','1');assert.equal(M.safety(s).action,'prompt');s=set(s,'safety.current','unknown');assert(M.safety(s).unknown.includes('current'));s=set(s,'safety.means','yes');assert.equal(M.safety(s).action,'immediate')});
test('Severe mania, isolated insomnia and grouped risk behaviours',()=>{const r=M.assess(mania(base(),true));assert.equal(r.leading,'bipolar1');let s=set(base(),'mania.period','yes');s=fill(s);s=set(s,'mania.features.sleep','yes');s=set(s,'mania.duration','under4');assert.equal(M.assess(s).mania.bipolarConcern,false);s=mania(base());for(const k of ['activity','sleep','speech','racing'])s=set(s,'mania.features.'+k,'no');for(const k of ['spending','sexual','driving','otherRisk'])s=set(s,'mania.features.'+k,'yes');assert.equal(M.assess(s).mania.groups,1);assert.equal(M.assess(s).mania.cluster,false)});
test('Unknown competing history prevents leading unipolar direction',()=>{for(const p of ['mania.period','medical.temporal','substance.temporal','course.chronic','stress.present'])assert.notEqual(M.assess(set(base(),p,'unknown')).leading,'mdd')});
test('Same-time, frequency and change requirements affect MDD',()=>{for(const p of ['course.together'])assert.notEqual(M.assess(set(base(),p,'no')).leading,'mdd');let s=base();s=set(s,'symptoms.mood.present','no');s=set(s,'symptoms.interest.present','no');assert.notEqual(M.assess(s).leading,'mdd');assert.notEqual(M.assess(set(base(),'course.duration','under14')).leading,'mdd')});
test('No secret persistence or transmission in module; all seven names bilingual',()=>{for(const d of M.disorders){assert.equal(d.name.length,2);assert(d.references.every(id=>M.references.some(r=>r.id===id)));}for(const file of ['state','scoring','engine','safety','ui'])assert(!/localStorage|sessionStorage|sendBeacon|fetch\(|XMLHttpRequest/.test(fs.readFileSync('dist/mood/'+file+'.js','utf8')))});
test('Brief psychotic activation prompts care without establishing full mania duration',()=>{let s=mania(base(),true);s=set(s,'mania.duration','under4');s=set(s,'mania.psychosis','yes');s=set(s,'mania.current','yes');const r=M.assess(s);assert.equal(r.mania.maniaPattern,false);assert.equal(r.safety.action,'immediate');assert.equal(r.leading,null);assert.notEqual(r.directions.find(d=>d.id==='bipolar1').level,3)});
fs.mkdirSync('work',{recursive:true});fs.writeFileSync('work/logic-test-results.json',JSON.stringify({passed:results.length,tests:results},null,2));fs.writeFileSync('work/mood-fixture.json',JSON.stringify(base(),null,2));
