const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm');const boot=require(process.cwd()+'/tests/differential-v2-harness.cjs');let count=0;function test(name,fn){fn();count++;console.log('PASS Mood audit '+name);}
function setup(values){const c=boot(),M=c.Mood;for(let i=0;i<9;i++)M.update('phq.'+i,String(values[i]??0));for(const id of M.phqDomainMap)if(M.store.state.symptoms[id]?.present==='yes')for(const [key,value]of Object.entries({duration:'14to29',changed:'yes',severity:'1',...(id==='motor'?{observed:'yes'}:{})}))M.update('symptoms.'+id+'.'+key,value);return c;}
const explain=c=>c.Mood.explainSymptoms(c.Mood.store.state,c.Mood.assess(c.Mood.store.state));
test('5/27 with five several-day symptoms yields 0/9 without lost data',()=>{const c=setup([1,1,1,1,1]),M=c.Mood,r=M.assess(M.store.state),x=explain(c);assert.equal(r.phq.total,5);assert.equal(r.phq.band,1);assert.equal(r.supplied.length,5);assert.equal(r.qualified.length,0);assert.equal(x.reported,5);assert.equal(x.carryMismatch,false);for(const row of x.rows.filter(x=>x.reported))assert.deepEqual([...row.reasons],['moodExplain.frequencyLow']);});
test('same total 5 can include one qualified symptom',()=>{const c=setup([3,2]);assert.equal(c.Mood.assess(c.Mood.store.state).phq.total,5);assert.equal(explain(c).qualified,1);});
test('PHQ 2 remains excluded under existing stricter frequency rule',()=>{const c=setup([2,2,2,2,2]);assert.equal(c.Mood.assess(c.Mood.store.state).phq.total,10);assert.equal(explain(c).reported,5);assert.equal(explain(c).qualified,0);});
test('all nine carry-forward positions and all four values match',()=>{for(let i=0;i<9;i++)for(let v=0;v<4;v++){const c=setup(Array.from({length:9},(_,j)=>j===i?v:0)),M=c.Mood,x=explain(c);assert.equal(x.rows[i].score,v);assert.equal(x.rows[i].reported,v>0);assert.equal(x.carryMismatch,false);assert.equal(M.store.state.symptoms[M.phqDomainMap[i]].present,v?'yes':'no');}});
for(const [field,value,key]of [['duration','under14','durationShort'],['duration','unknown','durationUnknown'],['changed','no','changeNo'],['changed','unknown','changeUnknown']])test('exclusion reason '+key,()=>{const c=setup([3]);c.Mood.update('symptoms.interest.'+field,value);const x=explain(c);assert.equal(x.qualified,0);assert(x.rows[0].reasons.includes('moodExplain.'+key));});
test('missing follow-up is uncertainty, not absence',()=>{const c=setup([3]);c.Mood.update('symptoms.interest.duration','');const x=explain(c);assert(x.rows[0].reasons.includes('moodExplain.durationUnknown'));assert(!x.rows[0].reasons.includes('moodExplain.notReported'));});
test('motor observation criterion has an explicit explanation',()=>{const c=setup([0,0,0,0,0,0,0,3]);c.Mood.update('symptoms.motor.observed','no');assert(explain(c).rows[7].reasons.includes('moodExplain.observationNo'));c.Mood.update('symptoms.motor.observed','unknown');assert(explain(c).rows[7].reasons.includes('moodExplain.observationUnknown'));});
test('item 9 frequency exception and independent safety check retained',()=>{const c=setup([0,0,0,0,0,0,0,0,1]),M=c.Mood;assert.equal(explain(c).qualified,1);M.update('symptoms.death.duration','under14');assert.equal(explain(c).qualified,0);assert.notEqual(M.assess(M.store.state).safety.action,'noneTriggered');M.update('safety.intent','yes');assert(c.GlobalSafety.current().requiresInterruption);});
test('PHQ editing updates counts and removes obsolete follow-ups',()=>{const c=setup([3]),M=c.Mood;assert.equal(explain(c).qualified,1);M.update('phq.0','0');assert.equal(explain(c).reported,0);assert.equal(explain(c).qualified,0);assert.equal(M.store.state.symptoms.interest.duration,undefined);M.update('phq.0','1');assert(explain(c).rows[0].reasons.includes('moodExplain.durationUnknown'));assert.equal(explain(c).carryMismatch,false);});
test('missing PHQ is not zero or an inferred negative answer',()=>{const c=boot(),M=c.Mood,r=M.assess(M.store.state),x=explain(c);assert.equal(r.phq.total,null);assert.equal(x.unanswered,9);assert(x.rows.every(row=>row.reported===null));assert(x.rows.every(row=>row.reasons.includes('moodExplain.presenceUnknown')));});
test('synthetic inconsistent low-level state is flagged without repair',()=>{const c=setup([3]),M=c.Mood;M.store.state=M.setAnswer(M.store.state,'symptoms.interest.frequency','some');const before=JSON.stringify(M.store.state);assert(explain(c).carryMismatch);assert.equal(JSON.stringify(M.store.state),before);});
test('score totals and severity boundaries remain arithmetic only',()=>{const M=boot().Mood;for(let total=0;total<=27;total++){let left=total;const values={};for(let i=0;i<9;i++){values[i]=String(Math.min(3,left));left-=Number(values[i]);}const r=M.scorePHQ9(values);assert.equal(r.total,total);assert.equal(r.band,total<5?0:total<10?1:total<15?2:total<20?3:4);}assert.equal(M.scorePHQ9({0:'unknown'}).total,null);});
test('explanation is read-only, bilingual and details closed by default',()=>{const c=setup([1,1,1,1,1]),M=c.Mood,r=M.assess(M.store.state),before=JSON.stringify([M.store.state,r]);for(const l of [0,1]){const html=M.explanationHTML(M.store.state,r,l);assert(html.includes(l?'Symptom areas reported on PHQ-9: 5/9':'PHQ-9 中报告出现过的症状领域：5/9'));assert(html.includes(l?'A count of 0 does not mean':'计数为 0 不代表'));assert(html.includes('<details class="mood-count-details">'));assert(!html.includes('mood-count-details" open'));assert(!html.includes('undefined'));assert(!html.includes('moodExplain.'));}assert.equal(JSON.stringify([M.store.state,r]),before);});
test('real language-switch handler preserves result, answers and safety',()=>{const c=setup([1,1,1,1,1]);let html='';c.document={documentElement:{},querySelector:s=>s==='#app'?{set innerHTML(v){html=v;}}:s==='#lang'?{}:null,querySelectorAll:()=>[],getElementById:()=>null};c.window={scrollTo(){}};vm.runInContext(fs.readFileSync('src/app.js','utf8'),c);c.GlobalSafety.reset();for(const p of c.GlobalSafety.paths)c.GlobalSafety.answer(p,false);c.GlobalSafety.acknowledge();c.Mood.store.step=11;vm.runInContext("navigate('screen')",c);assert(html.includes('mood-count-explanation'));const before=JSON.stringify([c.Mood.store,c.GlobalSafety.store]);vm.runInContext('switchLanguage()',c);assert.equal(JSON.stringify([c.Mood.store,c.GlobalSafety.store]),before);assert(html.includes('mood-count-explanation'));});
fs.writeFileSync('work/mood-integrity-results.json',JSON.stringify({passed:true,count},null,2));
