const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const c={lang:0,esc:x=>String(x)};vm.createContext(c);for(const f of ['runtime','catalog'])vm.runInContext(fs.readFileSync('dist/i18n/'+f+'.js','utf8'),c);for(const p of ['schema','rules','engine','adapters','extraction','resources','runtime','ui'])vm.runInContext(fs.readFileSync('dist/safety/'+p+'.js','utf8'),c);for(const p of ['shared/core','shared/safety','shared/fields','mood/data','mood/scoring','mood/safety','mood/state','mood/engine','mood/ui','mood/summary','anxiety/data','anxiety/state','anxiety/engine','anxiety/summary','anxiety/ui','ocd/data','ocd/state','ocd/engine','ocd/summary','ocd/ui'])vm.runInContext(fs.readFileSync('dist/'+p+'.js','utf8'),c,{filename:p});const O=c.OCD;
function set(s,items){for(const [k,v]of Object.entries(items))s=O.setAnswer(s,k,v);return s}function base(){return set(O.emptyState(),{'intro.agree':'yes','intro.immediate':'no','screen.intrusive':'no','screen.ritual':'no','screen.interfere':'no'});}function ocd(s,extra={}){return set(s,{ 'obsessions.present':'yes','obsessions.ego':'yes','obsessions.control':'yes','themes.contamination':'yes','visible.wash':'yes','cycle.response':'yes','cycle.relief':'yes','impact.time':'1to3','impact.distress':'2','impact.work':'2',...extra});}function r(s){return O.assess(s,{},{});}function test(n,f){f();console.log('PASS '+n);}
test('1 contamination plus washing and impairment is high consistency',()=>assert.equal(r(ocd(base())).level,3));
test('2 ego-dystonic harm intrusion is not violent intent or psychosis',()=>{const x=r(ocd(base(),{'themes.harm':'yes','harm.intrusive':'yes','harm.desire':'no','harm.intent':'no','harm.plan':'no'}));assert(x.harmObsession);assert.equal(x.safety.action,'noneTriggered');assert(!x.alternatives.some(a=>a.id==='psychosis'));});
test('3 broad worry without rituals flags GAD direction above OCD',()=>{const x=r(set(base(),{'diff.gad':'yes'}));assert.equal(x.level,0);assert(x.alternatives.some(a=>a.id==='gad'));});
test('4 checking with temporary relief is OCD compatible',()=>assert(r(ocd(base(),{'themes.checking':'yes','visible.check':'yes'})).level>=2));
test('5 fixed conviction / reality testing flags psychosis differential',()=>assert(r(set(base(),{'psychosis.fixed':'yes','psychosis.reality':'yes'})).alternatives.some(a=>a.id==='psychosis')));
test('6 appearance pattern flags BDD',()=>assert(r(set(base(),{'diff.bdd':'yes'})).alternatives.some(a=>a.id==='bdd')));
test('7 hair pulling flags trichotillomania',()=>assert(r(set(base(),{'diff.hair':'yes'})).alternatives.some(a=>a.id==='trichotillomania')));
test('8 skin picking flags excoriation',()=>assert(r(set(base(),{'diff.skin':'yes'})).alternatives.some(a=>a.id==='excoriation')));
test('9 ego-syntonic perfectionism flags OCPD direction, not OCD',()=>{const x=r(set(base(),{'diff.ocpd':'yes'}));assert.equal(x.level,0);assert(x.alternatives.some(a=>a.id==='ocpd'));});
test('10 depressive symptoms remain a comorbid differential',()=>assert(r(ocd(set(base(),{'diff.depression':'yes'}))).alternatives.some(a=>a.id==='depression')));
test('11 intrusive self-harm image without desire/plan is not suicidal intent',()=>{const x=r(ocd(base(),{'harm.intrusive':'yes','harm.desire':'no','harm.intent':'no','harm.plan':'no'}));assert(x.harmObsession);assert.equal(x.safety.action,'noneTriggered');});
test('12 suicidal intent with a plan interrupts OCD result',()=>assert.equal(r(ocd(base(),{'safety.current':'yes','harm.intent':'yes','harm.plan':'yes'})).safety.action,'immediate'));
test('13 taboo intrusion with mental checking is OCD compatible',()=>assert(r(ocd(base(),{'themes.taboo':'yes','mental.review':'yes','visible.reassure':'yes'})).level>=2));
test('14 direct trauma re-experiencing flags trauma differential',()=>assert(r(set(base(),{'obsessions.trauma':'yes'})).alternatives.some(a=>a.id==='trauma')));
test('15 pleasurable / regulating repetition flags neurodevelopmental differential',()=>assert(r(set(base(),{'diff.autism':'yes'})).alternatives.some(a=>a.id==='neurodevelopmental')));
test('bilingual summary and UI expose boundary and explanations',()=>{let s=ocd(base(),{'harm.intrusive':'yes','harm.desire':'no','harm.intent':'no','harm.plan':'no'}),x=r(s);for(const l of [0,1]){c.lang=l;O.store.state=s;O.store.step='results';assert(O.summary(s,x,l).includes(l?'Assessment Summary':'评估摘要'));assert(O.render().includes(l?'Why this result?':'为什么得到这个结果？'));}assert(!/localStorage|sessionStorage|fetch\(/.test(['data','state','engine','summary','ui'].map(f=>fs.readFileSync('dist/ocd/'+f+'.js','utf8')).join('')));});
