const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');const c={lang:1,esc:s=>String(s).replaceAll('<','&lt;')};vm.createContext(c);for(const m of fs.readFileSync('dist/index.html','utf8').matchAll(/<script src="([^"]+)"/g))if(m[1]!=='app.js')vm.runInContext(fs.readFileSync('dist/'+m[1],'utf8'),c);vm.runInContext(fs.readFileSync('tests/psychosis-fixtures.js','utf8'),c);const {Psychosis:A,PsychosisFixtures:F,GlobalSafety:G,SymptomRouter:R,Differential:D,ExperienceContext:X}=c,clone=x=>JSON.parse(JSON.stringify(x));function test(n,f){f();console.log('PASS Psychosis '+n);}const level=(v={},classic=true)=>F.load(v,classic).patterns[0].level;
test('awake recurrent impairing perceptions warrant assessment',()=>{assert.equal(level(),3);assert.equal(F.load().score,null);assert(D.current().candidates.some(x=>x.id==='psychosis'));});
for(const [name,values]of Object.entries({sleep:{'audio.sleep':'yes','sleep.transitions':'yes'},isolated:{'audio.frequency':'isolated'},history:{'audio.time':'history','course.time':'history'},trauma:{'audio.trauma':'yes','trauma.reliving':'yes','trauma.only':'yes'},substance:{'audio.substance':'yes','substance.use':'yes'},culture:{'culture.shared':'yes'},grief:{'culture.grief':'yes'},medication:{'substance.medication':'yes'},medical:{'medical.illness':'yes'},sleepDeprivation:{'sleep.deprivation':'yes'},depressionOnly:{'mood.depression':'yes','mood.onlyDepression':'yes'},activationOnly:{'mood.activation':'yes','mood.onlyActivation':'yes'}}))test(name+' prevents strongest independent interpretation',()=>assert(level(values)<3));
for(const [name,values]of Object.entries({negativeOnly:{'negative.motivation':'yes','negative.pleasure':'yes'},dissociation:{'trauma.dissociation':'yes'},ocdIntrusion:{'ocd.intrusive':'yes','ocd.rituals':'yes','ocd.linked':'yes'},ordinarySuspicion:{'belief.targeted':'yes','belief.current':'yes','belief.conviction':'doubt','belief.insight':'open'},longstandingCommunication:{'organization.speech':'yes','organization.baseline':'yes'}}))test(name+' is not sufficient for psychosis',()=>{assert(level(values,false)<2);assert.notEqual(G.current().urgency,'acute');});
test('fixed conviction and limited alternatives modeled separately',()=>{assert.equal(level({'belief.targeted':'yes','belief.current':'yes','belief.conviction':'complete','belief.insight':'none','function.decline':'yes'},false),3);assert(level({'belief.targeted':'yes','belief.current':'yes','belief.conviction':'complete','belief.insight':'open','function.decline':'yes'},false)<3);});
test('unknown ruleouts stay unknown',()=>{const r=F.load({'substance.use':'unknown'});assert.equal(r.facts.substance,'unknown');assert(r.ruleouts.includes('substance'));assert(r.patterns[0].level<3);});
test('historical and current conflict is retained',()=>{const r=F.load({'course.time':'history'});assert(r.conflicts.length);assert(r.patterns[0].level<3);});
test('underage scope prevents adult interpretation',()=>assert.equal(level({'intro.adult':'no'}),0));
test('hiding a modality clears only dependent answers',()=>{F.load();A.update('perception.audio','no');assert.equal(Object.keys(A.store.state.audio).length,0);assert.equal(A.store.state.function.decline,'yes');assert(!A.plan(A.store.state).some(s=>s.id==='audio'));});
test('edit invalidates differential evidence',()=>{F.load();A.update('audio.frequency','isolated');assert.equal(A.store.result,null);assert.equal(D.adapt('psychosis',A.store,A).ready,false);});
for(const [path,domain]of [['psychosis.commandSelfHarm','suicide'],['psychosis.commandOtherHarm','harm_to_others'],['medical.severeConfusion','medical'],['suicide.intent','suicide']])test('shared acute '+path,()=>{F.load();A.update('safety.'+path,'yes');assert.equal(G.current().urgency,'acute');assert.equal(G.current().primaryDomain,domain);assert(G.guard('psychosis').show);});
test('a command does not invent actual desire or intent',()=>{F.load();A.update('safety.psychosis.commandOtherHarm','yes');assert.notEqual(G.current().signals.harmToOthers.intent,true);assert.notEqual(G.current().signals.harmToOthers.actualDesire,true);});
test('all new rules require review',()=>{assert.equal(A.version,'psychosis-assessment-v1.0.0');for(const r of [...A.ruleCatalog,...D.rules.filter(r=>r.id.includes('PSYCHOSIS')),...R.rules.filter(r=>r.domain==='psychosis')])assert.equal(r.reviewStatus,'unreviewed');});
const excluded=['My friend says a voice is telling her to jump off the balcony.','My brother hears voices every day.','My doctor asked whether I hear voices. I said no.','I do not hear voices.','Five years ago I heard voices, but not anymore.','If I heard voices someday, I would ask for help.','My friend said "I hear voices every day."','我哥哥最近总说他听到有人和他说话。','我的医生问我是否听到声音。我说没有。','我没有听到声音。','五年前我听到声音，现在没有。','如果有一天我听到声音，我会求助。'];
for(const [i,t]of excluded.entries())test('attribution negative history hypothetical '+i,()=>{assert.notEqual(X.analyze(t).facts.perception,true);assert.notEqual(G.extract(t).signals.psychosis.commandSelfHarm,true);assert.notEqual(R.route(R.extract(t)).primaryRoute,'psychosis');});
for(const t of ['The voices are telling me to jump from the balcony.','声音命令我从阳台跳下去。'])test('dangerous self command bilingual '+t.length,()=>{assert.equal(G.fromExtraction(G.extract(t)).result.urgency,'acute');assert.equal(G.extract(t).signals.psychosis.commandSelfHarm,true);});
test('unrelated command and feared intrusive image not combined',()=>{const s=G.extract('A voice is telling me the time. I am afraid of an intrusive thought about jumping.').signals;assert.notEqual(s.psychosis.commandSelfHarm,true);assert.notEqual(s.suicide.intent,true);});
test('direct violence concerning partner remains actionable',()=>assert.equal(G.fromExtraction(G.extract('I want to stab my partner tonight and I already prepared the knife.')).result.urgency,'acute'));
test('structured results and safety state independent of language',()=>{const r=F.load(),before=clone({state:A.store,stateSafety:G.store,result:D.current()});for(const l of [0,1]){c.lang=l;const h=A.render();assert(!h.includes('undefined'));assert(!h.includes('psychosisUI.'));assert(A.summary(A.store.state,r,l));assert.deepEqual(clone({state:A.store,stateSafety:G.store,result:D.current()}),before);}});
test('all questions options and labels bilingual',()=>{for(const q of A.questions){assert(c.I18n.text(q.label,0));assert(c.I18n.text(q.label,1));for(const o of q.options)assert(o[1]&&o[2]);}});
const routeText='I keep hearing voices while fully awake. I am completely convinced the TV sends messages to me. I cannot work because my functioning has declined.';
const routeZh='我反复听到声音，完全清醒。我完全确信电视向我传达信息。我功能下降，无法工作。';
test('Router current contextual primary bilingual',()=>{for(const t of [routeText,routeZh]){const p=R.extract(t);assert(R.validate(p));assert.equal(R.route(p).primaryRoute,'psychosis');}});
for(const [name,t]of [['OCD','I keep checking the door again and again because unwanted intrusive thoughts terrify me.'],['PTSD','I was assaulted and now I keep reliving it, avoid that area, and feel constantly on guard.'],['sleep','I sometimes hear my name while falling asleep.'],['idiom','My boss is driving me crazy.'],['technical','My phone is talking to me again through its voice assistant.']])test('Router false-positive protection '+name,()=>assert.notEqual(R.route(R.extract(t)).primaryRoute,'psychosis'));
test('Router contextual qualifier protects cultural explanation',()=>assert.notEqual(R.route(R.extract(routeText+' I have a belief shared within my community.')).primaryRoute,'psychosis'));
test('Router suicide safety overrides psychosis recommendation',()=>{G.reset();R.clear();assert.equal(R.submit(routeText+' I intend to kill myself.'),'safety');assert.equal(R.store.profile,null);});
test('negation refers to experience rather than any negative word',()=>{assert.equal(X.analyze("I hear voices and don't know why.").facts.perception,true);assert.equal(X.analyze('I am not convinced the TV is sending messages.').facts.belief,false);});
test('historical observation retained without current positive fact',()=>{const p=X.analyze('I heard voices years ago but not anymore.');assert(p.observations.some(x=>x.feature==='perception'&&x.context.temporality==='historical'));assert.notEqual(p.facts.perception,true);});
test('negative features with depression retain shared Mood alternative',()=>{F.load({'negative.motivation':'yes','mood.depression':'yes'},false);assert(D.current().candidates.some(x=>x.id==='mood'&&x.level>0));});
test('new disorganization is separate from longstanding differences',()=>{assert.equal(F.load({'organization.thought':'yes'},false).facts.disorganization,true);assert.equal(F.load({'organization.thought':'yes','organization.baseline':'yes'},false).facts.disorganization,false);});
test('low distress does not erase functional decline',()=>assert.equal(level({'audio.distress':'none','audio.impact':'none','function.decline':'yes'}),3));
test('no impairment and isolated mild experience stays low',()=>assert(level({'audio.frequency':'isolated','audio.distress':'mild','audio.impact':'mild','function.decline':'no'})<2));
test('corrupted safety value fails closed',()=>{F.load();A.store.state.safety.medical.severeConfusion='invalid';assert.equal(G.current().assessmentStatus,'unable_to_assess');});
test('summary covers structured sections without narrative or diagnostic probability',()=>{const r=F.load(),s=A.summary(A.store.state,r,1);for(const sec of A.plan(A.store.state))assert(s.includes(c.I18n.t(sec.label,1)));assert(!s.includes('psychosisUI.'));assert(!/\d+%/.test(s));});
test('quotation scope survives multiple sentences',()=>{const p=X.analyze('My friend said, "I hear voices. I am completely convinced the TV is sending me messages."');assert.notEqual(p.facts.perception,true);assert.notEqual(p.facts.belief,true);assert.notEqual(p.facts.conviction,true);});
test('quoted dangerous command remains actionable when directly experienced',()=>assert.equal(G.fromExtraction(G.extract('A voice is telling me "jump off the balcony".')).result.urgency,'acute'));
test('command to avoid harm does not become command to harm',()=>assert.notEqual(G.extract('The voices tell me not to jump.').signals.psychosis.commandSelfHarm,true));
test('Chinese first-person intent with relational target retained',()=>assert.equal(G.fromExtraction(G.extract('我打算杀我的女友，已经有计划。')).result.urgency,'acute'));
test('structured clarification outranks weaker text without erasing conflict',()=>{const e=[D.fact('psychosis.sleep',false,'router',['psychosis.sleep'],0,'free_text_extraction'),D.fact('psychosis.sleep',true,'clarification',['sleep.transitions'],1,'user_clarification')],n=D.normalize(e);assert(n.valid);assert.equal(n.facts['psychosis.sleep'],true);assert.equal(n.contradictions.length,1);assert.equal(n.contradictions[0].selectedValue,true);});
test('equivalent bilingual Router structured clinical facts',()=>assert.deepEqual(clone(R.extract(routeText).psychosis),clone(R.extract(routeZh).psychosis)));
for(const [domain,extra]of [['mood','I feel depressed every day and have lost interest in everything.'],['anxiety','I worry all the time about work, money and family and cannot stop.'],['ocd','I repeatedly check the door because of unwanted intrusive thoughts and have to repeat rituals.'],['trauma','I was assaulted and now keep reliving it and avoid reminders while constantly on guard.']])test('Router retains mixed '+domain,()=>{const r=R.route(R.extract(routeText+' '+extra));assert(r.candidateRoutes.some(x=>x.domain==='psychosis'));assert(r.candidateRoutes.some(x=>x.domain===domain));});
test('actual violent intent and control difficulty remain separate from commands',()=>{F.load();A.update('safety.psychosis.commandOtherHarm','yes');A.update('safety.harmToOthers.intent','yes');A.update('safety.harmToOthers.impairedBehavioralControl','yes');const r=G.current();assert(r.requiresInterruption);assert.equal(r.signals.harmToOthers.intent,true);assert.equal(r.signals.harmToOthers.impairedBehavioralControl,true);});
test('all modality-specific dimensions are retained in state',()=>{for(const k of A.modalities){const r=F.load({['perception.'+k]:'yes',[k+'.time']:'current',[k+'.frequency']:'recurrent',[k+'.awake']:'yes',[k+'.conviction']:'fluctuating',[k+'.insight']:'open',[k+'.distress']:'severe',[k+'.impact']:'mild',[k+'.sleep']:'no',[k+'.trauma']:'no',[k+'.substance']:'no'});assert.equal(A.store.state[k].conviction,'fluctuating');assert.equal(A.store.state[k].insight,'open');assert(r.perceptions.some(x=>x.id===k&&x.present===true));}});
test('no experience narrative or persistence API in new modules',()=>{for(const p of fs.readdirSync('src/psychosis').filter(p=>p.endsWith('.js'))){const code=fs.readFileSync('src/psychosis/'+p,'utf8');assert(!/localStorage|sessionStorage|indexedDB|fetch\(|XMLHttpRequest|sendBeacon|console\.log/.test(code));}const output=JSON.stringify(R.extract(routeText));assert(!output.includes(routeText));assert(!Object.keys(F.load()).some(k=>/narrative|rawText/.test(k)));});
for(const f of ['differential-fixtures','trauma-fixtures','adhd-fixtures','eating-fixtures'])vm.runInContext(fs.readFileSync('tests/'+f+'.js','utf8'),c);
for(const [name,module,make]of [['mood',c.Mood,()=>c.DifferentialFixtures.mood()],['anxiety',c.Anxiety,()=>c.DifferentialFixtures.gad()],['ocd',c.OCD,()=>c.DifferentialFixtures.ocd()],['trauma',c.Trauma,()=>c.TraumaFixtures.classic()],['adhd',c.ADHD,()=>c.ADHDTestFixtures.classic()],['eating',c.Eating,()=>c.EatingFixtures.state()]])test('shared comparison retains independent '+name+' and Psychosis evidence',()=>{F.load();module.store.state=make();module.store.result=module.assess(module.store.state,c.Mood.store.state,c.Anxiety.store.state);const r=D.current();assert(!r.blocked);assert(r.evidence.some(e=>e.sourceModule===name));assert(r.evidence.some(e=>e.sourceModule==='psychosis'));assert(r.candidates.some(e=>e.domain===name&&e.level>0));assert(r.candidates.some(e=>e.id==='psychosis'&&e.level>0));});
// Final acceptance audit: structured shared Safety remains authoritative in this module.
for(const [name,signals,urgency,domain]of [
 ['suicide intent',{'suicide.intent':true},'acute','suicide'],
 ['self-harm urges',{'selfHarm.currentUrges':true},'elevated','self_harm'],
 ['harm-to-others intent',{'harmToOthers.intent':true},'acute','harm_to_others'],
 ['dangerous self command',{'psychosis.commandSelfHarm':true},'acute','suicide'],
 ['severe mania',{'mania.impairedJudgment':true,'mania.recklessDriving':true},'acute','mania'],
 ['basic self-care',{'selfCare.unableToEat':true},'elevated','self_care'],
 ['medical emergency',{'medical.severeBreathingDifficulty':true},'acute','medical'],
 ['delirium-like confusion',{'medical.severeConfusion':true},'acute','medical'],
 ['intoxication emergency',{'substances.severeIntoxication':true},'acute','medical'],
 ['withdrawal emergency',{'substances.severeWithdrawalConcern':true},'acute','medical']
])test('final shared Safety authority: '+name,()=>{F.load();for(const [p,v]of Object.entries(signals))G.answer(p,v);const r=G.current();assert.equal(r.urgency,urgency);assert.equal(r.primaryDomain,domain);assert(G.guard('psychosis').show);assert.equal(r.requiresInterruption,urgency==='acute');});
for(const [name,text]of [
 ['other and denial','My brother hears voices. 我现在没有听到声音。'],
 ['quoted speech','我哥哥说：“I hear voices.”'],
 ['negation','I do not hear voices. 我没有听到声音。'],
 ['historical','I heard voices five years ago. 现在没有。'],
 ['hypothetical','If I hear voices someday，我会寻求帮助。']
])test('final mixed-language contextual protection: '+name,()=>{const s=G.extract(text),p=R.extract(text),x=X.analyze(text);assert.notEqual(s.signals.psychosis.hallucinations,true);assert.notEqual(s.signals.psychosis.commandSelfHarm,true);assert.notEqual(p.psychosis.perception,true);assert.notEqual(x.facts.perception,true);assert.notEqual(R.route(p).primaryRoute,'psychosis');});
test('final mixed-language self intent survives an other-person report',()=>{const s=G.fromExtraction(G.extract('My brother hears voices. 我打算自杀。'));assert.equal(s.result.urgency,'acute');assert.equal(s.signals.suicide.intent,true);assert.notEqual(s.signals.psychosis.hallucinations,true);});
