// All input descriptions in this suite are synthetic acceptance fixtures.
const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
let markup='';const nodes={app:{set innerHTML(v){markup=v;}},lang:{focus(){}},detail:{open:false}};
const c={document:{documentElement:{},querySelector:s=>nodes[s.slice(1)]||null,querySelectorAll:()=>[],getElementById:id=>nodes[id]||null},window:{scrollTo(){}}};vm.createContext(c);
for(const m of fs.readFileSync('dist/index.html','utf8').matchAll(/<script src="([^"]+)"/g))vm.runInContext(fs.readFileSync('dist/'+m[1],'utf8'),c,{filename:m[1]});
const R=c.SymptomRouter,G=c.GlobalSafety,copy=x=>JSON.parse(JSON.stringify(x));let count=0;
function test(name,fn){fn();count++;console.log('PASS Router '+name);}
const result=text=>R.route(R.extract(text));
const scenarios=[
 ['Mood primary','I feel depressed every day, cannot enjoy anything, and have no energy.','mood',['mood']],
 ['Anxiety primary','I worry constantly about work, money, school and family.','anxiety',['anxiety']],
 ['OCD primary','I repeatedly check the stove even after I know it is off.','ocd',['ocd']],
 ['OCD plus Mood','I keep having unwanted harm thoughts and checking things repeatedly. I am also depressed and have lost interest in everything.','ocd',['ocd','mood']],
 ['Mood plus Anxiety','I feel hopeless and low but also worry about everything all day.','mood',['mood','anxiety']],
 ['OCD plus Anxiety','I constantly worry, but I also keep checking the door because I cannot trust that it is locked.','ocd',['ocd','anxiety']],
 ['insufficient',"I don't feel right.",null,[]],
 ['intrusive harm',"I am terrified by intrusive thoughts of stabbing someone, but I don't want to hurt anyone and I keep avoiding knives.",'ocd',['ocd']],
 ['historical','I had panic attacks three years ago but not anymore.',null,[]],
 ['third person','My brother has OCD and checks the door constantly.',null,[]],
 ['hypothetical','If I became depressed, I would probably stay in bed.',null,[]],
 ['supported trauma','I keep reliving a traumatic assault in vivid flashbacks.','trauma',['trauma']],
 ['mixed language','我最近一直很焦虑 and I keep checking whether the door is locked.',null,['anxiety','ocd']]
];
for(const [name,text,primary,domains]of scenarios)test(name,()=>{const r=result(text);assert.equal(r.primaryRoute,primary);assert.deepEqual(copy(r.candidateRoutes.map(v=>v.domain)),domains);if(name==='supported trauma')assert.deepEqual(copy(r.unsupportedSignals),[]);if(name==='insufficient')assert.deepEqual(copy(r.unresolvedQuestions),['main_concern']);});
const pairs=[
 ['Mood','最近什么都提不起兴趣，心情一直很低落。','Recently I have lost interest in everything and have been feeling very low.'],
 ['Anxiety','我每天都担心工作、钱和家里的事情，停不下来。','I worry every day about work, money and my family and cannot stop.'],
 ['OCD','我知道门已经锁了，但还是要检查十几次。','I know the door is locked, but I still have to check it more than ten times.']
];
for(const [name,zh,en]of pairs)test(name+' bilingual profile and route parity',()=>{const a=R.extract(zh),b=R.extract(en);assert.deepEqual(copy(a),copy(b));assert.deepEqual(copy(R.route(a)),copy(R.route(b)));});
function reset(){G.reset();R.clear();}
function clearSafety(){for(const p of G.paths)G.answer(p,false);G.acknowledge();}
test('suicide override executes before symptom extraction',()=>{reset();const extract=R.extract;let calls=0;R.extract=()=>{calls++;return R.empty();};assert.equal(R.submit('I am depressed and I plan to kill myself tonight.'),'safety');assert.equal(calls,0);assert.equal(G.current().urgency,'acute');vm.runInContext("navigate('router')",c);assert(!markup.includes('data-router-start'));assert(!markup.includes('data-global="continue"'));R.extract=extract;});
test('medical override prevents panic routing',()=>{reset();assert.equal(R.submit('I cannot breathe, have severe chest pain and almost passed out.'),'safety');assert.equal(G.current().primaryDomain,'medical');assert.equal(G.current().urgency,'acute');assert.equal(R.store.profile,null);});
test('OCD safety bridge retains unknown intent independently',()=>{reset();assert.equal(R.submit("I keep imagining stabbing my baby and it terrifies me. I do not want to do it, and I keep hiding knives."),'safety');assert.notEqual(G.current().urgency,'acute');assert.notEqual(G.store.signals.harmToOthers.intent,true);assert.equal(R.route(R.store.profile).primaryRoute,'ocd');assert.equal(R.store.result,null);});
test('clarification acknowledgment resumes pending router without raw text',()=>{reset();const text=scenarios[0][1];assert.equal(R.submit(text),'safety');assert.equal(R.store.result,null);assert(!JSON.stringify(R.store).includes(text));assert(G.acknowledge());assert.equal(R.resume(),'router');assert.equal(R.store.result.primaryRoute,'mood');});
test('elevated guidance must precede router and cannot be bypassed by choice',()=>{reset();R.submit('I feel hopeless and wish I were dead.');assert(G.current().requiresGuidance);assert.equal(R.start('mood'),'safety');assert.equal(R.choose('mood'),false);assert.equal(R.store.result,null);});
test('invalid safety blocks router even with a pending result',()=>{reset();R.submit(scenarios[0][1]);G.acceptExtraction('corrupted');assert.equal(R.resume(),'safety');vm.runInContext("navigate('router')",c);assert(!markup.includes('data-router-start'));});
test('unknown symptoms remain unknown and invalid structured profiles fail closed',()=>{const p=R.empty();assert.equal(p.mood.depressedMood,'unknown');assert(R.validate(p));p.mood.depressedMood='yes';assert(!R.validate(p));assert.equal(R.route(p).primaryRoute,null);assert.deepEqual(copy(R.route(p).unresolvedQuestions),['invalid_profile']);assert.equal(R.route({}).primaryRoute,null);});
test('negated symptoms do not route',()=>{for(const text of ['I am not depressed. I do not have panic attacks. I do not repeatedly check the door.','我没有反复检查。我没有惊恐发作。'])assert.equal(result(text).primaryRoute,null);});
test('ordinary sadness, perfectionism and vague distress do not diagnose',()=>{for(const text of ['I feel sad today.','I like my desk perfectly organized.','I feel distressed.','我喜欢整齐。'])assert.equal(result(text).primaryRoute,null);});
test('current symptoms are distinct from historical, hypothetical and other-person reports',()=>{assert.equal(result('I am having panic attacks every day now.').primaryRoute,'anxiety');for(const text of ['My girlfriend checks the door 20 times.','I used to have panic attacks years ago, but not anymore.','If I ever became depressed...','我女友反复检查门。','如果我抑郁。','我三年前有惊恐发作。'])assert.equal(result(text).primaryRoute,null);});
test('other person and self clauses retain attribution',()=>{const p=R.extract('My girlfriend repeatedly checks the door. I feel depressed every day and have no energy.');assert.equal(p.ocd.checking,'unknown');assert.equal(R.route(p).primaryRoute,'mood');});
test('unsupported domains remain outside registered assessments',()=>{for(const [text,key]of [['I have lifelong distractibility and hyperactivity.','attention']]){const r=result(text);assert.equal(r.primaryRoute,null);assert(r.unsupportedSignals.includes(key));}assert.equal(result('I binge eat and use purging.').primaryRoute,null);assert(!result('I binge eat and use purging.').unsupportedSignals.includes('eating'));assert(R.domains.has('eating'));assert.equal(R.domains.size,7);assert(R.domains.has('psychosis'));assert.equal(result('I am hearing voices.').primaryRoute,null);assert(!result('I am hearing voices.').unsupportedSignals.includes('psychotic'));assert.throws(()=>R.registerAssessmentDomain({id:'ptsd'}));});
test('tie asks a minimal question; choice never fabricates symptoms',()=>{reset();clearSafety();R.store.profile=R.extract('I constantly worry and repeatedly check the door.');R.store.pending=true;R.resume();assert.equal(R.store.result.confidenceStatus,'uncertain');const before=JSON.stringify(R.store.profile);assert(R.choose('ocd'));assert.equal(R.store.result.primaryRoute,'ocd');assert.equal(JSON.stringify(R.store.profile),before);assert.equal(R.start('anxiety'),'anxiety');assert.equal(R.start('ocd'),'ocd');assert.equal(R.start('mood'),'screen');});
test('not sure and something else do not force a route',()=>{reset();clearSafety();R.store.profile=R.empty();R.store.pending=true;for(const choice of ['other','unsure']){assert(R.choose(choice));assert.equal(R.store.result.primaryRoute,null);assert.equal(R.store.result.confidenceStatus,'insufficient');}});
test('complete Chinese mixed example preserves Mood and specific OCD patterns',()=>{const p=R.extract('最近脑子里总出现伤害家人的画面，我根本不想这么做，但特别害怕，所以一直检查刀有没有收好。最近心情也很差，对以前喜欢的事情也没兴趣。');for(const path of ['ocd.intrusiveThoughts','ocd.thoughtsUnwanted','ocd.egoDystonic','ocd.checking','mood.depressedMood','mood.anhedonia'])assert.equal(R.get(p,path),true,path);const r=R.route(p);assert.equal(r.primaryRoute,'ocd');assert(r.candidateRoutes.some(c=>c.domain==='mood'));});
test('language switching preserves router profile, route, safety and current page',()=>{reset();R.submit(scenarios[3][1]);G.acknowledge();R.resume();vm.runInContext("navigate('router')",c);const before=JSON.stringify([R.store,G.store]);for(let i=0;i<2;i++){vm.runInContext('switchLanguage()',c);assert.equal(JSON.stringify([R.store,G.store]),before);assert.equal(vm.runInContext('view',c),'router');assert(!markup.includes('ROUTER_'));assert(!markup.includes('undefined'));assert(markup.includes('data-router-start'));}});
test('bilingual clarification and unsupported/error rendering are complete',()=>{reset();clearSafety();for(const p of [R.empty(),R.extract('I have traumatic flashbacks.'),null]){R.store.profile=p;R.store.result=R.route(p);for(const l of [0,1]){vm.runInContext('lang='+l,c);const html=R.render();assert(!html.includes('undefined'));assert(!html.includes('router.heading'));if(l)assert(!/[\u3400-\u9fff]/.test(html));}}});
test('editing clears structured router state; invalid input cannot reuse earlier route',()=>{reset();R.submit(scenarios[0][1]);R.clear();assert.equal(R.store.profile,null);assert.equal(R.store.pending,false);for(const input of [null,'','x'.repeat(4001)])assert.throws(()=>R.extract(input));});
test('rules are deterministic versioned unreviewed and reference complete bilingual explanations',()=>{const p=R.extract(scenarios[3][1]);assert.deepEqual(copy(R.route(p)),copy(R.route(copy(p))));for(const rule of R.rules){assert.equal(rule.version,'symptom-router-v1.0.0');assert.equal(rule.reviewStatus,'unreviewed');assert.equal(c.I18n.pair(rule.explanationKey).length,2);}});
test('router source has no persistence, remote calls, analytics or raw-text store',()=>{const code=fs.readdirSync('src/router').filter(f=>f.endsWith('.js')).map(f=>fs.readFileSync('src/router/'+f,'utf8')).join('\n');assert(!/localStorage|sessionStorage|indexedDB|fetch\(|XMLHttpRequest|console\.(?:log|debug)|sendBeacon/.test(code));assert(!/store\.(?:raw|text|description)\s*=/.test(code));});
test('contradictory current observations stay unresolved across repeated mentions',()=>{const p=R.extract('I am depressed. I am not depressed. I am depressed.');assert.equal(p.mood.depressedMood,'unknown');assert.equal(R.route(p).primaryRoute,null);});
test('other-person repetition cannot inflate a self symptom duration rule',()=>{const p=R.extract('I feel depressed. My girlfriend repeatedly checks the door.');assert.equal(p.course.frequency,'unknown');assert.equal(R.route(p).primaryRoute,null);});
test('excessive observation count fails rather than silently truncating',()=>{assert.throws(()=>R.extract('panic attack.'.repeat(257)));});
fs.writeFileSync('work/router-test-results.json',JSON.stringify({passed:true,count},null,2));
