// Synthetic Mood/OCD clarification coverage; no patient data.
const assert=require('node:assert/strict'),c=require(process.cwd()+'/tests/router-v2-harness.cjs')(),{RouterV2:V,SymptomRouter:R,GlobalSafety:G}=c,rows=require(process.cwd()+'/benchmarks/router-v1/cases.cjs').filter(r=>r.pairId==='mixed-mood-ocd'),copy=x=>JSON.parse(JSON.stringify(x));
function test(name,fn){fn();console.log('PASS Mood OCD clarification '+name);}
const input=rows.find(r=>r.language==='en').text,base=()=>V.extract(input),shape=r=>copy(r.candidateRoutes.map(c=>({domain:c.domain,rank:c.rank}))),answer=value=>V.answer(base(),V.session(),'moodOcd',value);
for(const row of rows)test(row.id+' selects bilingual question',()=>{const r=V.evaluate(V.extract(row.text));assert.equal(r.clarification.id,'moodOcd');assert.equal(r.clarification.questionKey,'rv201.question');assert(c.I18n.t(r.clarification.questionKey,row.language));assert.equal(r.primaryRoute,null);});
for(const [value,domain,path,other]of [['mood','mood','mood.moodCongruentRumination','ocd.intrusionCompulsionLink'],['ocd','ocd','ocd.intrusionCompulsionLink','mood.moodCongruentRumination']])test(value+' increases supported discrimination without erasing the other domain',()=>{const a=answer(value),r=V.evaluate(a.profile,a.session),candidate=r.candidateRoutes.find(c=>c.domain===domain);assert.equal(a.profile.facts[path],true);assert.equal(a.profile.facts[other],'unknown');assert(candidate.discriminatingEvidence.some(e=>e.concept===path&&e.evidenceIds.length===1));assert(candidate.explanationKeys.includes(domain==='mood'?'rv201.reasonMood':'rv201.reasonOcd'));assert.deepEqual(shape(r),shape(V.evaluate(base())));assert.equal(r.primaryRoute,null);assert.equal(r.routingStatus,'ambiguous');assert.notEqual(r.clarification?.id,'moodOcd');});
test('both retains independently supported domains and both relationships',()=>{const a=answer('both'),r=V.evaluate(a.profile,a.session);assert.equal(a.profile.facts['mood.moodCongruentRumination'],true);assert.equal(a.profile.facts['ocd.intrusionCompulsionLink'],true);assert.equal(r.primaryRoute,null);assert.deepEqual(shape(r),shape(V.evaluate(base())));});
for(const value of ['unknown','prefer'])test(value+' adds no clinical evidence',()=>{const p=base(),a=V.answer(p,V.session(),'moodOcd',value);assert.deepEqual(copy(a.profile),copy(p));assert(a.session.stopped);assert.equal(V.evaluate(a.profile,a.session).clarification,null);});
test('Safety interrupts before answering',()=>{R.submit(input);G.acknowledge();R.resume();const before=copy(R.store.v2);G.answer('suicide.intent',true);assert.equal(V.respond('moodOcd','ocd'),false);assert.deepEqual(copy(R.store.v2),before);assert.equal(R.resume(),'safety');assert(!R.render().includes('data-v2-answer'));G.reset();});
for(const extra of ['I worry constantly about work and family and feel physically tense.','I keep reliving the assault and feel constantly on guard.'])test('three domains remain supported '+extra.length,()=>{const p=V.extract(input+'. '+extra),before=V.evaluate(p),a=V.answer(p,V.session(),'moodOcd','both'),after=V.evaluate(a.profile,a.session);assert.equal(before.candidateRoutes.length,3);assert.deepEqual(shape(after),shape(before));assert.equal(after.primaryRoute,null);assert.equal(after.routingStatus,'ambiguous');});
test('existing Mood Anxiety priority remains in three-domain case',()=>{const r=V.evaluate(V.extract(input+'. I worry constantly about work and family and feel physically tense.'));assert.equal(r.clarification.id,'moodAnxiety');});
test('new question uses final available slot and cannot bypass budget',()=>{const s=V.session();s.order=['moodAnxiety','ocdGad'];const p=base(),a=V.answer(p,s,'moodOcd','both'),r=V.evaluate(a.profile,a.session);assert.equal(a.session.order.length,3);assert.equal(r.stopReason,'question_limit');assert.equal(r.clarification,null);assert.throws(()=>V.answer(p,a.session,'ocdTrauma','memory'));});
test('question is not selected for one domain alone',()=>{for(const text of ['I feel depressed and have lost interest.','I keep having unwanted thoughts and repeatedly check the door.'])assert.notEqual(V.evaluate(V.extract(text)).clarification?.id,'moodOcd');});
for(const value of ['mood','ocd','both','unknown','prefer'])test('equivalent bilingual structured answer '+value,()=>{const a=rows.map(row=>V.answer(V.extract(row.text),V.session(),'moodOcd',value));assert.deepEqual(copy(a[0].profile.facts),copy(a[1].profile.facts));assert.deepEqual(shape(V.evaluate(a[0].profile,a[0].session)),shape(V.evaluate(a[1].profile,a[1].session)));});
test('presentation switching preserves clarification and clinical state',()=>{G.reset();R.submit(input);G.acknowledge();R.resume();const before=JSON.stringify([R.store,G.store,c.Differential.store]);c.lang=0;const zh=R.render();c.lang=1;const en=R.render();assert(zh.includes('反复出现的想法'));assert(en.includes('Which better describes'));assert.equal(JSON.stringify([R.store,G.store,c.Differential.store]),before);assert.equal(R.store.result.clarification.id,'moodOcd');});
test('new question is unreviewed and has exactly five answer semantics',()=>{const q=V.questions.find(q=>q.id==='moodOcd');assert.equal(q.reviewStatus,'unreviewed');assert.deepEqual(copy(q.options.map(o=>o.value)),['mood','ocd','both','unknown','prefer']);assert.equal(V.version,'symptom-router-v2.0.1');});
