const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const c={lang:0,esc:s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')};vm.createContext(c);
for(const m of fs.readFileSync('dist/index.html','utf8').matchAll(/<script src="([^"]+)"/g))if(m[1]!=='app.js')vm.runInContext(fs.readFileSync('dist/'+m[1],'utf8'),c);
const G=c.GlobalSafety,results=[];function test(name,fn){fn();results.push(name);console.log('PASS UX '+name);}
function known(){const s=G.empty();for(const p of G.critical)G.put(s,p,false);return s;}
const none=G.evaluate(known()),attention=G.evaluate(G.merge([known(),{suicide:{passiveDeathWish:true}}]).signals),incomplete=G.evaluate(G.empty()),failed=G.fromExtraction('not JSON').result,elevated=G.evaluate({selfHarm:{recentBehavior:true}}),suicide=G.evaluate({suicide:{intent:true}}),medical=G.evaluate({medical:{suspectedOverdose:true},suicide:{intent:true}}),ocd=G.evaluate({harmToOthers:{violentThoughts:true,thoughtsUnwanted:true,actualDesire:false,intent:false}});
for(const l of [0,1]){c.lang=l;const suffix=l?' EN':' ZH';
 test('normal entry is an ordinary assessment action'+suffix,()=>{const h=G.entryHTML();assert(h.includes(l?'Start assessment':'开始评估'));assert(h.includes(l?'I need urgent help now':'我现在需要紧急帮助'));assert(!h.includes('Check safety information first'));assert(h.includes('type="submit"'));assert(h.includes('data-view="urgent"'));assert(!h.includes('role="alert"'));assert(h.includes('aria-describedby="global-entry-help global-entry-privacy global-entry-error"'));});
 test('none has no crisis or compact interruption'+suffix,()=>{const h=G.panel(none);assert.equal(G.safetyPresentation(none).state,'none');assert.equal(G.panel(none,true),'');assert(h.includes('Continue')||h.includes('继续'));assert(!h.includes('role="alert"'));assert(!h.includes('global-followups'));});
 test('incomplete asks first and does not claim technical inability'+suffix,()=>{const h=G.panel(incomplete);assert(h.includes(l?'We need to clarify a few safety questions':'我们需要先确认你的安全状况'));assert(!h.includes(l?"We couldn't complete":'暂时无法完成'));assert(!h.includes('role="alert"'));assert(h.indexOf('global-followups')<h.indexOf('id="global-support"'));assert(h.includes('<details id="global-support">'));assert(!h.includes('<details id="global-support" open'));assert(h.includes('data-global="continue"'));});
 test('true unable_to_assess has failure wording and no ordinary Continue'+suffix,()=>{const h=G.panel(failed);assert(h.includes(l?"We couldn't complete the safety check":'暂时无法完成安全评估'));assert(h.includes('data-safety-ui="unable_to_assess"'));assert(!h.includes('data-global="continue"'));assert(!h.includes('global-followups'));assert(h.includes('data-global="reset"'));assert(h.indexOf(l?'Clear page answers and retry':'清除页面答案并重试')<h.indexOf('id="global-support"'));});
 test('attention is subtle information with support folded away'+suffix,()=>{const h=G.panel(attention);assert(h.includes('data-safety-ui="attention"'));assert(!h.includes('role="alert"'));assert(h.includes('<details id="global-support">'));assert(h.includes(l?'Worth following up':'值得留意'));});
 test('elevated prioritizes prompt support even with unresolved fields'+suffix,()=>{const h=G.panel(elevated);assert(h.includes(l?'Contact a professional promptly':'请尽快联系专业人员'));assert(h.includes('data-safety-ui="elevated"'));assert(!h.includes('role="alert"'));assert(h.indexOf('class="global-support"')<h.indexOf('global-followups'));assert(h.includes('data-global="continue"'));});
 test('acute suicide interrupts and prioritizes one emergency contact'+suffix,()=>{G.store.region='ca';const h=G.panel(suicide);assert.equal((h.match(/role="alert"/g)||[]).length,1);assert(!h.includes('data-global="continue"'));assert(!h.includes('global-followups'));assert(h.includes('class="primary" href="tel:911"'));assert(h.includes('class="secondary" href="tel:988"'));assert.equal((h.match(/<a class="primary"/g)||[]).length,1);});
 test('acute medical action preserves secondary suicide internally'+suffix,()=>{const before=JSON.stringify(medical),h=G.panel(medical);assert(h.includes(l?'Seek emergency medical help first':'先获得紧急医疗帮助'));assert(!h.includes('href="tel:988"'));assert(!h.includes('data-global="continue"'));assert(medical.domains.includes('suicide'));assert.equal(JSON.stringify(medical),before);});
 test('intrusive OCD thought receives clarification, not emergency styling'+suffix,()=>{const h=G.panel(ocd);assert(h.includes('global-intrusive'));assert(!h.includes('role="alert"'));assert(!h.includes('global-safety acute'));assert(h.includes(l?'not the same as actual intent':'不等于实际意图'));assert(h.includes('<details id="global-support">'));});
 test('explicit urgent-help request shows contacts without inventing urgency'+suffix,()=>{const before=JSON.stringify(incomplete),h=G.panel(incomplete,false,{urgentRequest:true});assert(h.includes(l?'Get urgent help now':'现在获取紧急帮助'));assert(h.includes('class="global-support"'));assert(!h.includes('global-followups'));assert(!h.includes('role="alert"'));assert.equal(JSON.stringify(incomplete),before);});
 test('questions have direct labels and all three response semantics'+suffix,()=>{const h=G.panel(incomplete);for(const p of incomplete.followup){const id='global-answer-'+p.replaceAll('.','-');assert(h.includes('label for="'+id+'"'));assert(h.includes('id="'+id+'"'));assert(h.includes(G.questionLabels[p][l]));}assert(h.includes('value="yes"'));assert(h.includes('value="no"'));assert(h.includes('value="unknown"'));assert(h.includes('aria-describedby="global-answer-help"'));assert.equal((h.match(/<h1 /g)||[]).length,1);});
}
test('bilingual presentation and urgent help never mutate core results',()=>{for(const r of [none,incomplete,failed,attention,elevated,suicide,medical,ocd]){const before=JSON.stringify(r);for(const l of [0,1]){c.lang=l;assert(!G.panel(r).includes('undefined'));G.panel(r,false,{urgentRequest:true});}assert.equal(JSON.stringify(r),before);}});
test('focus moves to next question when the previous answer removes a field',()=>{let focused='';const next={focus(){focused='next';}},panel={getAttribute:()=> 'incomplete'};c.document={getElementById:()=>null,querySelector:s=>s==='[data-safety-ui]'?panel:s==='[data-global-answer]'?next:null};G.restoreUI({focus:'global-answer-suicide-intent',scope:'incomplete',open:[]});assert.equal(focused,'next');});
test('acute transition focuses emergency heading instead of a stale control',()=>{let focused='';const heading={focus(){focused='heading';}},panel={getAttribute:()=> 'acute'};c.document={getElementById:id=>id==='global-safety-heading'?heading:null,querySelector:()=>panel};G.restoreUI({focus:'global-answer-suicide-intent',scope:'incomplete',open:[]});assert.equal(focused,'heading');});
test('language redraw retains draft, region disclosure and keyboard focus without engine storage',()=>{let focused='';const draft={value:''},region={focus(){focused='region';}},details={open:false};c.document={getElementById:id=>({'global-description':draft,'global-region':region,'global-support':details}[id]),querySelector:()=>null};G.restoreUI({draft:'synthetic-draft-marker',focus:'global-region',scope:undefined,open:['global-support']});assert.equal(draft.value,'synthetic-draft-marker');assert(details.open);assert.equal(focused,'region');assert(!JSON.stringify(G.store).includes('synthetic-draft-marker'));});
test('blank entry uses an input error rather than a false technical failure',()=>{G.reset();let focus=false;const input={value:'   ',setAttribute(){},focus(){focus=true;}},error={},form={};c.document={getElementById:id=>({'global-description':input,'global-entry-error':error,'global-entry-form':form}[id]),querySelectorAll:()=>[]};G.bind();let prevented=false;form.onsubmit({preventDefault(){prevented=true;}});assert(prevented&&focus);assert.equal(G.store.failed,false);assert(error.textContent);});
test('mobile and keyboard styles retain visible focus and large wrapping targets',()=>{const css=fs.readFileSync('dist/safety/safety.css','utf8');assert(css.includes('@media(max-width:600px)'));assert(css.includes('min-height:48px'));assert(css.includes('white-space:normal'));assert(css.includes('overflow-wrap:anywhere'));assert(css.includes('summary):focus-visible'));assert(css.includes('outline:3px solid #174c91'));for(const state of ['incomplete','attention','elevated','acute','unable_to_assess','none'])assert(css.includes('.'+state));assert(!/tabindex="[1-9]/.test(fs.readFileSync('dist/safety/ui.js','utf8')));});
function luminance(hex){const a=hex.replace('#','').match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return a[0]*.2126+a[1]*.7152+a[2]*.0722;}
test('safety text and buttons meet 4.5:1 contrast; focus indicator meets 3:1',()=>{for(const [fg,bg]of [['#253d36','#ffffff'],['#4e6358','#ffffff'],['#795213','#fff9ea'],['#385670','#f3f7fb'],['#892d20','#fff5f1'],['#ffffff','#286450'],['#ffffff','#963526']]){const a=luminance(fg),b=luminance(bg);assert((Math.max(a,b)+.05)/(Math.min(a,b)+.05)>=4.5,fg+' on '+bg);}assert((luminance('#ffffff')+.05)/(luminance('#174c91')+.05)>=3);});
test('six core files unchanged; extraction differs only by the documented bilingual bug fix',()=>{const baseline=JSON.parse(fs.readFileSync('tests/fixtures/safety-core-hashes.json','utf8').replace(/^\uFEFF/,''));assert.equal(baseline.length,7);for(const f of baseline){const name=f.Path.split(/[\\/]/).pop();assert.equal(crypto.createHash('sha256').update(originalCoreBytes(name)).digest('hex').toUpperCase(),f.Hash,name);}});
fs.writeFileSync('work/safety-ux-test-results.json',JSON.stringify({passed:results.length,tests:results},null,2));

function originalCoreBytes(name){const bytes=fs.readFileSync('dist/safety/'+name);if(name!=='extraction.js')return bytes;let code=bytes.toString('utf8');for(const change of JSON.parse(fs.readFileSync('tests/fixtures/extraction-i18n-patch.json','utf8')).changes){assert.equal(code.split(change.after).length,2);code=code.replace(change.after,change.before);}return Buffer.from(code);}
