const assert=require('node:assert/strict'),fs=require('fs');const boot=require(process.cwd()+'/tests/differential-v2-harness.cjs');let count=0;function test(name,fn){fn();count++;console.log('PASS Safety consistency '+name);}
function completed(){const c=boot(),M=c.Mood;c.view='screen';c.render=()=>{};for(const q of M.questions){if(q.optional||!M.visible(q,M.store.state))continue;const v=q.options.find(x=>x[0]==='no')?.[0]??q.options.find(x=>x[0]==='0')?.[0]??q.options.find(x=>x[0]==='none')?.[0]??q.options[0][0];M.update(q.id,v);}M.update('intro.age','yes');M.update('intro.agree','yes');M.store.step=11;M.store.maxStep=11;assert.equal(M.missing(M.store.state).length,0);return c;}
function resolved(c){for(const p of c.GlobalSafety.critical)c.GlobalSafety.answer(p,false);assert.equal(c.GlobalSafety.current().assessmentStatus,'assessed');}
test('completed Mood can genuinely leave global critical questions unanswered',()=>{const c=completed(),G=c.GlobalSafety,r=G.current();assert.equal(r.assessmentStatus,'incomplete');assert(r.unresolvedCriticalSignals.length);assert(c.Mood.render().includes('data-result-safety="incomplete"'));for(const p of r.unresolvedCriticalSignals)assert(c.Mood.render().includes(c.I18n.text(G.questionLabels[p],c.lang)));assert.equal(G.current().assessmentStatus,'incomplete');});
for(const lang of [0,1])test('resolved current global status replaces stale cached local warning '+lang,()=>{const c=completed(),M=c.Mood,G=c.GlobalSafety;c.lang=lang;M.store.result=M.assess(M.store.state);assert.equal(M.store.result.safety.assessmentStatus,'incomplete');resolved(c);c.I18n.presentationOnly=true;const html=M.render();assert(html.includes('data-result-safety="none"'));assert(!html.includes(G.safetyPresentation(M.store.result.safety).title));assert.equal(M.safetyHTML(M.store.result),'');assert.equal(M.store.result.safety.assessmentStatus,'incomplete');});
test('other-module acute evidence overrides Mood local result',()=>{const c=completed();resolved(c);c.Anxiety.store.state.revision=1;c.Anxiety.store.state.safetySignals=c.GlobalSafety.empty();c.GlobalSafety.put(c.Anxiety.store.state.safetySignals,'medical.otherImmediateMedicalDanger',true);assert(!c.Mood.safety(c.Mood.store.state).requiresInterruption);assert(c.GlobalSafety.current().requiresInterruption);const html=c.Mood.render();assert(!html.includes('consumer-result'));assert(!html.includes('data-mood="next"'));assert(html.includes('data-safety-ui="acute"'));});
test('unable-to-assess hides ordinary result without treating failure as incomplete',()=>{const c=completed();resolved(c);c.GlobalSafety.store.failed=true;const html=c.Mood.render();assert(html.includes('data-safety-ui="unable_to_assess"'));assert(!html.includes('consumer-result'));assert.equal(c.GlobalSafety.finishResultClarification(),false);});
test('elevated state preserves support and unanswered critical questions',()=>{const c=completed(),G=c.GlobalSafety;G.answer('selfCare.unableToMaintainShelter',true);const r=G.current();assert.equal(r.urgency,'elevated');assert(c.Mood.render().includes('data-result-safety="elevated"'));assert(G.clarificationPaths(r).length);});
test('clarification completion returns to exact result step without answer loss',()=>{const c=completed(),G=c.GlobalSafety,M=c.Mood;const state=JSON.stringify(M.store.state);assert.equal(G.beginResultClarification(),'safety');assert.equal(G.finishResultClarification(),false);assert.equal(G.current().assessmentStatus,'incomplete');resolved(c);assert.equal(G.finishResultClarification(),'screen');assert.equal(M.store.step,11);assert.equal(JSON.stringify(M.store.state),state);});
test('actual Continue stays in clarification when unknown and resumes only after assessment',()=>{const c=completed(),G=c.GlobalSafety;G.beginResultClarification();c.view='safety';let target=null;c.navigate=v=>target=v;const button={dataset:{global:'continue'}};c.document={querySelector:()=>null,getElementById:()=>null,querySelectorAll:q=>q==='[data-global]'?[button]:[]};G.bind();button.onclick();assert.equal(target,null);resolved(c);button.onclick();assert.equal(target,'screen');});
test('accidental answer corrected from original source preserves step and other answers',()=>{const c=completed(),M=c.Mood,G=c.GlobalSafety;resolved(c);const phq=JSON.stringify(M.store.state.phq);M.update('safety.intent','yes');assert(G.current().requiresInterruption);assert.equal(G.resumeCorrection(),false);G.correct('no');assert.equal(G.resumeCorrection(),'screen');assert.equal(M.store.step,11);assert.equal(JSON.stringify(M.store.state.phq),phq);});
test('correcting one acute indicator never clears independent medical danger',()=>{const c=completed(),G=c.GlobalSafety;resolved(c);c.Mood.update('safety.intent','yes');G.answer('medical.otherImmediateMedicalDanger',true);G.correct('no');assert(G.current().requiresInterruption);assert.equal(G.resumeCorrection(),false);assert(!c.Mood.render().includes('consumer-result'));});
test('acute event inside clarification returns to saved assessment only after correction',()=>{const c=completed(),G=c.GlobalSafety;resolved(c);G.beginResultClarification();c.view='safety';G.answer('suicide.intent',true);assert.equal(G.finishResultClarification(),false);G.correct('no');assert.equal(G.resumeCorrection(),'screen');assert.equal(c.Mood.store.step,11);});
test('exploratory output is collapsed and not used as a diagnostic headline',()=>{const c=completed();resolved(c);const html=c.Mood.render();assert(html.includes('<details class="mood-technical">'));assert(!html.includes('mood-technical" open'));for(const l of [0,1]){c.lang=l;const out=c.Mood.render();assert(out.includes(c.I18n.t('safetyResult.technical',l)));assert(out.includes(c.I18n.t('moodExplain.limitation',l)));}});
test('score and qualified predicate remain unchanged',()=>{const c=completed(),M=c.Mood;for(let i=0;i<5;i++){M.update('phq.'+i,'1');for(const [k,v]of Object.entries({duration:'14to29',changed:'yes'}))M.update('symptoms.'+M.phqDomainMap[i]+'.'+k,v);}let r=M.assess(M.store.state);assert.equal(r.phq.total,5);assert.equal(r.qualified.length,0);M.update('phq.0','3');M.update('symptoms.interest.duration','14to29');M.update('symptoms.interest.changed','yes');r=M.assess(M.store.state);assert.equal(r.phq.total,7);assert.deepEqual([...r.qualified],['interest']);});
test('summary presentation uses live safety without changing the assessment snapshot',()=>{const c=completed(),M=c.Mood,G=c.GlobalSafety,r=M.assess(M.store.state);resolved(c);const out=M.summary(M.store.state,r,1,G.current());assert(out.includes(c.I18n.t('platform.m_9db5e4dd5753',1)));assert.equal(r.safety.assessmentStatus,'incomplete');});
test('fresh Mood-local unknowns do not contradict resolved shared evidence from another module',()=>{const c=completed(),G=c.GlobalSafety;c.Anxiety.store.state.revision=1;c.Anxiety.store.state.safetySignals=G.empty();for(const path of G.critical)G.put(c.Anxiety.store.state.safetySignals,path,false);assert.equal(c.Mood.safety(c.Mood.store.state).assessmentStatus,'incomplete');assert.equal(G.current().assessmentStatus,'assessed');assert(c.Mood.render().includes('data-result-safety="none"'));});
fs.writeFileSync('work/safety-consistency-results.json',JSON.stringify({passed:true,count},null,2));

