(function(V,D){'use strict';
const statusKeys={sufficient:'dv2.sufficient',partially_sufficient:'dv2.partial',insufficient:'dv2.insufficient',conflicted:'dv2.conflicted',safety_interrupted:'dv2.safety'};
const sourceKeys={free_text_extraction:'dv2.extracted',standardized_screener:'dv2.screening',structured_assessment:'dv2.assessment',functional_impairment:'dv2.function',duration:'dv2.course',exclusion:'dv2.exclusion',developmental_history:'dv2.development',user_clarification:'dv2.clarification',safety_clarification:'dv2.safetySource'};
const timeKeys={current:'dv2.current',history:'dv2.history',episodic:'dv2.episodic',unknown:'dv2.unknownTime',hypothetical:'dv2.hypothetical'};
const levelKeys={strong:'differential.strong',supported:'differential.supported',weak:'differential.weak',insufficient:'differential.insufficientLabel'};
const stateKeys={insufficient:'dv2.needEvidence',still_discriminating:'dv2.stillDiscriminating',reasonably_saturated:'dv2.saturated'};
const text=(key,l=lang)=>I18n.t(key,l),escape=value=>esc(String(value)),label=(id,l)=>text(D.directions[id].label,l);
const concept=(id,l)=>V.concepts[id]?text(V.concepts[id],l):D.describe(id,l);
const reason=(r,l)=>text(r.key,l)+(r.concepts.length?' — '+r.concepts.map(k=>concept(k,l)).join('; '):'');
const source=(n,l)=>text(SymptomRouter.domains.get(n.source)?.label||({router:'dv2.routerSource',clarification:'dv2.clarification',safety:'dv2.safetySource'})[n.source],l);
V.describeObservations=(r,l)=>r.evidenceGraph?.nodes.filter(n=>Object.hasOwn(V.valueOptions,n.concept)).map(n=>{const contract=V.observationContracts.find(o=>o.concept===n.concept),q=D.modules()[contract.domain].questions.find(q=>q.id===contract.questionId),option=q.options.find(o=>o[0]===n.value);return source(n,l)+' — '+I18n.text(q.label,l)+': '+(option?I18n.text(option.slice(1),l):text('differential.unknown',l));})||[];
V.summary=function(r,l=0){
 if(r.blocked||D.gate().show)return text('differential.safetyFirst',l);
 const section=(key,values)=>[text(key,l),...(values.length?values:[text('differential.noneIdentified',l)])];
 return [text('differential.heading',l),text('differential.disclaimer',l),text(statusKeys[r.differentialStatus],l),...section('differential.primary',r.primaryDirections.map(id=>label(id,l))),...section('differential.cooccurring',(r.possibleCooccurringPatterns||[]).map(p=>p.directions.map(id=>label(id,l)).join(' + '))),...section('dv2.alternatives',r.alternatives.map(id=>label(id,l))),...r.candidateDirections.filter(d=>d.level).flatMap(d=>[label(d.id,l)+' — '+text(levelKeys[d.consistency],l),...section('differential.supporting',d.supportingEvidence.map(x=>reason(x,l))),...section('differential.opposing',d.opposingEvidence.map(x=>reason(x,l))),...section('differential.discriminating',d.discriminatingEvidence.map(x=>reason(x,l))),...section('dv2.provenance',d.provenanceSummary.map(n=>concept(n.concept,l)+' — '+source(n,l)+' · '+text(sourceKeys[n.sourceType],l)+' · '+text(timeKeys[n.temporality],l)))]),...section('dv2.context',V.describeObservations(r,l)),...section('differential.contradictions',r.contradictions.map(x=>concept(x.concept,l)+' — '+text(x.resolved?'dv2.resolved':'dv2.unresolved',l))),...section('differential.missing',r.missingEvidence.map(k=>concept(k,l))),...section('differential.ruleouts',r.unresolvedRuleOuts.map(k=>concept(k,l))),...section('dv2.uncertain',r.unresolvedDiscriminators.map(d=>concept(d.conceptNeeded,l)+' — '+text(d.reason,l))),...section('differential.unsupported',r.unsupportedAlternatives.map(k=>concept(k,l))),text(stateKeys[r.evidenceState],l),text('differential.safetyState',l)+': '+text(({none:'differential.safetyNone',attention:'differential.safetyAttention',elevated:'differential.safetyElevated',acute:'differential.safetyAcute'})[r.safetyState.urgency],l),text('dv2.version',l)+': '+V.version,text('dv2.review',l)].join('\n');
};
V.render=function(){
 if(D.gate().show)return GlobalSafety.panel(GlobalSafety.current());
 const r=V.current();if(r.blocked)return GlobalSafety.panel(GlobalSafety.current());
 const msg=key=>escape(text(key)),list=items=>items.length?'<ul>'+items.map(x=>'<li>'+escape(x)+'</li>').join('')+'</ul>':'<p class="muted">'+msg('differential.noneIdentified')+'</p>',names=ids=>list(ids.map(id=>label(id,lang)));
 const provenance=d=>list(d.provenanceSummary.map(n=>concept(n.concept,lang)+' — '+source(n,lang)+' · '+text(sourceKeys[n.sourceType])+' · '+text(timeKeys[n.temporality])));
 return `<section class="page differential-page differential-v2" aria-labelledby="differential-heading"><h1 id="differential-heading" tabindex="-1">${msg('dv2.heading')}</h1><p>${msg('differential.disclaimer')}</p><p role="status">${msg(statusKeys[r.differentialStatus])}</p><details><summary>${msg('differential.selection')}</summary><div class="dv2-sources">${Object.keys(D.store.selected).map(id=>`<label><input type="checkbox" data-diff-source="${id}" ${D.store.selected[id]?'checked':''}>${escape(text(id==='router'?'dv2.routerSource':SymptomRouter.domains.get(id).label))}</label>`).join('')}</div></details><h2>${msg('differential.primary')}</h2>${names(r.primaryDirections)}${r.primaryDirections.length>1?'<p>'+msg('dv2.multiple')+'</p>':''}${r.cooccurringDirections.length?'<h2>'+msg('differential.cooccurring')+'</h2>'+names(r.cooccurringDirections):''}${r.alternatives.length?'<details><summary>'+msg('dv2.alternatives')+'</summary>'+names(r.alternatives)+'</details>':''}<h2>${msg('differential.why')}</h2>${r.candidateDirections.filter(d=>d.level).map(d=>`<article class="panel"><h3>${escape(label(d.id,lang))} · ${msg(levelKeys[d.consistency])}</h3>${list(d.supportingEvidence.map(x=>reason(x,lang)))}<details><summary>${msg('differential.details')}</summary><h4>${msg('differential.opposing')}</h4>${list(d.opposingEvidence.map(x=>reason(x,lang)))}<h4>${msg('differential.discriminating')}</h4>${list(d.discriminatingEvidence.map(x=>reason(x,lang)))}<h4>${msg('dv2.provenance')}</h4>${provenance(d)}</details></article>`).join('')}<details><summary>${msg('dv2.context')}</summary>${list(V.describeObservations(r,lang))}</details><section aria-labelledby="dv2-uncertain"><h2 id="dv2-uncertain">${msg('dv2.uncertain')}</h2><p>${msg('dv2.unknownHelp')}</p>${list(r.unresolvedDiscriminators.map(d=>concept(d.conceptNeeded,lang)+' — '+text(d.reason)+(d.alreadyAsked?' '+text('dv2.alreadyAsked'):'')))}<h3>${msg('differential.missing')}</h3>${list(r.missingEvidence.map(k=>concept(k,lang)))}<h3>${msg('differential.ruleouts')}</h3>${list(r.unresolvedRuleOuts.map(k=>concept(k,lang)))}</section>${r.contradictions.length?'<section><h2>'+msg('differential.contradictions')+'</h2>'+list(r.contradictions.map(x=>concept(x.concept,lang)+' — '+text(x.resolved?'dv2.resolved':'dv2.unresolved')))+'</section>':''}${r.unsupportedAlternatives.length?'<h2>'+msg('differential.unsupported')+'</h2>'+list(r.unsupportedAlternatives.map(k=>concept(k,lang))):''}<p>${msg(stateKeys[r.evidenceState])}</p><p>${msg('dv2.review')}</p><details><summary>${msg('differential.summary')}</summary><textarea readonly rows="16" aria-label="${msg('differential.summary')}">${escape(V.summary(r,lang))}</textarea></details><div class="actions"><button class="secondary" data-view="library">${msg('differential.return')}</button><button class="secondary" data-diff-clear>${msg('differential.clear')}</button></div></section>`;
};
})(globalThis.DifferentialV2,globalThis.Differential);
