(function(D){'use strict';
D.version='cross-disorder-differential-v1.0.0';
D.concepts={
 'ocd.intrusive':'differential.intrusive','ocd.ego':'differential.ego','ocd.rituals':'differential.rituals','ocd.relief':'differential.relief','ocd.response':'differential.response','ocd.impact':'differential.ocdImpact','ocd.timeKnown':'differential.timeKnown',
 'mood.low':'differential.low','mood.interest':'differential.interest','mood.energy':'differential.energy','mood.worth':'differential.worth','mood.sleep':'differential.sleep','mood.duration':'differential.moodDuration','mood.together':'differential.together','mood.impact':'differential.moodImpact','mood.chronic':'differential.chronic','mood.activation':'differential.activation','mood.bipolarKnown':'differential.bipolarKnown','mood.contextSymptoms':'differential.contextMood','mood.rumination':'differential.rumination',
 'anxiety.broad':'differential.broad','anxiety.excessive':'differential.excessive','anxiety.control':'differential.control','anxiety.mostDays':'differential.mostDays','anxiety.tension':'differential.tension','anxiety.duration':'differential.anxietyDuration','anxiety.impact':'differential.anxietyImpact','anxiety.panic':'differential.panic','anxiety.panicDuration':'differential.panicDuration','anxiety.panicImpact':'differential.panicImpact','anxiety.social':'differential.social','anxiety.specific':'differential.specific','anxiety.agora':'differential.agora','anxiety.separation':'differential.separation','anxiety.onlyObsessions':'differential.onlyObsessions',
 'mood.medical':'differential.medical','mood.substance':'differential.substance','mood.stressor':'differential.stressor','anxiety.medical':'differential.medical','anxiety.substance':'differential.substance','ocd.medical':'differential.medical','ocd.substance':'differential.substance',
 'screen.mood':'differential.moodScreen','screen.anxiety':'differential.anxietyScreen',
 'unsupported.trauma':'differential.trauma','unsupported.attention':'differential.attention','unsupported.eating':'differential.eating','unsupported.psychotic':'differential.psychotic','unsupported.other':'differential.otherCategory'
};
D.sourceRanks={free_text_extraction:1,standardized_screener:2,structured_assessment:3,functional_impairment:3,duration:3,exclusion:3,user_clarification:4};
D.validEvidence=e=>!!e&&typeof e==='object'&&Object.keys(e).length===10&&typeof e.id==='string'&&/^[a-z0-9_.:-]{1,160}$/i.test(e.id)&&Object.hasOwn(D.concepts,e.concept)&&['mood','anxiety','ocd','router','clarification'].includes(e.sourceModule)&&['mood','anxiety','ocd','screen','unsupported'].includes(e.domain)&&e.domain===e.concept.split('.')[0]&&Object.hasOwn(D.sourceRanks,e.sourceType)&&[true,false,'unknown'].includes(e.value)&&['current','history','unknown'].includes(e.temporality)&&['reported','unknown'].includes(e.certainty)&&e.certainty===(e.value==='unknown'?'unknown':'reported')&&['context','discriminating'].includes(e.relevance)&&e.provenance&&Object.keys(e.provenance).length===3&&Number.isInteger(e.provenance.revision)&&e.provenance.revision>=0&&typeof e.provenance.engineVersion==='string'&&e.provenance.engineVersion.length<100&&Array.isArray(e.provenance.questionIds)&&e.provenance.questionIds.length<=100&&e.provenance.questionIds.every(id=>typeof id==='string'&&/^[a-z0-9_.:-]{1,100}$/i.test(id));
D.fact=(concept,value,sourceModule,questionIds,revision=0,sourceType='structured_assessment',temporality='current',engineVersion=D.version)=>({id:sourceModule+':'+concept,domain:concept.split('.')[0],concept,value,sourceModule,sourceType,temporality,certainty:value==='unknown'?'unknown':'reported',relevance:sourceType==='free_text_extraction'||sourceType==='standardized_screener'?'context':'discriminating',provenance:{questionIds,revision,engineVersion}});
D.truth=v=>v==='yes'?true:v==='no'?false:'unknown';
D.any=values=>values.some(v=>v===true)?true:values.length&&values.every(v=>v===false)?false:'unknown';
D.all=values=>values.some(v=>v===false)?false:values.length&&values.every(v=>v===true)?true:'unknown';
})(globalThis.Differential=globalThis.Differential||{});
