// Product availability metadata only. Never input to clinical engines.
(function(C){'use strict';
C.version='assessment-availability-ui-v1.0.0';
C.badgeKeys=Object.freeze({FULL_ASSESSMENT:'capability.full',ASSESSMENT_PATHWAY:'capability.pathway',KNOWLEDGE_ONLY:'capability.knowledge',DIFFERENTIAL_OR_NAVIGATION:'capability.navigation',MEDICAL_OR_SAFETY_NAVIGATION:'capability.medical'});
C.domainKeys=Object.freeze({mood:'capability.mood',anxiety:'capability.anxiety',ocd:'capability.ocd',trauma:'capability.trauma',adhd:'capability.adhd',eating:'capability.eating',psychosis:'capability.psychosis'});
C.topics=Object.freeze([
  {
    "topicId": "depression",
    "topicIndex": 0,
    "titleKey": "platform.m_5225c9865424",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": true,
    "assessmentDomain": "mood",
    "assessmentPathway": null,
    "routerSupported": true,
    "differentialSupported": true,
    "adaptiveSupported": true,
    "safetyRelevant": true,
    "capabilityType": "FULL_ASSESSMENT",
    "assessmentRoute": "screen",
    "explanationKey": "capability.fullHelp"
  },
  {
    "topicId": "bipolar",
    "topicIndex": 1,
    "titleKey": "platform.m_81685a246191",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": false,
    "assessmentDomain": "mood",
    "assessmentPathway": "bipolar",
    "routerSupported": true,
    "differentialSupported": true,
    "adaptiveSupported": true,
    "safetyRelevant": true,
    "capabilityType": "ASSESSMENT_PATHWAY",
    "assessmentRoute": "screen",
    "explanationKey": "capability.bipolarHelp"
  },
  {
    "topicId": "gad",
    "topicIndex": 2,
    "titleKey": "platform.m_e21b7383cdca",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": true,
    "assessmentDomain": "anxiety",
    "assessmentPathway": null,
    "routerSupported": true,
    "differentialSupported": true,
    "adaptiveSupported": true,
    "safetyRelevant": true,
    "capabilityType": "FULL_ASSESSMENT",
    "assessmentRoute": "anxiety",
    "explanationKey": "capability.fullHelp"
  },
  {
    "topicId": "panic",
    "topicIndex": 3,
    "titleKey": "platform.m_86eac9fc8505",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": false,
    "assessmentDomain": "anxiety",
    "assessmentPathway": "panic",
    "routerSupported": true,
    "differentialSupported": true,
    "adaptiveSupported": true,
    "safetyRelevant": true,
    "capabilityType": "ASSESSMENT_PATHWAY",
    "assessmentRoute": "anxiety",
    "explanationKey": "capability.anxietyHelp"
  },
  {
    "topicId": "social-anxiety",
    "topicIndex": 4,
    "titleKey": "platform.m_bf28edd8b266",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": false,
    "assessmentDomain": "anxiety",
    "assessmentPathway": "social-anxiety",
    "routerSupported": true,
    "differentialSupported": true,
    "adaptiveSupported": true,
    "safetyRelevant": true,
    "capabilityType": "ASSESSMENT_PATHWAY",
    "assessmentRoute": "anxiety",
    "explanationKey": "capability.anxietyHelp"
  },
  {
    "topicId": "ocd",
    "topicIndex": 5,
    "titleKey": "platform.m_8b0eb8e13e98",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": true,
    "assessmentDomain": "ocd",
    "assessmentPathway": null,
    "routerSupported": true,
    "differentialSupported": true,
    "adaptiveSupported": true,
    "safetyRelevant": true,
    "capabilityType": "FULL_ASSESSMENT",
    "assessmentRoute": "ocd",
    "explanationKey": "capability.fullHelp"
  },
  {
    "topicId": "body-dysmorphia-hoarding",
    "topicIndex": 6,
    "titleKey": "platform.m_74cce6dec778",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": false,
    "assessmentDomain": null,
    "assessmentPathway": null,
    "routerSupported": false,
    "differentialSupported": false,
    "adaptiveSupported": false,
    "safetyRelevant": true,
    "capabilityType": "DIFFERENTIAL_OR_NAVIGATION",
    "assessmentRoute": null,
    "explanationKey": "capability.ocdRelatedHelp"
  },
  {
    "topicId": "ptsd",
    "topicIndex": 7,
    "titleKey": "platform.m_f6a6d5a22aef",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": true,
    "assessmentDomain": "trauma",
    "assessmentPathway": null,
    "routerSupported": true,
    "differentialSupported": true,
    "adaptiveSupported": true,
    "safetyRelevant": true,
    "capabilityType": "FULL_ASSESSMENT",
    "assessmentRoute": "trauma",
    "explanationKey": "capability.fullHelp"
  },
  {
    "topicId": "adjustment-grief",
    "topicIndex": 8,
    "titleKey": "platform.m_33421a6d1acc",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": false,
    "assessmentDomain": null,
    "assessmentPathway": null,
    "routerSupported": false,
    "differentialSupported": false,
    "adaptiveSupported": false,
    "safetyRelevant": true,
    "capabilityType": "DIFFERENTIAL_OR_NAVIGATION",
    "assessmentRoute": null,
    "explanationKey": "capability.adjustmentHelp"
  },
  {
    "topicId": "psychosis",
    "topicIndex": 9,
    "titleKey": "platform.m_0a03b5e5fcff",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": true,
    "assessmentDomain": "psychosis",
    "assessmentPathway": null,
    "routerSupported": true,
    "differentialSupported": true,
    "adaptiveSupported": true,
    "safetyRelevant": true,
    "capabilityType": "FULL_ASSESSMENT",
    "assessmentRoute": "psychosis",
    "explanationKey": "capability.fullHelp"
  },
  {
    "topicId": "adhd",
    "topicIndex": 10,
    "titleKey": "platform.m_ab03d880bd6d",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": true,
    "assessmentDomain": "adhd",
    "assessmentPathway": null,
    "routerSupported": true,
    "differentialSupported": true,
    "adaptiveSupported": true,
    "safetyRelevant": true,
    "capabilityType": "FULL_ASSESSMENT",
    "assessmentRoute": "adhd",
    "explanationKey": "capability.fullHelp"
  },
  {
    "topicId": "autism",
    "topicIndex": 11,
    "titleKey": "platform.m_5813b810efd4",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": false,
    "assessmentDomain": null,
    "assessmentPathway": null,
    "routerSupported": false,
    "differentialSupported": false,
    "adaptiveSupported": false,
    "safetyRelevant": true,
    "capabilityType": "KNOWLEDGE_ONLY",
    "assessmentRoute": null,
    "explanationKey": "capability.autismHelp"
  },
  {
    "topicId": "eating",
    "topicIndex": 12,
    "titleKey": "platform.m_d1875dccd9fa",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": true,
    "assessmentDomain": "eating",
    "assessmentPathway": null,
    "routerSupported": true,
    "differentialSupported": true,
    "adaptiveSupported": true,
    "safetyRelevant": true,
    "capabilityType": "FULL_ASSESSMENT",
    "assessmentRoute": "eating",
    "explanationKey": "capability.fullHelp"
  },
  {
    "topicId": "somatic",
    "topicIndex": 13,
    "titleKey": "platform.m_cbaee6ed6b5e",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": false,
    "assessmentDomain": null,
    "assessmentPathway": null,
    "routerSupported": false,
    "differentialSupported": false,
    "adaptiveSupported": false,
    "safetyRelevant": true,
    "capabilityType": "DIFFERENTIAL_OR_NAVIGATION",
    "assessmentRoute": null,
    "explanationKey": "capability.somaticHelp"
  },
  {
    "topicId": "sleep",
    "topicIndex": 14,
    "titleKey": "platform.m_e59c924e7d42",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": false,
    "assessmentDomain": null,
    "assessmentPathway": null,
    "routerSupported": false,
    "differentialSupported": false,
    "adaptiveSupported": false,
    "safetyRelevant": true,
    "capabilityType": "DIFFERENTIAL_OR_NAVIGATION",
    "assessmentRoute": null,
    "explanationKey": "capability.sleepHelp"
  },
  {
    "topicId": "substance",
    "topicIndex": 15,
    "titleKey": "platform.m_e534a0ad0817",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": false,
    "assessmentDomain": null,
    "assessmentPathway": null,
    "routerSupported": false,
    "differentialSupported": false,
    "adaptiveSupported": false,
    "safetyRelevant": true,
    "capabilityType": "MEDICAL_OR_SAFETY_NAVIGATION",
    "assessmentRoute": null,
    "explanationKey": "capability.substanceHelp"
  },
  {
    "topicId": "personality",
    "topicIndex": 16,
    "titleKey": "platform.m_e05783a5fe86",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": false,
    "assessmentDomain": null,
    "assessmentPathway": null,
    "routerSupported": false,
    "differentialSupported": false,
    "adaptiveSupported": false,
    "safetyRelevant": true,
    "capabilityType": "KNOWLEDGE_ONLY",
    "assessmentRoute": null,
    "explanationKey": "capability.personalityHelp"
  },
  {
    "topicId": "cognitive",
    "topicIndex": 17,
    "titleKey": "platform.m_3849f19b5489",
    "knowledgeAvailable": true,
    "fullAssessmentAvailable": false,
    "assessmentDomain": null,
    "assessmentPathway": null,
    "routerSupported": false,
    "differentialSupported": false,
    "adaptiveSupported": false,
    "safetyRelevant": true,
    "capabilityType": "MEDICAL_OR_SAFETY_NAVIGATION",
    "assessmentRoute": null,
    "explanationKey": "capability.cognitiveHelp"
  }
].map(Object.freeze));
C.forTopic=index=>C.topics.find(c=>c.topicIndex===index);
C.assessments=()=>C.topics.filter(c=>c.fullAssessmentAvailable);
C.route=c=>c&&['FULL_ASSESSMENT','ASSESSMENT_PATHWAY'].includes(c.capabilityType)?c.assessmentRoute:null;
})(globalThis.TopicCapabilities={});
