(function(P,G,V,E){'use strict';
// Only enduring, explicitly confirmed developmental context is eligible in v1.
// Route labels and assessment summaries never become clinical observations.
P.evidence=function(current=[]){if(!G.profileDecision({fieldId:'childhoodAttention',storageTarget:'memory',purpose:'user_controlled_profile',dataClass:'HIGHLY_SENSITIVE_HEALTH',userInitiated:true}))return [];const state=ADHD.store.state;if(['childhood','adolescent','adult','remember','decline'].includes(state.onset?.age))current=[...current,{concept:'adhd.onset',value:true}];if(Object.values(state.development||{}).some(v=>['yes','no','decline'].includes(v)))current=[...current,{concept:'adhd.developmental',value:true}];const eligible=P.store.list().filter(i=>i.fieldId==='childhoodAttention'&&i.confirmedByUser&&i.sourceType==='user_confirmed'&&i.temporality==='historical'&&['yes','no'].includes(i.value));
 if(new Set(eligible.map(i=>i.value)).size>1)return [];
 return eligible.slice(-1).flatMap(i=>['adhd.onset','adhd.developmental'].filter(concept=>!current.some(n=>n.concept===concept&&n.value!=='unknown')).map(concept=>({itemId:i.id,dataClass:i.dataClass,provenance:i.sourceType,temporality:i.temporality,node:V.node(concept,i.value==='yes',{id:i.id+':'+concept,source:'clarification',sourceType:'developmental_history',temporality:'history',questionIds:['profile.'+i.fieldId],revision:i.updatedAt,engineVersion:P.version})})));};
const adapt=V.adaptAssessment;V.adaptAssessment=function(name,store,module){const result=adapt(name,store,module);if(name!=='adhd'||result.invalid)return result;return {...result,evidence:[...result.evidence,...P.evidence(result.evidence).map(e=>e.node)]};};
// Entry duplicate protection reads the adapter, not arbitrary Profile UI state.
const entryQuestion=E.entryQuestion;E.entryQuestion=function(q,profile){const base=entryQuestion(q,profile);if(!base||q.id==='entryBroad'||!P.evidence().length)return base;const known=Object.fromEntries(P.evidence().map(e=>[e.node.concept,e.node.value]));const options=base.options.filter(o=>{const facts=Object.entries(o.effects);return !facts.length||facts.some(([p])=>!Object.hasOwn(known,p));});return options.some(o=>Object.keys(o.effects).length)?{...base,options}:null;};
P.routerContext=()=>P.evidence().map(({node,...metadata})=>({...metadata,concept:node.concept,value:node.value}));
const route=RouterV2.evaluate;RouterV2.evaluate=function(profile,session,safety){if(!RouterV2.validate(profile))return route(profile,session,safety);const copy=JSON.parse(JSON.stringify(profile));for(const e of P.routerContext())if(RouterV2.paths.includes(e.concept)&&copy.evidence.length<500)copy.evidence.push({id:'clarification:profileContext:'+e.concept,path:e.concept,value:e.value,source:'clarification',context:{subject:'self',temporality:'historical',polarity:e.value?'affirmed':'denied',quotationStatus:'direct_self_report',certainty:'reported'}});return route(RouterV2.normalize(copy),session,safety);};
P.proposeAssessment=function(domain){const module=globalThis[P.domains[domain]],result=module?.store.result;if(!result||result.revision!==module.store.state.revision||GlobalSafety.current().requiresInterruption)return false;return P.preview('assessment',{domain,version:module.version,revision:result.revision,summary:'assessment_review',outcomes:P.minimizedSummary(domain,result)},'historical');};
})(PersonalProfile,PrivacyGovernance,DifferentialV2,EntryFlow);



