(function(A,D,R){'use strict';
const valid=D.validEvidence;D.validEvidence=e=>e?.sourceModule==='eating'||e?.domain==='eating'?!!e&&['eating','adhd','trauma','mood','anxiety','ocd','router','clarification'].includes(e.sourceModule)&&e.domain===e.concept?.split('.')[0]&&Object.hasOwn(D.concepts,e.concept)&&valid({...e,sourceModule:'mood',domain:'mood',concept:'mood.low'}):valid(e);
for(const [k,label]of Object.entries(A.factLabels))D.concepts['eating.'+k]=label;
const modules=D.modules;D.modules=()=>({...modules(),eating:A});D.store.selected.eating=true;
A.factPaths={coherent:['shape.motive','arfid.sensory','arfid.interest','arfid.choking','arfid.vomiting','arfid.adverse','restriction.persistent','course.restriction','course.binge','course.comp','binge.loss',...A.questions.filter(q=>q.id.startsWith('compensation.')).map(q=>q.id)],restriction:['restriction.persistent','course.restriction'],weightMotive:['shape.motive'],fear:['shape.fear'],overvalue:['shape.overvalue'],binge:['binge.amount','binge.loss'],loss:['binge.loss'],bingeRecurrent:['course.binge'],compensation:A.questions.filter(q=>q.id.startsWith('compensation.')).map(q=>q.id),compRecurrent:['course.comp',...A.questions.filter(q=>q.id.startsWith('compensation.')).map(q=>q.id)],noComp:['course.comp',...A.questions.filter(q=>q.id.startsWith('compensation.')).map(q=>q.id)],distress:['binge.distress'],drivers:['arfid.sensory','arfid.interest','arfid.choking','arfid.vomiting','arfid.adverse'],notWeight:['shape.motive'],nutrition:['restriction.inadequate','arfid.nutrition','arfid.supplements','arfid.social',...A.questions.filter(q=>q.id.startsWith('function.')).map(q=>q.id)],impact:A.questions.filter(q=>q.id.startsWith('function.')).map(q=>q.id),persistent:['course.duration','course.pattern'],independent:['context.mood','context.ocd','context.trauma','context.adhd','context.access'],medical:['medical.gi','medical.contribution'],substance:['substance.medication','substance.contribution'],mood:['context.mood'],anxiety:['context.anxiety'],ocd:['context.ocd'],trauma:['context.trauma'],adhd:['context.adhd'],bdd:['shape.otherDefect']};
const adapt=D.adapt;D.adapt=(name,store,module)=>{if(name!=='eating')return adapt(name,store,module);const s=store?.state,r=store?.result;if(!s||!Number.isInteger(s.revision))return {evidence:[],ready:false,invalid:true};if(!r||r.revision!==s.revision||r.scope)return {evidence:[],ready:false,invalid:false};return {ready:true,invalid:A.questions.some(q=>Assessment.get(s,q.id)!==undefined&&!Assessment.validAnswer(q,Assessment.get(s,q.id))),evidence:Object.entries(r.facts).map(([k,v])=>D.fact('eating.'+k,v,'eating',A.factPaths[k],s.revision,['medical','substance'].includes(k)?'exclusion':k==='impact'?'functional_impairment':k==='persistent'?'duration':'structured_assessment','current',A.version))};};
const rule=(id,all,effects,key)=>({id,comparison:'eating_existing_domains',all,effects,explanationKey:key,reviewStatus:'unreviewed',version:D.version,moduleVersion:A.version,evidenceSource:'normalized_structured_evidence'});
for(const [id,req]of Object.entries(A.requirements)){const direction='eating_'+id;D.directions[direction]={label:A.copy[id],domain:'eating',required:req.map(k=>'eating.'+k)};const anchors=id==='restrictive'?['restriction','weightMotive']:id==='arfid'?['restriction','drivers','notWeight']:['binge'];D.rules.push(rule('DIFF_EATING_'+id.toUpperCase()+'_PARTIAL',Object.fromEntries(anchors.map(k=>['eating.'+k,true])),[{direction,support:2}],A.copy.partialReason),rule('DIFF_EATING_'+id.toUpperCase()+'_FULL',Object.fromEntries(req.map(k=>['eating.'+k,true])),[{direction,support:3}],A.copy.patternReason));}
for(const [key,direction]of [['mood','mood'],['anxiety','specific'],['ocd','ocd'],['trauma','trauma'],['adhd','adhd']])D.rules.push(rule('DIFF_EATING_CONTEXT_'+key.toUpperCase(),{['eating.'+key]:true},[{direction,support:key==='adhd'?1:2}],A.copy[key+'Compare']));
for(const key of ['medical','substance'])D.rules.push(rule('DIFF_EATING_'+key.toUpperCase(),{['eating.'+key]:true},Object.keys(A.requirements).map(id=>({direction:'eating_'+id,oppose:true})),A.copy[key+'Compare']));
const evaluate=D.evaluate;D.evaluate=(e,s,o)=>{const r=evaluate(e,s,o);if(r.blocked)return r;const eating=r.candidates.filter(c=>c.domain==='eating'&&c.level>=2);for(const c of eating)for(const [id,key]of [['mood','mood'],['gad','anxiety'],['ocd','ocd'],['trauma','trauma'],['adhd','adhd']])if(r.candidates.some(x=>x.id===id&&x.level>=2))r.possibleCooccurringPatterns.push({directions:[c.id,id],key:A.copy[key+'Compare']});if(r.evidence.some(x=>x.concept==='eating.bdd'&&x.value===true))r.unsupportedDomainFlags.push('eating.bdd');return r;};
const router=D.adaptRouter;D.adaptRouter=p=>{const evidence=router(p);if(!R.validate(p))return evidence;return [...evidence.filter(e=>e.concept!=='unsupported.eating'), ...[['restriction','restriction'],['weightFear','fear'],['loss','loss']].map(([a,b])=>D.fact('eating.'+b,p.eating[a],'router',['eating.'+a],0,'free_text_extraction','current',A.version))];};
})(globalThis.Eating,globalThis.Differential,globalThis.SymptomRouter);
