(function(R,G){'use strict';
const register=R.registerAssessmentDomain;R.registerAssessmentDomain=d=>{if(d.id!=='eating')return register(d);if(R.domains.has(d.id))throw Error('Duplicate domain');R.domains.set(d.id,Object.freeze({...d}));};R.registerAssessmentDomain({id:'eating',view:'eating',label:'eatingUI.title'});
R.fields.eating=['restriction','weightFear','binge','loss','compensation','avoidance','sensory','consequenceFear','intakeImpact'];R.paths.push(...R.fields.eating.map(k=>'eating.'+k));
const extract=R.extract;R.extract=raw=>{const p=extract(raw);if(typeof raw!=='string')return p;const text=raw.normalize('NFKC').toLowerCase();const clauses=text.split(/[.!?;\n\u3002\uff01\uff1f\uff1b]+/);const add=(path)=>{R.put(p,path,true);p.observations.push({path,value:true,context:{subject:'self',temporality:'current',polarity:'affirmed',uncertainty:false}});};
for(const t of clauses){if(/\b(?:my friend|my partner|he|she|they|if|hypothetical|used to|years ago|no longer)\b|\u4ed6|\u5979|\u5982\u679c|\u5047\u5982|\u4ee5\u524d|\u4e0d\u518d/.test(t))continue;
// This explicit causal phrase contains a negated appetite, not a negated depressed mood.
if(/(?:no appetite|not had much appetite|lost my appetite).{0,35}(?:since|after).{0,25}depress|\u6291\u90c1.{0,15}\u4ee5\u540e.{0,15}\u6ca1\u6709\u80c3\u53e3/.test(t)){add('mood.depressedMood');add('mood.appetiteChange');}
if(/\b(?:not|never|no)\b|\u6ca1\u6709|\u4e0d\u4f1a/.test(t))continue;
const patterns={restriction:/restrict(?:ing)? (?:food|what i eat|my (?:food|intake))|\u9650\u5236.{0,8}(?:\u8fdb\u98df|\u98df\u7269)/,weightFear:/(?:terrified|fear|afraid).{0,15}(?:gain(?:ing)? weight|weight gain)|\u5bb3\u6015.{0,8}(?:\u53d8\u80d6|\u4f53\u91cd\u589e\u52a0)/,binge:/\bbinge|\u66b4\u98df/,loss:/lose control|loss of control|out of control.{0,15}eat|\u8fdb\u98df\u5931\u63a7|\u5403.{0,8}\u5931\u63a7/,compensation:/make myself vomit|purging|compensat.{0,15}(?:eat|exercise)|\u50ac\u5410|\u8865\u507f.{0,8}\u8fd0\u52a8/,avoidance:/avoid (?:food|eating)|\u56de\u907f.{0,5}(?:\u98df\u7269|\u8fdb\u98df)/,sensory:/texture.{0,20}(?:gag|avers)|\u8d28\u5730.{0,10}(?:\u6076\u5fc3|\u4f5c\u5455)/,consequenceFear:/fear of (?:choking|vomiting)|\u5bb3\u6015(?:\u564e\u4f4f|\u5455\u5410)/,intakeImpact:/inadequate intake|cannot eat enough|interferes with.{0,15}eat|\u6444\u5165\u4e0d\u8db3|\u65e0\u6cd5\u5403\u591f/};for(const [k,re]of Object.entries(patterns))if(re.test(t))add('eating.'+k);
}return p;};
R.rules.push({id:'ROUTER_EATING_PATTERN_001',domain:'eating',relevance:'high',explanationKey:'eatingUI.routerReason',version:R.version,moduleVersion:Eating.version,reviewStatus:'unreviewed',when:p=>p.eating.restriction===true&&p.eating.weightFear===true||p.eating.binge===true&&p.eating.loss===true&&p.eating.compensation===true||p.eating.avoidance===true&&p.eating.intakeImpact===true&&(p.eating.sensory===true||p.eating.consequenceFear===true)});
const route=R.route;R.route=(p,choice)=>{const r=route(p,choice);r.unsupportedSignals=r.unsupportedSignals.filter(k=>k!=='eating');return r;};
})(globalThis.SymptomRouter,globalThis.GlobalSafety);
