(function(M){'use strict';
M.summary=function(s,r,l=0){const tr=p=>I18n.text(p,l),en=!!l,na=I18n.t("platform.m_8761c0d9409d",l);const value=id=>{const q=M.questions.find(q=>q.id===id),v=M.get(s,id);if(v===undefined||v==='')return na;return q?.type==='month'?v:q?.options?.find(o=>o[0]===v)?.[l+1]||String(v);};
const lines=[I18n.t("platform.m_280f578550db",l),M.disclaimer[l],`${I18n.t("platform.m_dadabfd04a14",l)}: ${r.assessedAt||'—'} | ${I18n.t("platform.m_bc929c973d77",l)}: ${r.version}`];
const heading=(z,e)=>lines.push('',I18n.select(z,e,l));const add=(z,e,str)=>lines.push(`${I18n.select(z,e,l)}: ${str}`);const selections=(prefix)=>{const qs=M.questions.filter(q=>q.id.startsWith(prefix)&&M.visible(q,s));const groups=[['yes',...I18n.pair("platform.m_79da8d1cf508")],['unknown',...I18n.pair("platform.m_b3ea1fcb5c85")]];return groups.map(([v,z,e])=>`${I18n.select(z,e,l)} — ${qs.filter(q=>M.get(s,q.id)===v).map(q=>tr(q.label)).join('; ')||'—'}`).join(' | ')+` | ${I18n.t("platform.m_33ec93923d9d",l)}: ${qs.filter(q=>M.get(s,q.id)==='no').length}; ${I18n.t("platform.m_bf38b36359b6",l)}: ${qs.filter(q=>M.get(s,q.id)===undefined).length}`;};
heading(...I18n.pair("platform.m_67584ffd7c2b"));lines.push(value('intro.concern'));
heading(...I18n.pair("platform.m_165d4879930f"));add('PHQ-9','PHQ-9',`${r.phq.total??'—'}/27 (${r.phq.band===null?na:tr(M.phqBands[r.phq.band])}); ${I18n.t("platform.m_245d2215d89e",l)}: ${Array.from({length:9},(_,i)=>s.phq?.[i]??'—').join(', ')}; ${I18n.t("platform.m_68a46df85661",l)}: ${r.phq.item9??'—'}`);
for(const [id,z,e]of M.symptomDomains){const d=s.symptoms?.[id]||{};if(d.present==='yes')lines.push(`${I18n.select(z,e,l)}: ${['frequency','duration','changed','severity'].map(k=>value('symptoms.'+id+'.'+k)).join(' / ')}${d.onset?' / '+d.onset:''}${id==='motor'?' / '+value('symptoms.motor.observed'):''}`);}
add(...I18n.pair("platform.m_5f6f9bacfca3"),I18n.t("platform.m_a6a5d1eddcf2",l));add(...I18n.pair("platform.m_5b3c44f91cea"),r.absent.map(id=>tr(M.symptomDomains.find(d=>d[0]===id).slice(1))).join('; ')||'—');add(...I18n.pair("platform.m_215a04f358f7"),r.unresolvedSymptoms.map(id=>tr(M.symptomDomains.find(d=>d[0]===id).slice(1))).join('; ')||'—');
heading(...I18n.pair("platform.m_bbb81bde3cc8"));for(const id of ['onset','duration','together','pattern','previous','trend','chronic'])add(tr(M.questions.find(q=>q.id==='course.'+id).label),tr(M.questions.find(q=>q.id==='course.'+id).label),value('course.'+id));if(s.course?.chronic==='yes'){add(...I18n.pair("platform.m_13cf67a5abd8"),value('course.years')+' / '+value('course.remission'));lines.push(selections('course.associated.'));}
lines.push(M.functionalDomains.map(([id,z,e])=>`${I18n.select(z,e,l)}: ${value('function.'+id)}`).join('; '));add(...I18n.pair("platform.m_73ecdb799284"),value('function.distress'));
heading(...I18n.pair("platform.m_0c90365c7db3"));add(...I18n.pair("platform.m_a4bced56ac28"),value('mania.period')+' / '+value('mania.pastMania'));if(s.mania?.period!=='no'){lines.push(selections('mania.features.'));lines.push(['together','duration','noticed','impact','hospital','psychosis','current','related'].map(k=>`${tr(M.questions.find(q=>q.id==='mania.'+k).label)}: ${value('mania.'+k)}`).join('; '));}
heading(...I18n.pair("platform.m_bc6fae5bf3c2"));lines.push(selections('medical.conditions.'));add(...I18n.pair("platform.m_0d9e69895ee1"),['evaluation','labs','temporal'].map(k=>value('medical.'+k)).join(' / '));
heading(...I18n.pair("platform.m_23ad81b53b42"));lines.push(selections('substance.exposures.'));add(...I18n.pair("platform.m_ddb9292f4ba0"),value('substance.temporal')+' / '+value('substance.before'));
heading(...I18n.pair("platform.m_7f5d7dac7c51"));lines.push(value('stress.present'));if(s.stress?.present!=='no'){lines.push(selections('stress.types.'));add(...I18n.pair("platform.m_d79756b50194"),['date','onset','linked','impact','ended'].map(k=>value('stress.'+k)).join(' / '));}
heading(...I18n.pair("platform.m_117395849264"));lines.push(M.sections[9].questions.map(q=>`${tr(q.label)}: ${value(q.id)}`).join('; '));if(r.safety.action==='immediate')lines.push(I18n.t("platform.m_03eb09b0c11d",l));else if(r.safety.action==='noneTriggered')lines.push(I18n.t("platform.m_9db5e4dd5753",l));else lines.push(I18n.t("platform.m_09f6fc3b2b8e",l));
heading(...I18n.pair("platform.m_0b679bd1b527"));add(...I18n.pair("platform.m_bfcd47351836"),r.leading?tr(r.directions.find(d=>d.id===r.leading).name):(I18n.t("platform.m_8fda7212da08",l)));r.directions.forEach(d=>lines.push(`${tr(d.name)}: ${tr(M.levels[d.level])}`));const lead=r.directions.find(d=>d.id===r.leading);if(lead){add(...I18n.pair("platform.m_54f0a30e38d1"),lead.support.map(x=>tr(x.text)).join(' '));add(...I18n.pair("platform.m_a39248c46654"),[...lead.against,...lead.unresolved].map(x=>tr(x.text)).join(' '));}add(...I18n.pair("platform.m_91633d191f75"),r.ruleouts.map(x=>tr(x.text)).join(' ')|| (I18n.t("platform.m_8d0d3de63cbf",l)));
heading(...I18n.pair("platform.m_64b120050e43"));lines.push(I18n.t("platform.m_635bb8d8f3b4",l));lines.push(...r.limitations.map(x=>tr(x.text)));return lines.join('\n');
};
})(globalThis.Mood=globalThis.Mood||{});
