(function(A){'use strict';
A.tri=v=>v==='yes'?true:v==='no'?false:'unknown';
A.any=values=>values.some(v=>v===true)?true:values.length&&values.every(v=>v===false)?false:'unknown';
A.all=values=>values.some(v=>v===false)?false:values.length&&values.every(v=>v===true)?true:'unknown';
A.emptyState=()=>({intro:{},inattention:{},hyper:{},development:{},onset:{},settings:{},settingImpact:{},function:{},compensation:{},course:{},sleep:{},medical:{},substance:{},context:{},safety:{},revision:0});
A.store={state:A.emptyState(),step:'intro',error:[],result:null};
A.visible=(q,s)=>!q.id.startsWith('settingImpact.')||s.settings?.[q.id.split('.')[1]]!=='no';
A.plan=s=>A.sections.map(sec=>({...sec,questions:sec.questions.filter(q=>A.visible(q,s))}));
A.setAnswer=(s,path,value)=>{const q=A.questions.find(q=>q.id===path);if(!q||!Assessment.validAnswer(q,value))throw Error('Invalid ADHD answer');const next=Assessment.set(s,path,value);if(path.startsWith('settings.')&&value==='no')delete next.settingImpact[path.split('.')[1]];return next;};
A.update=(p,v)=>{A.store.state=A.setAnswer(A.store.state,p,v);A.store.result=null;};
A.clear=()=>{A.store={state:A.emptyState(),step:'intro',error:[],result:null};};
A.count=function(s,group){const values=A.symptoms[group].map(k=>s[group]?.[k]);const count=values.filter(v=>['2','3'].includes(v)).length,unknown=values.filter(v=>!['0','1','2','3'].includes(v)).length;return {count,unknown,threshold:5,present:count>=5?true:count+unknown>=5?'unknown':false};};
A.assess=function(s){
 const counts={inattention:A.count(s,'inattention'),hyper:A.count(s,'hyper')};
 const missing=A.questions.filter(q=>A.visible(q,s)&&!q.optional&&(!Assessment.validAnswer(q,Assessment.get(s,q.id))||['unknown','remember','decline'].includes(Assessment.get(s,q.id)))).map(q=>q.id);
 const developmental=A.any(['school','organization','tasks','restless','feedback'].map(k=>A.tri(s.development?.[k])));
 const onset=s.onset?.age==='childhood'?true:['adolescent','adult'].includes(s.onset?.age)?false:'unknown';
 const settingNames=['work','school','home','social'],positiveSettings=settingNames.filter(k=>s.settings?.[k]==='yes');
 const unknownSettings=settingNames.filter(k=>!['yes','no'].includes(s.settings?.[k]));
 const crossSetting=s.settings?.narrow==='yes'?false:positiveSettings.length>=2?true:positiveSettings.length+unknownSettings.length>=2?'unknown':false;
 const functionValues=A.questions.filter(q=>q.id.startsWith('function.')).map(q=>Assessment.get(s,q.id));
 const visibleImpact=functionValues.some(v=>['moderate','severe'].includes(v))?true:functionValues.every(v=>['none','mild','na'].includes(v))?false:'unknown';
 const impairment=visibleImpact===false&&s.compensation?.burden==='yes'?'unknown':visibleImpact;
 const duration=s.course?.duration==='sixPlus'?true:s.course?.duration==='underSix'?false:'unknown';
 const course=s.course?.pattern==='longstanding'?true:['episodic','situational','recent'].includes(s.course?.pattern)?false:'unknown';
 const alternatives=Object.keys(s.context||{}).filter(k=>s.context[k]==='yes').map(k=>'context.'+k);
 const sleep=A.any(['short','insomnia','irregular','daytime','breathing','linked'].map(k=>A.tri(s.sleep?.[k])));
 const medical=A.any([A.tri(s.medical?.contribution),A.tri(s.onset?.sudden)]),substance=A.tri(s.substance?.contribution);
 const ruleouts=[];if(sleep!==false)ruleouts.push('sleep.linked');if(medical!==false)ruleouts.push('medical.contribution');if(substance!==false)ruleouts.push('substance.contribution');
 if(s.compensation?.burden==='yes'&&impairment==='unknown')missing.push('compensation.burden');
 const contextValues=['onlyMood','onlyAnxiety','onlyOCD','onlyTrauma','activation'].map(k=>A.tri(s.context?.[k]));
 const independent=contextValues.some(v=>v===true)?false:contextValues.every(v=>v===false)?true:'unknown';
 const facts={sleepClear:sleep==='unknown'?'unknown':!sleep,current:A.any(Object.values(counts).map(x=>x.present)),developmental,onset,crossSetting,impairment,persistent:A.all([duration,course]),independent};
 const conflicts=[];if(developmental===true&&s.onset?.age==='adult')conflicts.push('onset.age');if(positiveSettings.length>=2&&s.settings?.narrow==='yes')conflicts.push('settings.narrow');
 const scope=s.intro?.adult!=='yes'||s.intro?.agree!=='yes';
 const all=Object.values(facts).every(v=>v===true),negative=Object.values(facts).some(v=>v===false);
 const consistency=scope?'insufficient':all&&!ruleouts.length&&!conflicts.length?'high':facts.current===true&&!negative?'moderate':facts.current===true?'low':'insufficient';
 return {version:A.version,revision:s.revision,reviewStatus:'unreviewed',instrument:'custom_structured_not_validated',score:null,counts,facts,positiveSettings,unknownSettings,visibleImpact,compensation:A.tri(s.compensation?.burden),contributions:{sleep,medical,substance},support:Object.keys(facts).filter(k=>facts[k]===true),opposing:Object.keys(facts).filter(k=>facts[k]===false),missing:[...new Set(missing)],ruleouts,alternatives,conflicts,consistency,scope};
};
A.ruleCatalog=[{id:'ADHD_DEVELOPMENTAL_PATTERN_001',version:A.version,reviewStatus:'unreviewed',criteria:{symptomsPerCluster:5,frequency:'often_or_very_often',ageScope:'adult_18plus',onset:'before12_context',duration:'sixPlus',course:'longstanding',settings:2,impact:'moderate_or_severe'},instrument:'custom_not_validated'}];
})(globalThis.ADHD);
