(function(A,D,R,G){'use strict';
// Reuse the existing shared-signal questions; add explicit current danger questions,
// never map ordinary ADHD impulsivity or restlessness to an emergency signal.
const safetyQuestions=Trauma.sections.filter(s=>s.id.startsWith('safety')).flatMap(s=>s.questions).map(q=>({...q}));
for(const [p,label]of [['mania.severelyReducedNeedForSleep','adhdSafety.sleep'],['mania.markedlyIncreasedEnergy','adhdSafety.energy'],['mania.grandiosity','adhdSafety.grandiosity'],['mania.recklessDriving','adhdSafety.driving'],['mania.impairedJudgment','adhdSafety.judgment'],['mania.inabilityToControlBehavior','adhdSafety.control'],['other.immediateDanger','adhdSafety.danger']])safetyQuestions.push({id:'safety.'+p,label:I18n.pair(label),options:['yes','no','unknown'].map(v=>[v,...I18n.pair(({yes:'adhdUI.opt_yes',no:'adhdUI.opt_no',unknown:'adhdUI.opt_unknown'})[v])])});
A.sections.splice(1,0,...Array.from({length:Math.ceil(safetyQuestions.length/5)},(_,i)=>({id:'safety'+i,label:'adhdUI.safety',questions:safetyQuestions.slice(i*5,(i+1)*5)})));A.questions=A.sections.flatMap(s=>s.questions);
const guard=G.guard,reset=G.reset,collect=G.collect,update=A.update;
G.guard=target=>guard(target==='adhd'?'screen':target);G.reset=()=>{A.clear();reset();};
A.update=(p,v)=>{update(p,v);if(p.startsWith('safety.'))G.answer(p.slice(7),A.tri(v));};
G.collect=()=>{const base=collect();if(!A.store.state.revision)return base;const signals=G.empty();let failed=false;for(const q of safetyQuestions){const v=Assessment.get(A.store.state,q.id);if(v!==undefined&&!['yes','no','unknown'].includes(v))failed=true;G.put(signals,q.id.slice(7),A.tri(v));}const merged=G.merge([base.signals,signals]);return {...G.evaluate(merged.signals,{failed:failed||base.assessmentStatus==='unable_to_assess'}),signals:merged.signals,sources:[...base.sources,{module:'adhd',revision:A.store.state.revision}]};};
const valid=D.validEvidence;D.validEvidence=e=>e?.sourceModule==='adhd'||e?.domain==='adhd'?!!e&&['adhd','trauma','mood','anxiety','ocd','router','clarification'].includes(e.sourceModule)&&e.domain===e.concept?.split('.')[0]&&Object.hasOwn(D.concepts,e.concept)&&valid({...e,sourceModule:'mood',domain:'mood',concept:'mood.low'}):valid(e);
for(const [k,v]of Object.entries(A.factLabels))D.concepts['adhd.'+k]=v;
for(const [k,v]of Object.entries({sleep:'adhdUI.sleep',medical:'adhdUI.medical',substance:'adhdUI.substanceCompare',onlyMood:'adhdUI.moodCompare',onlyAnxiety:'adhdUI.anxietyCompare',onlyOCD:'adhdUI.ocdCompare',onlyTrauma:'adhdUI.traumaCompare',activation:'adhdUI.bipolarCompare'}))D.concepts['adhd.'+k]=v;
const modules=D.modules;D.modules=()=>({...modules(),adhd:A});D.store.selected.adhd=true;
const adapt=D.adapt;D.adapt=(name,store,module)=>{if(name!=='adhd')return adapt(name,store,module);const s=store?.state,r=store?.result;if(!r||r.revision!==s.revision||r.scope)return {evidence:[],ready:false,invalid:false};const paths={sleepClear:['sleep'],current:['inattention','hyper'],developmental:['development'],onset:['onset'],crossSetting:['settings','settingImpact'],impairment:['function','compensation'],persistent:['course'],independent:['context']};return {ready:true,invalid:A.questions.filter(q=>A.visible(q,s)).some(q=>!Assessment.validAnswer(q,Assessment.get(s,q.id))),evidence:[...Object.entries(r.facts).map(([k,v])=>D.fact('adhd.'+k,v,'adhd',A.questions.filter(q=>paths[k].some(prefix=>q.id.startsWith(prefix+'.'))).map(q=>q.id),s.revision,'structured_assessment',['developmental','onset'].includes(k)?'history':'current',A.version)),...Object.entries(r.contributions).map(([k,v])=>D.fact('adhd.'+k,v,'adhd',A.questions.filter(q=>q.id.startsWith(k+'.')||k==='medical'&&q.id==='onset.sudden').map(q=>q.id),s.revision,'exclusion','current',A.version)),...['onlyMood','onlyAnxiety','onlyOCD','onlyTrauma','activation'].map(k=>D.fact('adhd.'+k,A.tri(s.context[k]),'adhd',['context.'+k],s.revision,'structured_assessment','current',A.version))]};};
D.directions.adhd={label:'adhdUI.title',domain:'adhd',required:Object.keys(A.factLabels).map(k=>'adhd.'+k)};
const rule=(id,all,effects,key)=>({id,comparison:'adhd_existing_domains',all,effects,explanationKey:key,evidenceSource:'normalized_structured_evidence',reviewStatus:'unreviewed',version:D.version,moduleVersion:A.version});
D.rules.push(rule('DIFF_ADHD_CURRENT_001',{'adhd.current':true},[{direction:'adhd',support:1}],'adhdUI.partialReason'),rule('DIFF_ADHD_DEVELOPMENTAL_002',Object.fromEntries(Object.keys(A.factLabels).map(k=>['adhd.'+k,true])),[{direction:'adhd',support:3}],'adhdUI.patternReason'));
for(const [k,domain,key]of [['onlyMood','mood','adhdUI.moodCompare'],['onlyAnxiety','gad','adhdUI.anxietyCompare'],['onlyOCD','ocd','adhdUI.ocdCompare'],['onlyTrauma','trauma','adhdUI.traumaCompare'],['activation','bipolar','adhdUI.bipolarCompare']])D.rules.push(rule('DIFF_ADHD_'+k.toUpperCase()+'_003',{['adhd.'+k]:true,'adhd.current':true},[{direction:'adhd',oppose:true},{direction:domain,support:2}],key));
for(const [k,key]of [['sleep','adhdUI.sleep'],['medical','adhdUI.medical'],['substance','adhdUI.substanceCompare']])D.rules.push(rule('DIFF_ADHD_'+k.toUpperCase()+'_004',{['adhd.'+k]:true},[{direction:'adhd',oppose:true}],key));
const routerEvidence=D.adaptRouter;D.adaptRouter=p=>[...routerEvidence(p),...(R.validate(p)?[D.fact('adhd.developmental',p.adhd.developmental,'router',['adhd.developmental'],0,'free_text_extraction','history',R.version)]:[])];
const evaluate=D.evaluate;D.evaluate=(e,s,o)=>{const r=evaluate(e,s,o);if(r.blocked)return r;const candidate=r.candidates.find(c=>c.id==='adhd');if(candidate?.level>=2){for(const [id,key]of [['mood','adhdUI.moodCompare'],['gad','adhdUI.anxietyCompare'],['ocd','adhdUI.ocdCompare'],['trauma','adhdUI.traumaCompare']])if(r.candidates.some(c=>c.id===id&&c.level>=2))r.possibleCooccurringPatterns.push({directions:['adhd',id],key});}return r;};
})(globalThis.ADHD,globalThis.Differential,globalThis.SymptomRouter,globalThis.GlobalSafety);
