(function(E,R,C,G){'use strict';
const text=key=>esc(I18n.t(key,lang));
const button=(action,key)=>`<button type="button" class="secondary" data-entry-action="${action}">${text(key)}</button>`;
const originalRender=R.render,originalBind=R.bind;
E.choices=()=>`<div class="entry-options">${C.assessments().map(c=>`<button type="button" class="secondary" data-entry-start="${c.assessmentDomain}" data-router-start="${c.assessmentDomain}">${text(C.domainKeys[c.assessmentDomain])}</button>`).join('')}</div>`;
E.escapes=()=>`<div class="entry-escapes">${button('direct','entry.direct')}${button('knowledge','entry.knowledge')}${button('edit','entry.edit')}${button('stop','entry.stop')}<button class="secondary" data-view="care">${text('entry.professional')}</button></div>`;
R.render=function(){
 if(!E.store.active)return originalRender();
 if(E.checkSafety().show)return G.panel(G.current());
 const s=E.store,q=s.question,r=R.store.result;
 if(s.state==='ENTRY_DESCRIPTION')return `<section class="page"><p>${text('entry.editHelp')}</p>${G.entryHTML()}${button('direct','entry.direct')}</section>`;
 const asking=['ENTRY_BROAD_CLARIFICATION','ROUTER_CLARIFICATION'].includes(s.state)&&q;
 let body='';
 if(asking)body=`<p>${text('entry.started')}</p><p class="entry-progress" role="status" aria-live="polite" aria-atomic="true">${esc(I18n.t('entry.progress',lang,{current:Math.min(s.used+1,E.maxQuestions),max:E.maxQuestions}))}</p><fieldset><legend>${text(q.questionKey)}</legend><div class="entry-options">${q.options.map(o=>`<button type="button" class="secondary" data-entry-question="${q.id}" data-entry-answer="${o.value}">${text(o.labelKey)}</button>`).join('')}</div></fieldset>`;
 else if(s.state==='DIRECT_ASSESSMENT_SELECTION')body=`<p>${text('entry.noSingle')}</p>${E.choices()}`;
 else if(s.state==='STOPPED')body=`<p role="status">${text('entry.stopped')}</p>${E.choices()}`;
 else if(s.state==='UNSUPPORTED_NAVIGATION')body=`<p>${text('router.unsupported')}</p>${(r?.unsupportedDomainFlags||[]).map(flag=>`<button class="secondary" data-topic="${RouterV2.unsupported[flag]}">${text('rv2.knowledge')}: ${esc(topics[RouterV2.unsupported[flag]][1+lang])}</button>`).join('')}`;
 else body=`${r?.primaryRoute?`<p>${text('router.recommended')}: ${text(C.domainKeys[r.primaryRoute])}</p>`:`<p>${text('entry.multiple')}</p>`}${(r?.candidateRoutes||[]).map(c=>`<article class="panel"><h2>${text(C.domainKeys[c.domain])}</h2><h3>${text('router.why')}</h3><ul>${c.explanationKeys.map(k=>`<li>${text(k)}</li>`).join('')}</ul><button class="${c.domain===r.primaryRoute?'primary':'secondary'}" data-entry-start="${c.domain}" data-router-start="${c.domain}">${text('router.start')}</button></article>`).join('')}`;
 if(asking&&r.candidateRoutes.length)body+=`<details><summary>${text('router.alternatives')}</summary>${E.choices()}</details>`;
 return `<section class="page entry-flow" aria-labelledby="entry-heading" data-entry-state="${s.state.toLowerCase()}"><h1 id="entry-heading" tabindex="-1">${text('entry.heading')}</h1><p>${text('router.notDiagnosis')}</p>${body}${s.history.length&&s.used<E.maxQuestions?button('back','entry.back'):''}${E.escapes()}<details><summary>${text('entry.add')}</summary><form id="entry-add-form"><label for="entry-add-text">${text('entry.addHelp')}</label><textarea id="entry-add-text" maxlength="4000" rows="3" required></textarea><button type="submit" class="secondary">${text('entry.update')}</button></form></details><p class="muted">${text('entry.privacy')}</p></section>`;
};
R.bind=function(){originalBind();
 document.querySelectorAll('[data-entry-answer]').forEach(b=>b.onclick=()=>{E.respond(b.dataset.entryQuestion,b.dataset.entryAnswer);navigate(R.resume());document.getElementById('entry-heading')?.focus();});
 document.querySelectorAll('[data-entry-action]').forEach(b=>b.onclick=()=>{if(b.dataset.entryAction==='back'){E.back();render();}else navigate(E.action(b.dataset.entryAction));document.getElementById('entry-heading')?.focus();});
 document.querySelectorAll('[data-entry-start]').forEach(b=>b.onclick=()=>navigate(E.start(b.dataset.entryStart)));
 const form=document.getElementById('entry-add-form'),input=document.getElementById('entry-add-text');
 if(input)input.oninput=()=>{const parsed=G.validateExtraction(G.extract(input.value));if(G.evaluate(parsed.signals,{failed:!parsed.valid}).requiresInterruption)navigate(E.addText(input.value));};
 if(form)form.onsubmit=e=>{e.preventDefault();if(input.value.trim())navigate(E.addText(input.value));};
};
})(EntryFlow,SymptomRouter,TopicCapabilities,GlobalSafety);
